### ISSUE TITLE
Cleaning info for Windyridge - Player home in Winterhold

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1005]
### [Windyridge - Player home in Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/8046)

version 1.04

```yaml
  - name: 'windyridge.esp'
    dirty:
      - <<: *quickClean
        crc: 0x5877F38B
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 5
    clean:
      - crc: 0x81420997
        util: 'SSEEdit v4.0.3'
```
