### ISSUE TITLE
Cleaning info for Winterhold Fully Restored

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1006]
[Winterhold Fully Restored](https://www.nexusmods.com/skyrimspecialedition/mods/10428)

version 1.1

```yaml
  - name: 'Winterhold Fully Restored.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x7B03E956
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 77
        udr: 389
        nav: 7
      - <<: *reqManualFix
        crc: 0x328E0E90
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 7
```
