### ISSUE TITLE
Cleaning info for Agent of Righteous Might

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1027]
#### [Agent of Righteous Might](https://www.nexusmods.com/skyrimspecialedition/mods/29067)
version: 1.2.3
```yaml
  - name: 'AgentOfRighteousMight.esp'
    dirty:
      - <<: *quickClean
        crc: 0x162BF53D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 32
    clean:
      - crc: 0x90DDCB9F
        util: 'SSEEdit v4.0.3'
```
