### ISSUE TITLE
Expanded Skyrim Weaponry 

### ISSUE THREAD

**Issue by yggdrasil75** [loot/skyrimse#1038]
[Skyrim SE Expanded Skyrim Weaponry](https://www.nexusmods.com/skyrimspecialedition/mods/2300)

LrsamwaysExpandedSkyrimWeaponry.esp crc: `12bb1808` verified clean xedit 4.0.3

LOOT Masterlist Entries

```yaml
  - name: 'LrsamwaysExpandedSkyrimWeaponry.esp'
    clean:
      - crc: 0x12BB1808
        util: 'SSEEdit v4.0.3'
```
