### ISSUE TITLE
Add Cleaning Info for Outlaws Refuges and Hidden Hideouts

### ISSUE THREAD

**Issue by Xahtax** [loot/skyrimse#1039]
[Outlaws Refuges](https://www.nexusmods.com/skyrimspecialedition/mods/8445)
version 1.2

```yaml
  - name: 'OutlawsRefuges.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x7B0B0CBC
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 68
        nav: 1
      - <<: *reqManualFix
        crc: 0x1C430862
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1
```

[Hidden Hideouts](https://www.nexusmods.com/skyrimspecialedition/mods/2625)
version 1.0

```yaml
  - name: 'Hidden Hideouts of Skyrim - Merged.esp'
    dirty:
      - <<: *quickClean
        crc: 0x2728CD25
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 129
    clean:
      - crc: 0x0C31253F
        util: 'SSEEdit v4.0.3'

  - name: 'Hidden Hideouts of Skyrim - Merged - No Map Markers.esp'
    dirty:
      - <<: *quickClean
        crc: 0xC30F791D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 129
    clean:
      - crc: 0x43D7FFF2
        util: 'SSEEdit v4.0.3'

  - name: 'Hidden Hideouts of Skyrim - Merged - Deep Immersion.esp'
    dirty:
      - <<: *quickClean
        crc: 0xCBEBD91A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 129
    clean:
      - crc: 0xAE1C1BCE
        util: 'SSEEdit v4.0.3'

  - name: 'Hidden Hideouts of Skyrim - Merged NavMeshed.esp'
    dirty:
      - <<: *quickClean
        crc: 0xB7B3DB7D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 125
    clean:
      - crc: 0x973BEFC7
        util: 'SSEEdit v4.0.3'

  - name: 'Hidden Hideouts of Skyrim - Merged NavMeshed - No Map Markers.esp'
    dirty:
      - <<: *quickClean
        crc: 0x33DF7947
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 133
    clean:
      - crc: 0x3571EA07
        util: 'SSEEdit v4.0.3'

  - name: 'Hidden Hideouts of Skyrim - Merged NavMeshed - Deep Immersion.esp'
    dirty:
      - <<: *quickClean
        crc: 0x1E516349
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 133
    clean:
      - crc: 0xE408C84B
        util: 'SSEEdit v4.0.3'
```
