### ISSUE TITLE
Update Cleaning infor for 3DNPC

### ISSUE THREAD

**Issue by Xahtax** [loot/skyrimse#1050]
[Interesting NPCs SE (3DNPC)](https://www.nexusmods.com/skyrimspecialedition/mods/29194) 4.3.8Beta

````
  - name: '3DNPC.esp'
    clean:
      - crc: 0xBCE1E037
        util: 'SSEEdit v4.0.3'
````
