### ISSUE TITLE
Blood on the Ice Redux

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1055]
[Blood on the Ice Redux](https://www.nexusmods.com/skyrimspecialedition/mods/6126)

**Requirements**

> You NEED to have the Unofficial Skyrim Special Edition Patch, or you'll get a CTD. You have been warned.
> 
> As this quest has unvoiced dialogues, is highly recommendable to install Fuz Ro D'oh (and SKSE64, of course). You can use this mod without it, but the dialogues may appear and disappear in the blink of an eye.

**Load order**

> Shouldn't be a problem where you place this mod in your load order, but pretty high in the list, near the .esm files. But, if you have Quest Conflict Fixes in your mod list, place BOTI.esp below QCF esp file.

[Quest Conflict Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/12412)

Default sorting places `Quest Conflict Fixes.esp` after `BOTI.esp`.

![image](https://user-images.githubusercontent.com/1944639/76797250-02b73200-67c5-11ea-9cbc-a570320b0be7.png)

**Compatibility**

> 
> The only incompatibilities that I can think about are mods that modify the original Blood on the Ice quests (MS11 and MS11Kicker) or any of their attached scripts or dialogues. Windhelm or NPC enhancements shouldn't be a problem as long as they allow the original quest to run properly.
> 
> If you want to run Open Cities with BOTI Redux you should use [Zelazko's Open Cities Patch](https://www.nexusmods.com/skyrimspecialedition/mods/27556).

**Cleaning Info**

Version 2.1.1
```yaml
  - name: 'BOTI.esp'
    clean:
      - crc: 0x0900486D
        util: 'SSEEdit v4.0.3'
      # ESL version from [Zelazko''s Open Cities Patch](https://www.nexusmods.com/skyrimspecialedition/mods/27556).
      - crc: 0x14A9986A
        util: 'SSEEdit v4.0.3'
```

---

- [x] Add after for `Quest Conflict Fixes.esp`.
- [x] Add Open Cities patch message.
- [x] Add cleaning info.
- [x] Add requirement Fuz Ro D'oh.
