### ISSUE TITLE
Lanterns Of Skyrim II

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1063]
[Lanterns Of Skyrim II](https://www.nexusmods.com/skyrimspecialedition/mods/30817)

---

**Cleaning info**

Version 2.0

```yaml
  - name: 'Lanterns Of Skyrim II.esm'
    dirty:
      - <<: *quickClean
        crc: 0xEA776E36
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 14
    clean:
      - crc: 0xCB26A2AB
        util: 'SSEEdit v4.0.3'
```
```yaml
  - name: 'LoS II - Tamriel Master Lights.esp'
    dirty:
      - <<: *quickClean
        crc: 0x0D116849
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x19287E1D
        util: 'SSEEdit v4.0.3'
```
```yaml
  - name: 'LoS II - Lantern Workers.esp'
    dirty:
      - <<: *quickClean
        crc: 0x54F40975
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 25
    clean:
      - crc: 0xC5DCAADF
        util: 'SSEEdit v4.0.3'
```

---

**Compatibility**

`Lanterns Of Skyrim II.esm`

- Not compatible with [CLARALUX SSE - Controllable Lights Everywhere](https://www.nexusmods.com/skyrimspecialedition/mods/2371) `CLARALUX SSE.esp`.

- Not compatible with [Blowing in the Wind](https://www.nexusmods.com/skyrimspecialedition/mods/5124) `Blowing in the Wind SSE.esp`. Use [WiZkiD Signs](https://www.nexusmods.com/skyrimspecialedition/mods/30481) instead.

![image](https://user-images.githubusercontent.com/1944639/77179895-11e9f880-6ac1-11ea-8ff0-47610d87997a.png)

`LoS II - Lanterns Workers.esp`

>This addon was built based on the original vanilla environment so it is not compatible with all those mods that heavily alter the appearance of roads and settlements.

- Not compatible with [Enhanced Solitude SSE](https://www.nexusmods.com/skyrimspecialedition/mods/27816) `Enhanced Solitude SSE.esp`.

`LoS II - Tamriel Master Lights.esp`

>Los II - TML isn't compatible with any other exterior lighting mod.

- ` RLO - Exteriors.esp` from [Realistic Lighting Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/844)

- `ELFX - Exteriors.esp` from [Enhanced Lights and FX](https://www.nexusmods.com/skyrimspecialedition/mods/2424).

---

**Other Notes**

`LoS II - Tamriel Master Lights.esp` Cell location missing.

![image](https://user-images.githubusercontent.com/1944639/77176560-2ecffd00-6abc-11ea-86c9-0edbcd947e1f.png)

`LoS II - Tamriel Master Lights.esp` modifies two WRLD Object Bounds.

![image](https://user-images.githubusercontent.com/1944639/77177464-72773680-6abd-11ea-8dbe-bf2c3b648ce3.png)

![image](https://user-images.githubusercontent.com/1944639/77177549-9d618a80-6abd-11ea-8f29-72a48703f330.png)

`LoS II - Tamriel Master Lights.esp` Requires bash tags `Delev`,`Invent`.

![image](https://user-images.githubusercontent.com/1944639/77177985-5627c980-6abe-11ea-827a-3f3021a7b1c0.png)

![image](https://user-images.githubusercontent.com/1944639/77178483-0ac1eb00-6abf-11ea-84a1-03463ab0158a.png)

`LoS II - Lantern Workers.esp` Cell location missing.

![image](https://user-images.githubusercontent.com/1944639/77176970-bc135180-6abc-11ea-9b28-36d748e5f3c3.png)

`LoS II - LotD patch.esp` master order.

![image](https://user-images.githubusercontent.com/1944639/77174859-a2243f80-6ab9-11ea-9bbb-b6a5623e6124.png)

One conflict with patch.

![image](https://user-images.githubusercontent.com/1944639/77174994-d39d0b00-6ab9-11ea-8121-e3e3f2b58e8c.png)
