### ISSUE TITLE
The Great Cities of Skyrim and JKs skyrim compatibility patch

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1081]
[Xenons City patch (The Great Cities of Skyrim and JKs skyrim compatibility patch)](https://www.nexusmods.com/skyrimspecialedition/mods/25282)

version 3.0

```yaml
  - name: 'The Great JK''s Cities.esp'
    clean:
      - crc: 0xE0CA35BC
        util: 'SSEEdit v4.0.3'
```

- [x] Update cleaning info.
- [x] Update The Great Cities of Skyrim and JKs skyrim compatibility.
- [x] Add patch message.

_Originally posted by @CptMcSplody in https://github.com/loot/skyrimse/issues/741#issuecomment-611064231_
