### ISSUE TITLE
aMidianBorn Content Addon

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1146]
[aMidianBorn Content Addon](https://www.nexusmods.com/skyrimspecialedition/mods/35390)

Requirement:
[aMidianBorn Book of Silence](https://www.nexusmods.com/skyrim/mods/24909)

Patches:
[kryptopyr's Patch Hub](https://www.nexusmods.com/skyrimspecialedition/mods/19518)
Improved Closefaced Helmets - WACCF & AMB
`imp_helm_legend_WACCF_AMB_Patch.esp`
> Use this patch instead of the WACCF patch.

`imp_helm_legend_WACCF_Patch.esp`

> 
> Once the files above have been installed, deactivate or delete the following plugin (.esp) files if they are present:
> 
>  -   `Glass Variants.esp` or `AMB Glass Variants Lore.esp`
>  -   `Differently Ebony.esp`
>  -   `aMidianborn_Skyforge_Weapons.esp`

```yaml
  - name: 'aMidianBorn_ContentAddon.esp'
    tag:
      - Graphics
      - Invent.Add
      - Keywords
      - Stats
```

---

- [x] Update Location.
- [x] Add message for required resources.
- [x] Add Obsolete message for older versions.
- [x] Add AMB Book of Silence plugins to inc list.
- [x] Update message conditions for Imp Helm & WACCF patch.
- [x] Add bash tag suggestions.
