### ISSUE TITLE
Bash tag suggestions for mods

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1147]
[Weapons Armor Clothing and Clutter Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/18994)
```yaml
  - name: 'Weapons Armor Clothing & Clutter Fixes.esp'
    tag: [ Text ]
```
[Complete Crafting Overhaul Remastered](https://www.nexusmods.com/skyrimspecialedition/mods/28608)
```yaml
  - name: 'Complete Crafting Overhaul_Remastered.esp'
    tag:
      - Graphics
      - Keywords
      - Text
```
[Complete Alchemy and Cooking Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/19924)
```yaml
  - name: 'Complete Alchemy & Cooking Overhaul.esp'
    tag:
      - Keywords
      - Text
```
