### ISSUE TITLE
Cleaning info for Drachenzahn (Wyrmstooth DV)

### ISSUE THREAD

**Issue by minhbi99** [loot/skyrimse#1159]
[Drachenzahn (Wyrmstooth) EV 2.2](https://www.nexusmods.com/skyrimspecialedition/mods/19492)
```yaml
  - name: 'Wyrmstooth.esp'
    dirty:
      - <<: *quickClean
        crc: 0xF73A6161
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 5587
```

[Wyrmstooth 1.17B SSE](https://archive.org/details/Wyrmstooth1.17BSSE)
```yaml
  - name: 'Wyrmstooth.esp'
    clean:
      - crc: 0x97F8C8B4
        util: 'SSEEdit v4.0.3'
```

[Wyrmstooth 1.18 SSE](https://archive.org/details/wyrmstooth1.18SSE)
```yaml
  - name: 'Wyrmstooth.esp'
    clean:
      - crc: 0x85D4BF27
        util: 'SSEEdit v4.0.3'
```

[Drachenzahn DV 3.0](https://www.nexusmods.com/skyrimspecialedition/mods/18553)
```yaml
  - name: 'Wyrmstooth.esp'
    clean:
      - crc: 0xFD63BB73
        util: 'SSEEdit v4.0.3'
```

- [x] Add cleaning info for Drachenzahn (Wyrmstooth).

**Comment by MacSplody** [comment]
[Midwood Isle SE](https://www.nexusmods.com/skyrimspecialedition/mods/28120)
Version 2.62
```yaml
  - name: 'Midwood Isle.esp'
    dirty:
      - <<: *quickClean
        crc: 0x9A607524
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 6921
```

[Midwood Isle SE](https://www.nexusmods.com/skyrimspecialedition/mods/28120)

Version 2.66
```yaml
  - name: 'Midwood Isle.esp'
    clean:
      - crc: 0xC1D1EF6F
        util: 'SSEEdit v4.0.3'
      # No ESM flag
      - crc: 0xF1569674
        util: 'SSEEdit v4.0.3'
```

Version: 2.70
```yaml
  - name: 'Midwood Isle.esp'
    dirty:
      - <<: *quickClean
        crc: 0x35A61832
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 6916
    clean:
      - crc: 0x585A645E
        util: 'SSEEdit v4.0.3'
```

- [ ] Add cleaning info for Midwood Isle.
