### ISSUE TITLE
Cleaning info for Midwood Isle

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1171]
[Midwood Isle SE](https://www.nexusmods.com/skyrimspecialedition/mods/28120)

Version: 2.70
```yaml
  - name: 'Midwood Isle.esp'
    dirty:
      - <<: *quickClean
        crc: 0x35A61832
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 6916
    clean:
      - crc: 0x585A645E
        util: 'SSEEdit v4.0.3'
```

- [x] Add cleaning info for Midwood Isle.

_Originally posted by @minhbi99 in https://github.com/loot/skyrimse/issues/1159
