### ISSUE TITLE
EEKS Immersive Whiterun NAVM wild

### ISSUE THREAD

**Issue by yggdrasil75** [loot/skyrimse#1175]
CB4F3: a navmesh was deleted in Hearthfires.esm but is included in [EEKs Immersive Whiterun](https://www.nexusmods.com/skyrimspecialedition/mods/31214) 
```yaml
  - name: 'EEKs Immersive Whiterun.esp'
    clean:
      - crc: 0x16BF915D
        util: 'SSEEdit v4.0.3'
```
here is the main cleaning report, it isnt dirty itself, it just references dirty records
