### ISSUE TITLE
Oppaikun's Gardens

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1189]
[Oppaikun's Gardens - Garden extension for Hearthfire player homes](https://www.nexusmods.com/skyrimspecialedition/mods/36784)

`Oppaikuns Gardens - Full.esp`
`Oppaikuns Gardens - HH.esp`
`Oppaikuns Gardens - HH + WM.esp`
`Oppaikuns Gardens - LM.esp`
`Oppaikuns Gardens - LM + HH.esp`
`Oppaikuns Gardens - LM + WM.esp`
`Oppaikuns Gardens - WM.esp`

`Oppaikuns Gardens - HH Patch.esp`

> Make sure the mod is loaded after any other mods that alter the player home areas. If the gardens look weird, this is likely the reason.

Mods I've found that alter the same area.

[Enhanced Landscapes](https://www.nexusmods.com/skyrimspecialedition/mods/18162) `Enhanced Landscapes.esp`
[Landscape Fixes For Grass Mods](https://www.nexusmods.com/skyrimspecialedition/mods/9005) `Landscape Fixes For Grass Mods.esp`
[Skyrim Hearthfire Roads](https://www.nexusmods.com/skyrimspecialedition/mods/786) `HearthFires Roads.esp`
[Smooth Shores (Grass and Ground Remastered)](https://www.nexusmods.com/skyrimspecialedition/mods/10624) `SmoothShores.esp`
[THE PEOPLE OF SKYRIM 2](https://www.nexusmods.com/skyrimspecialedition/mods/22392) `tpos_complete02_RTCWG.esp`

Cleaning info

> Undeleting: [REFR:000E2430] (places TreePineForestSnowL05 [TREE:0005D2D7] in GRUP Cell Temporary Children of BYOHHouse2Exterior02 [CELL:00009291] (in Tamriel "Skyrim" [WRLD:0000003C] at -6,24))

```yaml
  - name: 'Oppaikuns Gardens - Full.esp'
    dirty:
      - <<: *quickClean
        crc: 0x8FA44781
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 1
    clean:
      - crc: 0x16798494
        util: 'SSEEdit v4.0.3'
```
