### ISSUE TITLE
Solitude Expansion - Cleaning Info

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1216]
[Solitude Expansion](https://www.nexusmods.com/skyrimspecialedition/mods/8)
Version 2.66

```yaml
  - name: 'Solitude Expansion.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xB547C8EB
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 20
        nav: 13
      - <<: *reqManualFix
        crc: 0xBC5257F4
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 13
```
