### ISSUE TITLE
Multiple Cyclical Interactions with Alternate Start

### ISSUE THREAD

**Issue by Graybark** [loot/skyrimse#122]
Know Your Enemy - Morrowloot Ultimate Patch:
Cyclic interaction detected between "kye_mlu_patch.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Alternate Start LAL TKAA Patch.esp, Immersive Citizens - AI Overhaul.esp, Bells of Skyrim - ICAIO Patch.esp, MLU.esp, kye_mlu_patch.esp

Improved Closedfaced Helmets:
Cyclic interaction detected between "imp_helm_legend.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Alternate Start LAL TKAA Patch.esp, Immersive Citizens - AI Overhaul.esp, Bells of Skyrim - ICAIO Patch.esp, MLU.esp, imp_helm_legend.esp

Improved Closedfaced Helmets - MLU Patch:
Cyclic interaction detected between "MLU - Improved Closefaced Helmets.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Alternate Start LAL TKAA Patch.esp, Immersive Citizens - AI Overhaul.esp, Bells of Skyrim - ICAIO Patch.esp, MLU.esp, imp_helm_legend.esp, MLU - Improved Closefaced Helmets.esp

**Comment by Graybark** [comment]
I have even more of these. This is probably because the group list of MLU patches is incomplete. Currently working on completing it.

**Comment by Graybark** [comment]
The two already added patches are also not tagged as belonging to the group.

**Comment by MacSplody** [comment]
@ArtaiosGreybark These are related to the following issue.
https://github.com/loot/loot-api/issues/22

**Comment by Graybark** [comment]
@CptMcSplody There is still value to adding the rest of the MLU patches, right? I am currently working on them. Here an example:

```
- name: 'MLU - Ars Metallica.esp'
  # MLU - Ars Metallica Patch
    url: 
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/3058/'
        name: 'MorrowLoot Ultimate on Nexus Mods'
    group: *mluGroup
    after:
      - 'Ars Metallica.esp'
      - 'MLU.esp'
    req:
	  - 'Ars Metallica.esp'
          - 'MLU.esp'
    tag:
      - Stats
```

Let me know what you think. The points I would like to have clarified are [1] if masters should also be added to the "after" list and [2] if the groups should be specified for the patches.

From reading loot/loot-api#22, I gather that he is working on a way of resolving the issue without us having to add something like the above. But how would LOOT know what group the plugins are in why should these not be in the MLU group? What is the point of having just one plugin in the group? Thanks!

At least for now they should be added since this prevents LOOT from sorting at all.

Edit: I am only now reading in the documentation that hard masters are not needed in the "req" list, and that the "after" list contains items not in the "req" list. Plugins are already coded to load after hard masters and plugins in the "req" list . The list should be cleaned up a bit, then.

Sorry for the monologue here.
