### ISSUE TITLE
White Phial Better Alignments

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1288]
[White Phial Better Alignments](https://www.nexusmods.com/skyrimspecialedition/mods/5656)

v1.1
```yaml
  - name: 'WhitePhialBetterAlignments.esp'
    clean:
      - crc: 0xB565B1EE
        util: 'SSEEdit v4.0.3'
```

Conflict with [Complete Alchemy and Cooking Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/19924).
![image](https://user-images.githubusercontent.com/1944639/93024116-b9b52e80-f5eb-11ea-8a5f-619c91b3495d.png)

May also conflict with other Alchemy Mods like [SAFO](https://www.nexusmods.com/skyrimspecialedition/mods/12343).

- [x] Add cleaning info.
- [x] Add after for CACO.
