### ISSUE TITLE
Immersive Fort Dawnguard suggested bash tags and cleaning info

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#1290]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/40436

Suggested bash tags: {{BASH:Actors.ACBS,Actors.AIPackages,Actors.Stats,C.Climate,C.Light,Factions,ObjectBounds}}

There are four other patches in the installer, so they may need bash tags too.

Cleaning info:
Version V1

```yaml
  - name: 'fortdawnguardimmersive.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xBF78675F
        util: '[SSEEdit v4.0.3b](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 104
        nav: 10
      - <<: *reqManualFix
        crc: 0x394DCD54
        util: '[SSEEdit v4.0.3b](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 10
```

Ediy: Removed second `dirty:` key, added version.
