### ISSUE TITLE
MorrowLoot Ultimate - Tags

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1413]
[MorrowLoot Ultimate](https://www.nexusmods.com/skyrimspecialedition/mods/3058/)
- [x] `MLU.esp`, `MLU - AAE Ultimate Edition.esp`, `MLU - Immersive Armors.esp`.

There may be some cross over with MLU due to [(SJG) OMEGA - The Modular Gameplay Overhaul for SSE](https://www.nexusmods.com/skyrimspecialedition/mods/17653) and [OMEGA Updated](https://www.nexusmods.com/skyrimspecialedition/mods/33718).

Tags I have for regular Morrowloot Ultimate.

```yaml
  - name: 'MLU.esp'
    tag:
      - Actors.ACBS
      - Actors.AIData
      - Actors.CombatStyle
      - Actors.Spells
      - Actors.Stats
      - EnchantmentStats
      - -Invent
      - Invent.Add
      - Invent.Change
      - Invent.Remove
      - Keywords
      - Outfits.Add
      - Outfits.Remove
```
```yaml
  - name: 'MLU - AAE Ultimate Edition.esp'
    tag:
      - Actors.ACBS
      - Actors.Stats
      - Actors.Spells
      - Invent.Add
      - Invent.Remove
```
_Originally posted by @MacSplody in https://github.com/loot/skyrimse/issue_comments/710707341_
