### ISSUE TITLE
Mainland Stalhrim - Cleaning info

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1428]
[Mainland Stalhrim](https://www.nexusmods.com/skyrimspecialedition/mods/8307)

Version: 1.0

```yaml
  - name: 'MainlandStalhrim.esp'
    dirty:
      - <<: *quickClean
        crc: 0xB78B64CB
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 16
```
