### ISSUE TITLE
Simple Magic Rebalance

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1429]
[Simple Magic Rebalance](https://www.nexusmods.com/skyrimspecialedition/mods/1982)

**Tags**

 - EffectStats, changes actor value, archtype, flags, magic skill, 
 - Keywords, removes keywords from two magic effects.
 - Names, changes names of twelve magic effects.
 - Text, changes descriptions of armors and magic effects.

**Cleaning info**

Version: 1.9b 0xD55C09E9, 1.9b No Perks 0x971ADB2B
```yaml
  - name: 'Simple Magic Rebalance.esp'
    clean:
      - crc: 0xD55C09E9
        util: 'SSEEdit v4.0.3'
      - crc: 0x971ADB2B
        util: 'SSEEdit v4.0.3'
```
