### ISSUE TITLE
Kato's Riverwood - Dirty Plugin

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1487]
[Kato's Riverwood](https://www.nexusmods.com/skyrimspecialedition/mods/7031)

**Cleaning info**
Version 2.0
```yaml
  - name: 'Kato's Riverwood.esp'
    dirty:
      - <<: *quickClean
        crc: 0x3702F743
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 128
        udr: 22
```
