### ISSUE TITLE
The Useless Shop and Interior Overhaul - Dirty Plugin with deleted navmesh

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1505]
[The Useless Shop and Interior Overhaul SE](https://www.nexusmods.com/skyrimspecialedition/mods/21887)
```yaml
  - name: 'iWil_UselessShopOverhaul.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x71EE880F
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
        udr: 2
        nav: 5
      - <<: *reqManualFix
        crc: 0x72B10622
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 5
```

[The Useless Shop and Interior Overhaul SE - Drunken Huntsman Bug Fix](https://www.nexusmods.com/skyrimspecialedition/mods/27406)
```yaml
  - name: 'iWil_UselessShopOverhaul.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x75DC460E
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
        udr: 2
        nav: 3
      - <<: *reqManualFix
        crc: 0x42557944
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 3
```
