### ISSUE TITLE
LOOT Metadata Issue for Relighting Skyrim SSE

### ISSUE THREAD

**Issue by ghost** [loot/skyrimse#1520]
LOOT complains if you have **Relighting Skyrim - SSE** and **Relighting Skyrim SSE - No Player Homes**  with **Improved Hearthfire Lighting**.

> RelightingSkyrim_SSE.esp  
> This plugin is incompatible with "ImprovedHearthfireLighting.esp", but both files are present.

**Comment by MacSplody** [comment]
[Relighting Skyrim SSE - No Player Homes](https://www.nexusmods.com/skyrimspecialedition/mods/26538)
Version 1.0
```yaml
  - name: 'RS_NoPlayerHomes.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA9D66DE5
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 43
```
