### ISSUE TITLE
Relighting Skyrim - No Player Homes

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1521]
###### Cleaning info
Version 1.0
```yaml
  - name: 'RS_NoPlayerHomes.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA9D66DE5
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 43
```

_Originally posted by @MacSplody in https://github.com/loot/skyrimse/issues/1520#issuecomment-725963775_
