### ISSUE TITLE
issue between path of sorcery and ordinator

### ISSUE THREAD

**Issue by ravensm** [loot/skyrimse#1535]
the master list says to load ordinator after path of sorcery, the user metadata says to load path of sorcery after ordinator, since path of sorcery alters the perk tree, the only way to use it is to load it after ordinator, but the master list doesn't allow that. I know I can alter the user metadata, but I am not sure how, even so, i believe the master list should be updated

**Comment by pStyl3** [comment]
[Ordinator - Perks of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/1137)
[Path of Sorcery - Magic Perk Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/6660)

SSE's masterlist contains the following:
```
  - name: 'Ordinator - Perks of Skyrim.esp'
    group: *perksGroup
    after:
      - name: 'PathOfSorcery.esp'
        condition: 'file("Path to Ordinance.esp") or file("Vokriinator.esp") or file("Vokriinator Black.esp")'
```
And:
```
  - name: 'PathOfSorcery.esp'
    after:
      - name: 'Ordinator - Perks of Skyrim.esp'
        condition: 'not file("Path to Ordinance.esp") and not file("Vokriinator.esp") and not file("Vokriinator Black.esp")'
```
Currently these are the [Groups](https://abload.de/img/groups25kdy.png) in the SSE masterlist, with `&perksGroup` being `Skills & Perks`. So `&perksGroup` comes after the `default` Group.

LOOT sorts `Ordinator - Perks of Skyrim.esp` after `PathOfSorcery.esp`, if either `Path to Ordinance.esp` or `Vokriinator.esp` or `Vokriinator Black.esp` is present.

If none of these three plugins are present, then it's reversed and `PathOfSorcery.esp` will be sorted after `Ordinator - Perks of Skyrim.esp`.

So I would guess that you have at least one of those three other plugins in your load order and that's why Ordinator gets sorted behind Path of Sorcery.

On the other hand you speak of existing user metadata. Please provide the content of your `userlist.yaml` which can be found in `C:\Users\USER\AppData\Local\LOOT\Skyrim Special Edition`, so that we can see what that one says.
