### ISSUE TITLE
Sorting error - Sacrilege & Vokrii

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1553]
https://discord.com/channels/473542112974077963/473542230095822848/804862683722809365

> hello, I started getting a "cyclic interaction" error for a load order that sorted fine until a couple hours ago:
> 
> Failed to sort plugins. Details:
> Cyclic interaction detected between "Sacrilege - Minimalistic Vampires of Skyrim.esp" and "CCOR_Vokrii.esp":
> 
> Sacrilege - Minimalistic Vampires of Skyrim.esp
>  [Master]
> YOT - Sacrilege.esp
>  [Group]
> Vokrii - Minimalistic Perks of Skyrim.esp
>  [Master]
> CCOR_Vokrii.esp
>  [Group]
> Sacrilege - Minimalistic Vampires of Skyrim.esp
> 
> hoow do I read this message?
> none of those plugins has any metadata associated

Added in https://github.com/loot/skyrimse/commit/285c767875be308ae0cffeadcc1b1f6ffa34dee5

```yaml
  - name: 'Sacrilege - Minimalistic Vampires of Skyrim.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/42408' ]
    group: *perksGroup
```
The group assignment itself is fine, but not having any afters for other group members can cause this.

**Comment by MacSplody** [comment]
At the moment there are seven files in the Perks group.
I'll have to do some testing to figure out the best solution, as I'm considering splitting the group.

```yaml
  - name: 'Vokrii - Minimalistic Perks of Skyrim.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/26176' ]
    group: *perksGroup
    after:
      - name: 'PathOfSorcery.esp'
        condition: 'file("Vokriinator Black.esp") or file("Vokriinator.esp")'
```

```yaml
  - name: 'Ordinator - Perks of Skyrim.esp'
    url:
      - 'https://www.nexusmods.com/skyrimspecialedition/mods/1137/'
      - 'https://bethesda.net/en/mods/skyrim/mod-detail/2980036'
    group: *perksGroup
    after:
      - name: 'PathOfSorcery.esp'
        condition: 'file("Path to Ordinance.esp") or file("Vokriinator.esp") or file("Vokriinator Black.esp")'
      - 'Phenderix Magic Evolved.esp'
      - 'Phenderix Magic World.esp'
      - 'SAFO.esp'
      - 'Undeath.esp'
      - 'Weapons Armor Clothing & Clutter Fixes.esp'
      - name: 'Vokrii - Minimalistic Perks of Skyrim.esp'
        condition: 'file("Vokriinator.esp") or file("Vokriinator Black.esp")'
```

```yaml
  - name: 'Vokriinator.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/26702' ]
    group: *perksGroup
```

```yaml
  - name: 'Vokriinator Black.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/26702' ]
    group: *perksGroup
    inc: [ 'Vokriinator.esp' ]
```

```yaml
  - name: 'Requiem.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/19281' ]
    group: *perksGroup
```

```yaml
  - name: 'Sacrosanct - Vampires of Skyrim.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/3928' ]
    group: *perksGroup
    inc:
      - 'mslVampiricThirst.esp'
      - 'SanguinairVampirism.esp'
      - 'VampireLordPerksExpanded.esp'
    after:
      - 'Complete Alchemy & Cooking Overhaul.esp'
      - 'DVA - Dynamic Vampire Appearance.esp'
      - 'Ordinator - Perks of Skyrim.esp'
      - 'RaceCompatibilityUSKPOverride.esp'
      - 'Requiem.esp'
      # Group after for Vokrii, to prevent sorting errors
      - 'Vokrii - Minimalistic Perks of Skyrim.esp'
      # Group after for Vokriinator, to prevent sorting errors
      - 'Vokriinator.esp'
      - 'Vokriinator Black.esp'
      - 'Volkihar Knight.esp'
      - 'YOT - Your Own Thoughts.esp'
```

```yaml
  - name: 'Better Vampires.esp'
    url:
      - 'https://www.nexusmods.com/skyrimspecialedition/mods/1925/'
      - 'https://bethesda.net/en/mods/skyrim/mod-detail/3244230'
    group: *perksGroup
    after:
      - 'EBM_UnlimitedPower.esp'
      - 'EBM_UnlimitedPower_Vampire.esp'
      # Group after for Ordinator, to prevent sorting errors
      - 'Ordinator - Perks of Skyrim.esp'
      - 'Requiem.esp'
      - 'Sacrosanct - Vampires of Skyrim.esp'
      - 'Tainted_Blood.esp'
      # Group after for Vokrii, to prevent sorting errors
      - 'Vokrii - Minimalistic Perks of Skyrim.esp'
      - 'Vokriinator.esp'
      - 'Vokriinator Black.esp'
    inc:
      - name: 'Sacrosanct - Vampires of Skyrim.esp'
        condition: 'active("Sacrosanct - Vampires of Skyrim.esp") and not active("Add Sacrosanct Spells to BV.esp") and not active("BVandSacrosanct_Patch.esp")'
```
