### ISSUE TITLE
Books of Skyrim - Cleaning required

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#1555]
### [Books of Skyrim SE](https://www.nexusmods.com/skyrimspecialedition/mods/4115)
Version 1.0
```yaml
  - name: 'BooksOfSkyrim.esp'
    dirty:
      - <<: *quickClean
        crc: 0x74D04D2B
        util: '[SSEEdit v4.0.3f](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
    clean:
      - crc: 0x56127650
        util: 'SSEEdit v4.0.3f'
```

Reverts change made by `Update.esm` for Creation Club plugin Saints & Seducers.
Also conflicts with `SkyrimSewers.esp`.
NAVM `000CAD79` in worldspace SolitudeOrigin `00037EE9`

![image](https://user-images.githubusercontent.com/1944639/106370859-28eead80-6356-11eb-8982-fe0cfcf6f444.png)

- [x] Add wild edit message.
