### ISSUE TITLE
Add useBashTweakInstead message to TDG's Activate To Interact

### ISSUE THREAD

**Issue by sibir-ine** [loot/skyrimse#1589]
This [mod](https://www.nexusmods.com/skyrimspecialedition/mods/35492/) simply changes the value of the game setting `sActivate` from `Activate` to `Interact`. This can now be accomplished with a settings tweak, `Prompt: Activate`, added in the latest nightly, `308.202102111126`.

Since it's still on a nightly, I'm hesitant to add the message until it's on an official release (i.e. on Nexus). For now, I'll leave a code snippet that can be added when the time comes:

```yaml
  - name: 'tdgsseActivateToInteract.esl'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/35492/' ]
    msg:
      - <<: *useBashTweakInstead
        subs: [ 'Tweak Settings -> Prompt: Activate' ]
```

[308](https://github.com/wrye-bash/wrye-bash/commit/f9b5ad2c7331d4f431a07cd8718cdc1da189bac4/) is out, congrats Wrye Bash team!

- [x] Add `tdgsseActivateToInteract.esl`

Done in 72460b5.
