### ISSUE TITLE
ICAIO, AFT/iAFT, & RDO load order

### ISSUE THREAD

**Issue by chrisyowyow** [loot/skyrimse#1612]
So I've noticed [AFT](https://www.nexusmods.com/skyrimspecialedition/mods/6656/)/[iAFT](https://www.nexusmods.com/skyrimspecialedition/mods/14722/) gets pushed very high in LO. Whats happening is, [ICAIO](https://www.nexusmods.com/skyrimspecialedition/mods/173/) is overwriting some of the changes of its functionality so the proper ordering should be ICAIO -> AFT/iAFT -> [RDO](https://www.nexusmods.com/skyrimspecialedition/mods/1187/) -> all patches between the 3

**Comment by sibir-ine** [comment]
> https://www.nexusmods.com/skyrim/mods/65013
https://www.nexusmods.com/skyrim/mods/15524
https://www.nexusmods.com/skyrim/mods/71689
https://www.nexusmods.com/skyrim/mods/74568

Is this for Skyrim LE or Skyrim SE?

**Comment by chrisyowyow** [comment]
SE

**Comment by sibir-ine** [comment]
> 
> 
> SE

Please update the links in both of your issues to point to the SE versions of those mods.

**Comment by chrisyowyow** [comment]
oh damn thanks, i thought i pointed at right 1s lol

**Comment by sibir-ine** [comment]
@chrisyowyow Here's the relevant metadata for the mods in question:
```yaml
  - name: 'Immersive Citizens - AI Overhaul.esp'
    group: *lowPriorityGroup

  - name: 'Relationship Dialogue Overhaul.esp'
    after:
      - 'Immersive Citizens - AI Overhaul.esp'
```
AFT/iAFT are both in the `default` group, which `lowPriorityGroup` loads after, so the typical load order will be AFT/iAFT > ICAIO > RDO. Since all your proposing is to switch the order of AFT/iAFT & ICAIO, it should be noted that they don't conflict in a way that load order can remedy. You can check for yourself with SSEEdit. Therefore, there's no need to swap the order.

Since your other concern is the placement of AFT/iAFT in general, are there any other mods you think they should load after?
