### ISSUE TITLE
Streamline &deletePlugin

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrimse#1623]
The situation with `&deletePlugin` (a message of type `warn`) across the different masterlists is a bit of a mess, and is in dire need of streamlining it, so that every masterlist contains the same version of it.

The original English `en` message:

(1) SSE, Skyrim, FO3
`When using **%1%**. It''s recommended that you deactivate or delete this ESP file, but keep the resources (e.g. meshes, textures) installed with this mod.`

(2) Morrowind, FNV, FO4
`When using **%1%**. It''s recommended that you deactivate or delete this ESP file, but keep the resources (e.g. meshes, textures) installed with this mod. As they''re still required by **%1%**.`

The sentence structure is a bit unorthodox, even more so with the second variant, however it conveys the message. Changing it now would also invalidate the available translations to an extent, so I'd say it's fine as it is. The only question is, which variant should be used from now? I tend to the longer version.

---
The German `de` translation is divided into 4 (!) different versions across the masterlists. The first two variants (3) and (4) belong to English (1), the second two variants (5) and (6) belong to English (2).

(3) SSE, FO3
`Beim Nutzen von **%1%** ist es empfohlen, dass Sie die ESP-Datei deaktivieren oder löschen, aber die mitgelieferten Mittel (z.B Meshes, Texturen) beibehalten die mit dieser Mod mitinstalliert wurden.`

(4) Skyrim
`Beim Nutzen von **%1%** ist es empfohlen, dass Sie die ESP-Datei deaktivieren oder löschen, aber die mitgelieferten Ressourcen (z.B Meshes, Texturen) beibehalten die mit dieser Mod mitinstalliert wurden.`

(5) Morrowind
`Beim nutzen von **%1%** ist es empfohlen das Sie die ESP-Datei deaktivieren oder löschen, aber die mitgelieferten Mittel (z.B Meshes, Texturen) beibehalten die mit dieser Mod mitinstalliert wurden. Diese werden immer noch von **%1%** vorausgesetzt.`

(6) FNV, FO4
`Beim Nutzen von **%1%** ist es empfohlen, dass Sie die ESP-Datei deaktivieren oder löschen, aber die mitgelieferten Mittel (z.B Meshes, Texturen) beibehalten die mit dieser Mod mitinstalliert wurden. Diese werden immer noch von **%1%** vorausgesetzt.`

German (6) is the best, however I'd further tweak it with the change from German (4), so the new and final `de` translation for `&deletePlugin` will become:

(7)
`Beim Nutzen von **%1%** ist es empfohlen, dass Sie die ESP-Datei deaktivieren oder löschen, aber die mitgelieferten Ressourcen (z.B Meshes, Texturen) beibehalten die mit dieser Mod mitinstalliert wurden. Diese werden immer noch von **%1%** vorausgesetzt.`

---

Japanese `ja`, two versions (8) and (9), which belong to English (1) and (2). The longer variant wins.

(8) SSE, Skyrim, FO3
`**%1%**を使用中の場合。このespファイルは無効化あるいは削除するのはおすすめしますが、このmodによってインストールされたリソース(メッシュ、テクスチャなど)はそのままにしておいてください。`

(9) Morrowind, FNV, FO4
`**%1%**を使用中の場合。このespファイルは無効化あるいは削除するのはおすすめしますが、このmodによってインストールされたリソース(メッシュ、テクスチャなど)はそのままにしておいてください。これらは**%1%**によって引き続き必要とされてます。`

---

Korean `ko`, two versions (10) and (11), which belong to English (1) and (2). The longer variant wins.

(10) SSE, Skyrim, FO3
`**%1%** 모드를 사용중일 떈, 이 ESP 파일을 삭제하고 함께 설치된 리소스(예: 메쉬, 텍스쳐)만 남겨두는 걸 권장합니다.`

(11) Morrowind, FNV, FO4
`**%1%** 모드를 사용중일 떈, 이 ESP 파일을 삭제하고 함께 설치된 리소스(예: 메쉬, 텍스쳐)만 남겨두는 걸 권장합니다. 리소스는 **%1%** 모드에서 필요로 합니다.`

---

Polish `pl`, two versions (12) and (13), which belong to English (1) and (2). The longer variant wins.

(12) SSE, Skyrim, FO3
`Używając **%1%**, jest rekomendowane abyś dezaktywował lub usunął ten plik ESP, ale pozostawił zasoby (siatki, tekstury) zainstalowane z tym modem.`

(13) Morrowind, FNV, FO4
`Używając **%1%**, jest rekomendowane abyś dezaktywował lub usunął ten plik ESP, ale pozostawił zasoby (siatki, tekstury) zainstalowane z tym modem. Ponieważ są wciąż wymagane przez **%1%**.`

---

Portuguese `pt`, two versions (14) and (15), which belong to English (1) and (2).

(14) SSE, Skyrim, FO3
`Ao utilizar **%1%**, é recomendado que você desative ou apage este ficheiro ESP, mas mantenha os recursos (ex. meshes, texturas) instalados por este mod.`

(15) Morrowind, FNV, FO4
`Ao utilizar **%1%**, é recomendado que você desative ou apage este ficheiro ESP, mas mantenha os recursos (ex. meshes, texturas) instalados por este mod. Sendo que os mesmos ainda são necessitados por **%1%**. `

An adjusted version of (15) will win, where there is no empty space after the point at the end.

(16)
`Ao utilizar **%1%**, é recomendado que você desative ou apage este ficheiro ESP, mas mantenha os recursos (ex. meshes, texturas) instalados por este mod. Sendo que os mesmos ainda são necessitados por **%1%**.`

---

Brazilian Portuguese `pt_BR`, one existing version (17).

(17) 
`Quando se usa **%1%**, é recomendado que você desative ou delete este arquivo ESP, mas que mantenha os recursos (ex. meshes, texturas) que vieram com esse mod.`

---

Russian `ru`, two versions (18) and (19), which belong to English (1) and (2). The longer variant wins.

(18) SSE, Skyrim, FO3
`Пока используется **%1%**, рекомендуется отключить или удалить esp этого мода, но оставить установленные ресурсы (meshes, textures).`

(19) Morrowind, FNV, FO4
`Пока используется **%1%**, рекомендуется отключить или удалить esp этого мода, но оставить установленные ресурсы (meshes, textures). Т.к. они все еще требуются для **%1%**.`

---

Swedish `sv`, two versions (20) and (21), which belong to English (1) and (2). The longer variant wins.

(20) SSE, Skyrim, FO3
`När du använder **%1%** är det rekommenderat att du avaktiverar eller tar bort denna ESP-fil, men behåll resurserna (meshar och texturer) installerade med denna mod.`

(21) Morrowind, FNV, FO4
`När du använder **%1%** är det rekommenderat att du avaktiverar eller tar bort denna ESP-fil, men behåll resurserna (meshar och texturer) installerade med denna mod. De krävs fortfarande av **%1%**.`

---

As such, the following versions should win:
English (2), German (7), Japanese (9), Korean (11), Polish (13), Portuguese (16), Brazilian Portuguese (17), Russian (19), Swedish (21)

So the final outcome would be:
```yaml
  - &deletePlugin
    type: warn
    content:
      - lang: en
        text: 'When using **%1%**. It''s recommended that you deactivate or delete this ESP file, but keep the resources (e.g. meshes, textures) installed with this mod. As they''re still required by **%1%**.'
      - lang: de
        text: 'Beim Nutzen von **%1%** ist es empfohlen, dass Sie die ESP-Datei deaktivieren oder löschen, aber die mitgelieferten Ressourcen (z.B Meshes, Texturen) beibehalten die mit dieser Mod mitinstalliert wurden. Diese werden immer noch von **%1%** vorausgesetzt.'
      - lang: ja
        text: '**%1%**を使用中の場合。このespファイルは無効化あるいは削除するのはおすすめしますが、このmodによってインストールされたリソース(メッシュ、テクスチャなど)はそのままにしておいてください。これらは**%1%**によって引き続き必要とされてます。'
      - lang: ko
        text: '**%1%** 모드를 사용중일 떈, 이 ESP 파일을 삭제하고 함께 설치된 리소스(예: 메쉬, 텍스쳐)만 남겨두는 걸 권장합니다. 리소스는 **%1%** 모드에서 필요로 합니다.'
      - lang: pl
        text: 'Używając **%1%**, jest rekomendowane abyś dezaktywował lub usunął ten plik ESP, ale pozostawił zasoby (siatki, tekstury) zainstalowane z tym modem. Ponieważ są wciąż wymagane przez **%1%**.'
      - lang: pt
        text: 'Ao utilizar **%1%**, é recomendado que você desative ou apage este ficheiro ESP, mas mantenha os recursos (ex. meshes, texturas) instalados por este mod. Sendo que os mesmos ainda são necessitados por **%1%**.'
      - lang: pt_BR
        text: 'Quando se usa **%1%**, é recomendado que você desative ou delete este arquivo ESP, mas que mantenha os recursos (ex. meshes, texturas) que vieram com esse mod.'
      - lang: ru
        text: 'Пока используется **%1%**, рекомендуется отключить или удалить esp этого мода, но оставить установленные ресурсы (meshes, textures). Т.к. они все еще требуются для **%1%**.'
      - lang: sv
        text: 'När du använder **%1%** är det rekommenderat att du avaktiverar eller tar bort denna ESP-fil, men behåll resurserna (meshar och texturer) installerade med denna mod. De krävs fortfarande av **%1%**.'
```

**Comment by sibir-ine** [comment]
The alias was originally shortened in #1306 as, in #1283, I used a modified version of the original message without the last segment fragment as it was inaccurate for the context. @MacSplody later decided to modify the alias as well since it'd make it more versatile. We also agreed that since most of the translations followed the same pattern with the sentence fragment at the end, they could probably be safely trimmed as well. It may be appropriate to see if some translators would be willing to double check them just in case.

I say we keep the trimmed version of the alias & propagate it to the other lists, but make it something like `When using **%1%**, it''s recommended that you deactivate or delete this ESP file but keep the resources (e.g. meshes, textures) installed with this mod.` to address the strange grammar.

**Comment by pStyl3** [comment]
If the message was trimmed for your mentioned use case, than we should of course use that one. And your slight modification to the `en` message seems doable just like that, as well. The german translation is already leaning towards your adjusted version.

As such, these translations should be used:
German (4), Japanese (8), Korean (10), Polish (12), Portuguese (14), Brazilian Portuguese (17), Russian (18), Swedish (20)

Result:
```yaml
  - &deletePlugin
    type: warn
    content:
      - lang: en
        text: 'When using **%1%**, it''s recommended that you deactivate or delete this ESP file but keep the resources (e.g. meshes, textures) installed with this mod.'
      - lang: de
        text: 'Beim Nutzen von **%1%** ist es empfohlen, dass Sie die ESP-Datei deaktivieren oder löschen, aber die mitgelieferten Ressourcen (z.B Meshes, Texturen) beibehalten die mit dieser Mod mitinstalliert wurden.'
      - lang: ja
        text: '**%1%**を使用中の場合。このespファイルは無効化あるいは削除するのはおすすめしますが、このmodによってインストールされたリソース(メッシュ、テクスチャなど)はそのままにしておいてください。'
      - lang: ko
        text: '**%1%** 모드를 사용중일 떈, 이 ESP 파일을 삭제하고 함께 설치된 리소스(예: 메쉬, 텍스쳐)만 남겨두는 걸 권장합니다.'
      - lang: pl
        text: 'Używając **%1%**, jest rekomendowane abyś dezaktywował lub usunął ten plik ESP, ale pozostawił zasoby (siatki, tekstury) zainstalowane z tym modem.'
      - lang: pt
        text: 'Ao utilizar **%1%**, é recomendado que você desative ou apage este ficheiro ESP, mas mantenha os recursos (ex. meshes, texturas) instalados por este mod.'
      - lang: pt_BR
        text: 'Quando se usa **%1%**, é recomendado que você desative ou delete este arquivo ESP, mas que mantenha os recursos (ex. meshes, texturas) que vieram com esse mod.'
      - lang: ru
        text: 'Пока используется **%1%**, рекомендуется отключить или удалить esp этого мода, но оставить установленные ресурсы (meshes, textures).'
      - lang: sv
        text: 'När du använder **%1%** är det rekommenderat att du avaktiverar eller tar bort denna ESP-fil, men behåll resurserna (meshar och texturer) installerade med denna mod.'
```

The following masterlists needs to be updated to reflect these changes to `&deletePlugin`:
- [x] SSE
- [x] Skyrim
- [x] Morrowind
- [x] Fallout 3
- [x] Fallout 4
- [x] Fallout NV
