### ISSUE TITLE
Streamline &obsolete

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrimse#1626]
English `en`

SSE, Skyrim, FO4
`Obsolete. Update to latest version. %1%`

Oblivion, Morrowind, FNV, FO3
`Obsolete. Update to the latest version. %1%`

---

German `de`

SSE, Oblivion, FNV, FO3, FO4
`Veraltet. Aktualisiere zur letzten Version. %1%`

Skyrim
`Veraltet. Aktualisieren Sie zur neusten Version. %1%`

Morrowind
`Veraltet. Aktualisere zur letzten Version. %1%`

---

Korean `ko`

SSE, Skyrim, FO3
`폐기된 플러그인입니다. 최신 버전으로 업데이트하십시오. %1%`

Oblivion, Morrowind, FNV, FO4
`사용되지 않습니다. 최신 버전으로 업데이트하십시오. %1%`

---

We should streamline `&obsolete` so that every masterlist uses the same versions. Regarding the `en` message, I don't really mind either way, though google search lists more results for `"Update to the latest version."` than for `"Update to latest version."`, making the first one a term generaly used more often.

For German I'd strongly prefer the version from Skyrim's masterlist.
For Korean, the result that google translate produces for the version of SSE & Co (`This is a deprecated plugin. Please update to the latest version. %1% `) seems more fitting than the one version from Oblivion & Co (`Not used. Please update to the latest version. %1%`) - of course though, this is only what google translate says ..

That would give us the following result:
```yaml
  - &obsolete
    type: warn
    content:
      - lang: en
        text: 'Obsolete. Update to the latest version. %1%'
      - lang: da
        text: 'Forældet. Opdatér til den nyeste version. %1%'
      - lang: de
        text: 'Veraltet. Aktualisieren Sie zur neusten Version. %1%'
      - lang: es
        text: 'Obsoleto. Actualizar a la última versión. %1%'
      - lang: ja
        text: '旧式のプラグインです。最新版に更新してください。 %1%'
      - lang: ko
        text: '폐기된 플러그인입니다. 최신 버전으로 업데이트하십시오. %1%'
      - lang: pl
        text: 'Przestarzały. Uaktualnij do ostatniej wersji. %1%'
      - lang: ru
        text: 'Устарело. Обновите до последней версии. %1%'
      - lang: sv
        text: 'Utdaterad. Uppdatera till den senaste versionen. %1%'
      - lang: zh_CN
        text: '已过时。请升级到最新版本。 %1%'
```
Every masterlist besides `Enderal` needs to be updated.
