### ISSUE TITLE
Inline single entry lists

### ISSUE THREAD

**Issue by sibir-ine** [loot/skyrimse#1640]
I've noticed that throughout most of the masterlists, there are quite a few lists that have only one entry that isn't inline. Here's an example from the SSE masterlist:

```yaml
  - name: 'InnoLostAlt.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/24236' ]
    after:
      - 'TheChoiceIsYours.esp'
    clean:
      - crc: 0x7D8AB5D7
        util: 'SSEEdit v4.0.3'
```

The `after` can be rewritten as:

```yaml
    after: [ 'TheChoiceIsYours.esp' ]
```

It's not a big deal, but it's definitely tidier that way; it's also done in most masterlists most of the time where applicable, so it's also worth doing for the sake of consistency.

@MacSplody did a lot of work towards this goal for the SSE masterlist in #978, the TES5 masterlist in loot/skyrim#311, & the TES4 masterlist in loot/oblivion#94 & loot/oblivion#72.

At the time of writing, I found 1 instance in the TES3 masterlist, 1 instance in the TES4 masterlist, 4 instances in the SSE masterlist, 18 instances in the TES5 masterlist, 73 instances in the FO4 masterlists, & about 493(!) instances in the FNV masterlist.

I found this out by searching the masterlists with a regex, specifically `: *\n {3,}-.*\n {2,4}(?! )`, to find every occurrence, taking advantage of the expected indentation of such an entry & how it will be preceded by a colon & newline & followed by a less indented line. I also tried to factor in erroneous spaces & indentation (it still caught a few false positives from bad indentation). Any improvements to the regex are very welcome.

- [x] TES3 inline lists -> loot/morrowind@dd7a06c
- [x] TES4 inline lists -> loot/oblivion@dbd40f1
- [x] TES5 inline lists -> loot/skyrim@59037b1
- [x] SSE inline lists -> 405071e
- [x] FNV inline lists -> loot/falloutnv@dbd09a8
- [x] FO4 inline lists -> loot/fallout4@83e749e
