### ISSUE TITLE
Scrambled Bugs

### ISSUE THREAD

**Issue by sibir-ine** [loot/skyrimse#1723]
[Link](https://www.nexusmods.com/skyrimspecialedition/mods/43532/)

- [x] Add ~~`*deletePlugin`~~ `*useVersion` to `WM Flora Fixes.esp`
- [x] Create `&alreadyInOrFixedByScrambledBugs` message anchor
- [x] Add `*alreadyInOrFixedByScrambledBugs` to `FloraRespawnFix.esp`
- [x] Add `*alreadyInOrFixedByScrambledBugs` to `Lafreakshow_AutoEquipAmmo.esp`
- [x] Add `*alreadyInOrFixedByScrambledBugs` to `Pick Best Arrow.esp`
- [x] Add `*alreadyInOrFixedByScrambledBugs` to `wolfs_LockpickingXPFix.esp`
- [x] Add `*moddingPlugin` to `ApplySpellPerkEntryPointsDemonstration.esp`
- [x] Add `*useBashTweakInstead` to `SoulGemTooSmall.esp` (after next stable release of WB)

For use later:
```yaml
  - name: 'SoulGemTooSmall.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/43532/' ]
    msg:
      - <<: *useBashTweakInstead
        subs: [ 'Tweak Settings -> Msg: No Soul Gem Large Enough' ]
```
