### ISSUE TITLE
Cleaning info w/links all from Nexus

### ISSUE THREAD

**Issue by cecell** [loot/skyrimse#1771]
<details><summary>Cleaning reports</summary>

```yaml
  - name: 'TimberSprings.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/43743' ]
    dirty:
      - <<: *reqManualFix
        crc: 0x07674A3F
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 173
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0xCBFBBC4F
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'Milos Hot Springs.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/17144' ]
    dirty:
      - <<: *quickClean
        crc: 0x68A34A5D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 12
    clean:
      - crc: 0x0AE54DF3
        util: 'SSEEdit v4.0.3'

  - name: 'SurSummerAssault - Stormcloak.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/42715' ]
    dirty:
      - <<: *reqManualFix
        crc: 0x5722E46A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 34
        udr: 5
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0xC61AFBDA
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'TownOfPinewatch.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/15735' ]
    dirty:
      - <<: *reqManualFix
        crc: 0x8C77CBC4
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 28
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0x0BE962F8
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'The Windhelm Smelter.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/46333' ]
    dirty:
      - <<: *reqManualFix
        crc: 0xED966101
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 30
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0x71698916
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'Fachry Brothel Riften.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/23763' ]
    dirty:
      - <<: *quickClean
        crc: 0x163A3B3F
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 9
    clean:
      - crc: 0x7356D24E
        util: 'SSEEdit v4.0.3'

  - name: 'Valen_assault.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/48349' ]
    dirty:
      - <<: *quickClean
        crc: 0x54ABB1A6
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 430
    clean:
      - crc: 0x5BE9C813
        util: 'SSEEdit v4.0.3'

  - name: 'GrayQuarter959.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/42234' ]
    dirty:
      - <<: *quickClean
        crc: 0x07282553
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 27
    clean:
      - crc: 0x1D2DA3F0
        util: 'SSEEdit v4.0.3'

  - name: 'Overstead.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/9323' ]
    dirty:
      - <<: *reqManualFix
        crc: 0x0DF870FF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 41
        udr: 1
        nav: 2
    dirty:
      - <<: *reqManualFix
        crc: 0xC7A3E3AF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 2

  - name: 'NorthernTowns.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/12915' ]
    dirty:
      - <<: *quickClean
        crc: 0x538D8CF1
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 11
    clean:
      - crc: 0xB88F78B7
        util: 'SSEEdit v4.0.3'

  - name: 'NarrativeLoot Complete.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/12812' ]
    dirty:
      - <<: *quickClean
        crc: 0x19851963
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 21
    clean:
      - crc: 0x559E3283
        util: 'SSEEdit v4.0.3'

  - name: 'MoreColorfulCritters.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/32691' ]
    dirty:
      - <<: *quickClean
        crc: 0xFA2086F3
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xDC9649AB
        util: 'SSEEdit v4.0.3'

  - name: 'MoreBanditEncampmentsFALK.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/13270' ]
    dirty:
      - <<: *reqManualFix
        crc: 0xD7C12C8C
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 372
        nav: 27
    dirty:
      - <<: *reqManualFix
        crc: 0x19142779
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 27

  - name: 'MistySkye.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/16374' ]
    dirty:
      - <<: *quickClean
        crc: 0xD8D5FF3A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 10
    clean:
      - crc: 0x4F094672
        util: 'SSEEdit v4.0.3'

  - name: 'Milante.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/26234' ]
    dirty:
      - <<: *quickClean
        crc: 0xFAACAD86
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 10
    clean:
      - crc: 0x1B2FE829
        util: 'SSEEdit v4.0.3'

  - name: 'MFRY Litany of Larceny 3.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/22651' ]
    dirty:
      - <<: *quickClean
        crc: 0x3EC0D818
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x4D8C1593
        util: 'SSEEdit v4.0.3'

  - name: 'LiamsConjurationSpells.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/29873' ]
    dirty:
      - <<: *quickClean
        crc: 0xF1C8C6EF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xC555195C
        util: 'SSEEdit v4.0.3'

  - name: 'Luminosity Lighting Overhaul.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/16830' ]
    dirty:
      - <<: *quickClean
        crc: 0x6C8E06F9
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xB3F5E795
        util: 'SSEEdit v4.0.3'

  - name: 'LvxMagicksFactionBooks-Morebooks Please2.5.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/10810' ]
    dirty:
      - <<: *quickClean
        crc: 0x54A05022
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x2BCD5BFD
        util: 'SSEEdit v4.0.3'

  - name: 'Magelight Multi Cast.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/29380' ]
    dirty:
      - <<: *quickClean
        crc: 0x28295F59
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xF222E169
        util: 'SSEEdit v4.0.3'

  - name: 'Kinky Inn.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/28917' ]
    dirty:
      - <<: *reqManualFix
        crc: 0x2627D9E9
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'Ish's Souls to Perks.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/1955' ]
    dirty:
      - <<: *quickClean
        crc: 0x801BF769
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x3D429C9B
        util: 'SSEEdit v4.0.3'

  - name: 'HopesabandonSSE 1.1.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/13870' ]
    dirty:
      - <<: *quickClean
        crc: 0xB887D331
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 12
    clean:
      - crc: 0x33FD45DC
        util: 'SSEEdit v4.0.3'

  - name: 'GuardsArmorsAndWeapons.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/19259' ]
    dirty:
      - <<: *quickClean
        crc: 0xD435392D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 26
    clean:
      - crc: 0x4A24B119
        util: 'SSEEdit v4.0.3'

  - name: 'Gavrostead.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/6794' ]
    dirty:
      - <<: *quickClean
        crc: 0x2A020CC8
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 12
    clean:
      - crc: 0x242F0F9D
        util: 'SSEEdit v4.0.3'

  - name: 'FactionSpy.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/17819' ]
    dirty:
      - <<: *quickClean
        crc: 0xC80E08EA
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x45D53EEF
        util: 'SSEEdit v4.0.3'

  - name: 'DragonbridgeSouthSide.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/13444' ]
    dirty:
      - <<: *quickClean
        crc: 0xC088ADAE
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x3986CE59
        util: 'SSEEdit v4.0.3'

  - name: 'Crime Overhaul.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/19647' ]
    dirty:
      - <<: *quickClean
        crc: 0x73901DF5
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x1B3801E9
        util: 'SSEEdit v4.0.3'

  - name: 'Darkspell01.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/30687' ]
    dirty:
      - <<: *quickClean
        crc: 0xABB2FA03
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x5B5DEC8E
        util: 'SSEEdit v4.0.3'

  - name: 'Chanterelle World Interiors.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/41965' ]
    dirty:
      - <<: *reqManualFix
        crc: 0xB5E2C59A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 3

  - name: 'Citizens Visual Overhaul.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/44563' ]
    dirty:
      - <<: *quickClean
        crc: 0x02F77946
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 7
    clean:
      - crc: 0x2955B05C
        util: 'SSEEdit v4.0.3'

  - name: 'Astral.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/37992' ]
    dirty:
      - <<: *quickClean
        crc: 0x3A8D55BA
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 6
    clean:
      - crc: 0x77DB3824
        util: 'SSEEdit v4.0.3'

  - name: '3BBB.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/30174' ]
    dirty:
      - <<: *quickClean
        crc: 0x8320E3CC
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x8C29C91B
        util: 'SSEEdit v4.0.3'

  - name: 'Whistling City Ruins.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/30766' ]
    dirty:
      - <<: *quickClean
        crc: 0x32C772B9
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 97
    dirty:
      - <<: *quickClean
        crc: 0x1692FF07
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xFE1A1960
        util: 'SSEEdit v4.0.3'
```

</details>

**Comment by sibir-ine** [comment]
@cecell Can you please also make a note of the version number of each mod you cleaned?

**Comment by cecell** [comment]
https://discord.com/channels/473542112974077963/496196499890241546/823653095484424282

<img width="885" height="420" alt="Image" src="https://github.com/user-attachments/assets/1fe31706-1c42-4598-b0e5-0896ab436bac" />

**Comment by cecell** [comment]
It is difficult for me to type due to a recent injury I would appreciate it if you would except it.  I'm having to take advantage of speech to text at the moment if you can't accept it like this then I'll just half to do it later

**Comment by cecell** [comment]
> @cecell Can you please also make a note of the version number of each mod you cleaned?

Sigh...I'll do it tomorrow I'm going to bed

**Comment by sibir-ine** [comment]
@cecell It's not a big deal. I don't know when we'll get around to adding these (I have my hands full ATM), so you can take your time.

**Comment by cecell** [comment]
```
  - name: 'TimberSprings.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/43743' ]
    dirty:
      # version: 0.20
      - <<: *reqManualFix
        crc: 0x07674A3F
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 173
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0xCBFBBC4F
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'Milos Hot Springs.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/17144' ]
    dirty:
      # version: 1.10
      - <<: *quickClean
        crc: 0x68A34A5D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 12
    clean:
      - crc: 0x0AE54DF3
        util: 'SSEEdit v4.0.3'

  - name: 'SurSummerAssault - Stormcloak.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/42715' ]
    dirty:
      # version: 0.80
      - <<: *reqManualFix
        crc: 0x5722E46A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 34
        udr: 5
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0xC61AFBDA
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'TownOfPinewatch.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/15735' ]
    dirty:
      # version: 0.92
      - <<: *reqManualFix
        crc: 0x8C77CBC4
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 28
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0x0BE962F8
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'The Windhelm Smelter.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/46333' ]
    dirty:
      # version: 2.0
      - <<: *reqManualFix
        crc: 0xED966101
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 30
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0x71698916
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'Fachry Brothel Riften.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/23763' ]
    dirty:
      # version: 1.30
      - <<: *quickClean
        crc: 0x163A3B3F
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 9
    clean:
      - crc: 0x7356D24E
        util: 'SSEEdit v4.0.3'

  - name: 'Valen_assault.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/48349' ]
    dirty:
      # version: 0.40
      - <<: *quickClean
        crc: 0x54ABB1A6
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 430
    clean:
      - crc: 0x5BE9C813
        util: 'SSEEdit v4.0.3'

  - name: 'GrayQuarter959.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/42234' ]
    dirty:
      # version: 1.2a
      - <<: *quickClean
        crc: 0x07282553
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 27
    clean:
      - crc: 0x1D2DA3F0
        util: 'SSEEdit v4.0.3'

  - name: 'Overstead.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/9323' ]
    dirty:
      # version: 1.0
      - <<: *reqManualFix
        crc: 0x0DF870FF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 41
        udr: 1
        nav: 2
    dirty:
      - <<: *reqManualFix
        crc: 0xC7A3E3AF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 2

  - name: 'NorthernTowns.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/12915' ]
    dirty:
      # version: 3.0
      - <<: *quickClean
        crc: 0x538D8CF1
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 11
    clean:
      - crc: 0xB88F78B7
        util: 'SSEEdit v4.0.3'

  - name: 'NarrativeLoot Complete.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/12812' ]
    dirty:
      # version: 2.0
      - <<: *quickClean
        crc: 0x19851963
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 21
    clean:
      - crc: 0x559E3283
        util: 'SSEEdit v4.0.3'

  - name: 'MoreColorfulCritters.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/32691' ]
    dirty:
      # version: 3.10
      - <<: *quickClean
        crc: 0xFA2086F3
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xDC9649AB
        util: 'SSEEdit v4.0.3'

  - name: 'MoreBanditEncampmentsFALK.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/13270' ]
    dirty:
      # version: 1.10
      - <<: *reqManualFix
        crc: 0xD7C12C8C
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 372
        nav: 27
    dirty:
      - <<: *reqManualFix
        crc: 0x19142779
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 27

  - name: 'MistySkye.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/16374' ]
    dirty:
      # version: 6.10
      - <<: *quickClean
        crc: 0xD8D5FF3A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 10
    clean:
      - crc: 0x4F094672
        util: 'SSEEdit v4.0.3'

  - name: 'Milante.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/26234' ]
    dirty:
      # version: 1.3.2
      - <<: *quickClean
        crc: 0xFAACAD86
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 10
    clean:
      - crc: 0x1B2FE829
        util: 'SSEEdit v4.0.3'

  - name: 'MFRY Litany of Larceny 3.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/22651' ]
    dirty:
      # version: 3.0
      - <<: *quickClean
        crc: 0x3EC0D818
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x4D8C1593
        util: 'SSEEdit v4.0.3'

  - name: 'LiamsConjurationSpells.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/29873' ]
    dirty:
      # version: 1.0
      - <<: *quickClean
        crc: 0xF1C8C6EF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xC555195C
        util: 'SSEEdit v4.0.3'

  - name: 'Luminosity Lighting Overhaul.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/16830' ]
    dirty:
      # version: 4.1
      - <<: *quickClean
        crc: 0x6C8E06F9
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xB3F5E795
        util: 'SSEEdit v4.0.3'

  - name: 'LvxMagicksFactionBooks-Morebooks Please2.5.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/10810' ]
    dirty:
      # version: 3.0
      - <<: *quickClean
        crc: 0x54A05022
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x2BCD5BFD
        util: 'SSEEdit v4.0.3'

  - name: 'Magelight Multi Cast.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/29380' ]
    dirty:
      # version: 1.0
      - <<: *quickClean
        crc: 0x28295F59
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xF222E169
        util: 'SSEEdit v4.0.3'

  - name: 'Kinky Inn.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/28917' ]
    dirty:
      # version: 2.20
      - <<: *reqManualFix
        crc: 0x2627D9E9
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'Ish's Souls to Perks.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/1955' ]
    dirty:
      # version: 1.20
      - <<: *quickClean
        crc: 0x801BF769
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x3D429C9B
        util: 'SSEEdit v4.0.3'

  - name: 'HopesabandonSSE 1.1.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/13870' ]
    dirty:
      # version: 1.20
      - <<: *quickClean
        crc: 0xB887D331
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 12
    clean:
      - crc: 0x33FD45DC
        util: 'SSEEdit v4.0.3'

  - name: 'GuardsArmorsAndWeapons.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/19259' ]
    dirty:
      # version: 1.0
      - <<: *quickClean
        crc: 0xD435392D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 26
    clean:
      - crc: 0x4A24B119
        util: 'SSEEdit v4.0.3'

  - name: 'Gavrostead.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/6794' ]
    dirty:
      # version: 1.10
      - <<: *quickClean
        crc: 0x2A020CC8
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 12
    clean:
      - crc: 0x242F0F9D
        util: 'SSEEdit v4.0.3'

  - name: 'FactionSpy.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/17819' ]
    dirty:
      # version: 1.10
      - <<: *quickClean
        crc: 0xC80E08EA
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x45D53EEF
        util: 'SSEEdit v4.0.3'

  - name: 'DragonbridgeSouthSide.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/13444' ]
    dirty:
      # version: 1.40
      - <<: *quickClean
        crc: 0xC088ADAE
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x3986CE59
        util: 'SSEEdit v4.0.3'

  - name: 'Crime Overhaul.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/19647' ]
    dirty:
      # version: 2.05a
      - <<: *quickClean
        crc: 0x73901DF5
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x1B3801E9
        util: 'SSEEdit v4.0.3'

  - name: 'Darkspell01.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/30687' ]
    dirty:
      # version: 1.00
      - <<: *quickClean
        crc: 0xABB2FA03
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x5B5DEC8E
        util: 'SSEEdit v4.0.3'

  - name: 'Chanterelle World Interiors.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/41965' ]
    dirty:
      # version: 1.0.6
      - <<: *reqManualFix
        crc: 0xB5E2C59A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 3

  - name: 'Citizens Visual Overhaul.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/44563' ]
    dirty:
      # version: 1.0
      - <<: *quickClean
        crc: 0x02F77946
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 7
    clean:
      - crc: 0x2955B05C
        util: 'SSEEdit v4.0.3'

  - name: 'Astral.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/37992' ]
    dirty:
      # version: 1.12
      - <<: *quickClean
        crc: 0x3A8D55BA
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 6
    clean:
      - crc: 0x77DB3824
        util: 'SSEEdit v4.0.3'

  - name: '3BBB.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/30174' ]
    dirty:
      # version: 2.06
      - <<: *quickClean
        crc: 0x8320E3CC
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x8C29C91B
        util: 'SSEEdit v4.0.3'

  - name: 'Whistling City Ruins.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/30766' ]
    dirty:
      # version: 1.0
      - <<: *quickClean
        crc: 0x32C772B9
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 97
    dirty:
      - <<: *quickClean
        crc: 0x1692FF07
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xFE1A1960
        util: 'SSEEdit v4.0.3'
```
