### ISSUE TITLE
Couple more dirty mods...

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/skyrimse#1900]
LOOT Masterlist Entries

```yaml
  - name: 'ChillrendNote.esl'
    dirty:
      - <<: *quickClean
        crc: 0xE771ACEB
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x3E60422C
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/34657
Version 1.1 esl

LOOT Masterlist Entries

```yaml
  - name: 'SnowBall.esp'
    dirty:
      - <<: *quickClean
        crc: 0xF25CB13C
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 6
    clean:
      - crc: 0x9A3724D0
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/51006
Version 1.4.1

LOOT Masterlist Entries

```yaml
  - name: 'Sanctuary Reborn.esp'
    dirty:
      - <<: *quickClean
        crc: 0xDEB7C3C4
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xA81AA17E
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/22070
Version 1.0.7

LOOT Masterlist Entries

```yaml
  - name: 'ShadyMerchants.esl'
    dirty:
      - <<: *quickClean
        crc: 0xF02E79B3
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x3D7898D5
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/17940
Version 1.0

LOOT Masterlist Entries

```yaml
  - name: 'BetterCitiesWhiterun.esp'
    dirty:
      - <<: *quickClean
        crc: 0x4BEB56A4
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 27
        udr: 92
    clean:
      - crc: 0xC04D987A
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/3847 (Whiterun variant)
Version 1.1

LOOT Masterlist Entries

```yaml
  - name: 'Better Cities Solitude.esp'
    dirty:
      - <<: *quickClean
        crc: 0xC112DD5C
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 16
    clean:
      - crc: 0x3D0D0A6E
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/3847 (Solitude variant)
Version 1.41

LOOT Masterlist Entries

```yaml
  - name: 'Solitude Expansion.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x249FA46C
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 31
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/8?tab=posts
or rather taken from here: https://drive.google.com/u/1/uc?id=1ndAlNoBJaTHmDOF-LpYCukfhJdAEmPbs&export=download (fixes missing navmeshes)
Have no idea what version it is, works fine anyway you put it, navmeshes though may be not aligned with ground in certain places but at least not missing... possibly it is best to not clean it at all idk

**Comment by IllusiveMan196** [comment]
And some more:

LOOT Masterlist Entries
```yaml
  - name: 'SMMerchantCamp.esl'
    dirty:
      - <<: *quickClean
        crc: 0xD6E8CE35
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x97375DF7
        util: 'SSEEdit v4.0.3
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/26042
Version 1.1


LOOT Masterlist Entries

```yaml
  - name: 'ancient weathertop.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x6C28BE22
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 4
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/42065
Version 1.0


LOOT Masterlist Entries

```yaml
  - name: 'Moonpath Navmesh Fix.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xF6CAAE30
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 31
        udr: 12
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0x02E02099
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/25714
Version 2.0
Not really sure as to this mod, because it is supposed to fix/overhaul/remake "very bad" Moonpath to Elsweyr's navmeshes, item ownership flags and some more


LOOT Masterlist Entries

```yaml
  - name: 'Leek_Giant.esp'
    dirty:
      - <<: *quickClean
        crc: 0x704F38BC
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 26
        udr: 14
    clean:
      - crc: 0xC790F24D
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/43960
Version 1.4.1 (full 30 leeks)


LOOT Masterlist Entries

```yaml
  - name: 'chickenleg.esp'
    dirty:
      - <<: *quickClean
        crc: 0xDD534CE0
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
        udr: 1
    clean:
      - crc: 0x8475D752
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/29339
Version 1.0

**Comment by IllusiveMan196** [comment]
LOOT Masterlist Entries

```yaml
  - name: 'SkoomDealersDen.esp'
    dirty:
      - <<: *quickClean
        crc: 0x9FC50651
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
        udr: 37
    clean:
      - crc: 0x82480954
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/25081
Version 1.4k (skooma dealer's den addon mod)


LOOT Masterlist Entries

```yaml
  - name: 'Portals of Skyrim.esp'
    dirty:
      - <<: *quickClean
        crc: 0x1B8AE5D9
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 8
        udr: 6
    clean:
      - crc: 0x035DBA03
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/44519
Version 1.0 (Vanilla edition non esl)


LOOT Masterlist Entries

```yaml
  - name: 'Glamoril.esp'
    dirty:
      - <<: *quickClean
        crc: 0xED78173A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 10
        udr: 1
    clean:
      - crc: 0x93612478
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/43477
Version 1.3.4


LOOT Masterlist Entries

```yaml
  - name: 'TheOneRing.esp'
    dirty:
      - <<: *quickClean
        crc: 0xECD2F4A3
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x39D90AB5
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/20167
Version 1
Have no idea where there may be ITMs honestly... it's just a ring on High Hrotgar and that's it


LOOT Masterlist Entries

```yaml
  - name: 'Pussycats.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x0B465805
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/28852
Version 1.0.2 (quest, custom CBBE)


LOOT Masterlist Entries

```yaml
  - name: 'Shani the Grey - Khajiit Follower.esp'
    dirty:
      - <<: *quickClean
        crc: 0x80A3764F
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 16
    clean:
      - crc: 0x991B9FBE
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/26935
Version 1.1 (UNP variant)


LOOT Masterlist Entries

```yaml
  - name: 'Sorceress Supreme.esp'
    dirty:
      - <<: *quickClean
        crc: 0xEC0E6EA3
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 18
    clean:
      - crc: 0xAAE391CF
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/39913
Version 1.2.2

**Comment by IllusiveMan196** [comment]
LOOT Masterlist Entries

```yaml
  - name: 'The Infinity Gauntlet.esp'
    dirty:
      - <<: *quickClean
        crc: 0xC875BB6D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 16
    clean:
      - crc: 0xBEDB4EB0
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/25556
Version 10


LOOT Masterlist Entries

```yaml
  - name: 'silvercraft.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA215AFEE
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xA6A7A48A
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/9450
Version 1.0


LOOT Masterlist Entries

```yaml
  - name: 'mihaildwarvenpowerarmor.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA542594A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 8
    clean:
      - crc: 0x3B731847
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/30317
Version 2


LOOT Masterlist Entries

```yaml
  - name: 'Remodeled Armor - Vanilla Replacer.esp'
    dirty:
      - <<: *quickClean
        crc: 0x24A898B8
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0xE5AC5136
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/22168
Version 1.2.1 (Main modfile from archive)

**Comment by IllusiveMan196** [comment]
LOOT Masterlist Entries

```yaml
  - name: 'Black Thief.esp'
    dirty:
      - <<: *quickClean
        crc: 0xB7952B91
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x1AA55279
        util: 'SSEEdit v4.0.3'
```

Link: https://www.nexusmods.com/skyrimspecialedition/mods/48252
Version 1.1
