### ISSUE TITLE
posting SSEdit status not in master day later?

### ISSUE THREAD

**Issue by Dreifels** [loot/skyrimse#1908]
https://www.afkmods.com/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/page/35/
lot of enries but new masterlist does not contain any

```yaml
  - name: 'Gildergreen Regrown.esp'
    clean:
      - crc: 0x7AA5675A
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Grass Field.esp'
    clean:
      - crc: 0xC2AE41DB
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Lanterns Of Skyrim - All In One - Main.esm'
    clean:
      - crc: 0x26758EF2
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ApachiiHairFemales.esm'
    clean:
      - crc: 0xE7A2F17C
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Alpine Forest of Whiterun Valley.esp'
    clean:
      - crc: 0x148D179A
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'MajesticMountains_Landscape.esm'
    clean:
      - crc: 0x441A2CF8
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Unofficial Skyrim SE Fixes.esp'
    dirty:
      - <<: *quickClean
        crc: 0x6659FDB9
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 8
        udr: 8
```

```yaml
  - name: '1wraiths.esl'
    clean:
      - crc: 0x5D93A42C
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Chanterelle World.esp'
    clean:
      - crc: 0x50F68984
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Wyrmstooth.esp'
    clean:
      - crc: 0xFD63BB73
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ShumerWorld.esm'
    clean:
      - crc: 0x00E7A57F
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'SkyUI_SE.esp'
    clean:
      - crc: 0x79ACE179
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'HD Lods SSE.esp'
    clean:
      - crc: 0x8CC253C3
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'SMIM-SE-Merged-All.esp'
    clean:
      - crc: 0x35C26177
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Gildergreen Regrown.esp'
    clean:
      - crc: 0x7AA5675A
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Dolomite Weathers.esp'
    clean:
      - crc: 0xED02540C
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 26 - Realistic Fall Damages.esp'
    clean:
      - crc: 0x969C2D7D
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 14.08 - Respawn Vendor Stuff 15 days.esp'
    clean:
      - crc: 0x6CD21EF1
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 14.03 - Vendor Soul Gems Only Empty And Very Rare.esp'
    clean:
      - crc: 0x0024D0DC
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 04 - Mighty Odahviing.esp'
    clean:
      - crc: 0xFAE85536
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 04.2 - Mighty Durnehviir.esp'
    clean:
      - crc: 0x240539B3
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'RelightingSkyrim_SSE.esp'
    dirty:
      - <<: *quickClean
        crc: 0x2024C5F2
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
    clean:
      - crc: 0xCEB8CEE6
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 21.02 PM Blackreach.esp'
    clean:
      - crc: 0xC966BE77
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 14.07 - Vendor Very Less Weapons Armors.esp'
    clean:
      - crc: 0x174DCC23
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Aspens Ablaze.esp'
    clean:
      - crc: 0x95CB3F4D
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Skyrim 3D Trees and Plants DV.esp'
    clean:
      - crc: 0x556EF942
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'S3DPlants.esp'
    clean:
      - crc: 0x8E0AEEDE
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Ultimative Inventar Sortierung - Special.esp'
    dirty:
      - <<: *quickClean
        crc: 0x315FAA3C
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
```

```yaml
  - name: 'Landscape Fixes For Grass Mods.esp'
    clean:
      - crc: 0xCB2F8826
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Friendlier Taverns.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x1175B045
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 198
        udr: 28
        nav: 2
      - <<: *reqManualFix
        crc: 0x12B6F23E
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 2
```

```yaml
  - name: 'Cutting Room Floor.esp'
    dirty:
      - <<: *quickClean
        crc: 0x88390367
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
```

```yaml
  - name: 'Rebirth Monster.esp'
    clean:
      - crc: 0x5EF4DA72
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 08 - RUS-00 Main plus Dawnguard Dragonborn.esp'
    clean:
      - crc: 0x94261E13
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ERSO 08.1 - ERSO MIRAAKC.esp'
    clean:
      - crc: 0x0F06D5CF
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Treeswinedave.esp'
    clean:
      - crc: 0x52C6D099
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Helgen Reborn.esp'
    dirty:
      - <<: *quickClean
        crc: 0xBCE8ABD8
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 13
```

```yaml
  - name: 'Unique Shops and Stores.esp'
    clean:
      - crc: 0x6BA0B928
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Jehanna.esp'
    clean:
      - crc: 0x999DD8C7
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'PiratesNorth.esp'
    clean:
      - crc: 0xFE768BEE
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'ShumerNWa.esp'
    clean:
      - crc: 0xE06BFBB6
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'BirdsOfSkyrim_SSE.esp'
    clean:
      - crc: 0xEC917BA2
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Beautiful Cities.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA5DFA4B4
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 243
        udr: 22
```

```yaml
  - name: 'Erbe_der_vergessenen_SchaetzeSSE.esp'
    dirty:
      - <<: *quickClean
        crc: 0x745B96A2
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 166
```

```yaml
  - name: 'Ebonvale.esp'
    dirty:
      - <<: *quickClean
        crc: 0x16C089F4
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 9
```

```yaml
  - name: 'Man Those Borders!.esp'
    dirty:
      - <<: *quickClean
        crc: 0xF22B4D3E
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 66
```

```yaml
  - name: 'MajesticMountains_Moss.esp'
    clean:
      - crc: 0xC95C5FD2
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Populated Cities Towns Villages Legendary.esp'
    clean:
      - crc: 0x7AC65415
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'NR_SLIMprovedSE.esp'
    clean:
      - crc: 0x011DD8DD
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Serana Renewal.esp'
    clean:
      - crc: 0x3205C8EE
        util: 'SSEEdit v4.0.3'
```

```yaml
  - name: 'Jehanna.esp'
    dirty:
      - <<: *quickClean
        crc: 0xF3725DFD
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 94
```

**Comment by sibir-ine** [comment]
@Dreifels Adding reported data to a masterlist can take some time depending on when we have the chance to do so & how much data is being added, so, especially for a list this long, it won't necessarily be added within a day. Data not submitted as a PR takes longer as well as we need to add it ourselves.

Also, before we add any data to the masterlist, we need the URL for each mod so later maintainers can easily access the mod if updates are needed or to check if it has been deleted. Could you please provide the URLs for these mods? I only recognize a handful of these, & I can't guarantee the rest of the team or I will know where to locate the others. We'd appreciate it if you could do so. We would also be able to add them sooner with that information.

Just FYI, to format cleaning data, you can enclose them in triple back ticks as follows:

````
```yaml
  - name: 'Gildergreen Regrown.esp'
    clean:
      - crc: 0x7AA5675A
        util: 'SSEEdit v4.0.3'
```
````

to produce:

```yaml
  - name: 'Gildergreen Regrown.esp'
    clean:
      - crc: 0x7AA5675A
        util: 'SSEEdit v4.0.3'
```

The `yaml` just indicates what syntax highlighting to use. Since the masterlists are written in YAML, it's easier to read with YAML syntax highlighting.
