### ISSUE TITLE
'Artifacts of Skyrim - Revised Edition' cleaning report and suggested bash tags

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2020]
Mod name: Artifacts of Skyrim - Revised Edition

Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/49779

Mod version: 1.1.3

Cleaning report:

```yaml
  - name: 'Artifacts_Revised.esp'
    dirty:
      - <<: *quickClean
        crc: 0x19EAE888
        util: '[SSEEdit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1096
        udr: 9
    clean:
      - crc: 0xE06919BB
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

My suggested bash tags for `Artifacts_Revised.esp` (may be fully correct or not):

`Actors.ACBS, C.Light, Graphics, Invent.Add, NPC.DefaultOutfit, ObjectBounds, Outfits.Add`

There are also two patches in the optional files on the mod page that may need cleaning and bash tags.
