### ISSUE TITLE
Skyrim Immersive Creatures - Update changes

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#2028]
From [AFK mods](https://www.afkmods.com/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/&do=findComment&comment=180466) post by @lifestorock

### [SIC SE - Add-Ons and Patches](https://www.nexusmods.com/skyrimspecialedition/mods/54930/)

**Out of date** - [Skyrim Immersive Creatures - Official Patch and Patch Central](https://www.nexusmods.com/skyrimspecialedition/mods/18639)

```yaml
  - name: 'Skyrim Immersive Creatures Special Edition.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/12680/'
        name: 'Skyrim Immersive Creatures Special Edition'
    tag:
      - Actors.ACBS
      - Actors.AIData
      - Actors.CombatStyle
      - Actors.DeathItem
      - Actors.Stats
     #added tag
      - Delev
      - -C.Location
      - Factions
      - Graphics
      - Invent.Add
      - Invent.Remove
      - NPC.Class
      - NPC.Race
      #added tag
      - Relev
    msg:
      - *requiresMCM_SkyUISE
      - type: say
        content:
          - lang: en
            text: 'When using DwemerSpectresLegendary.esp, set Creature Toggles Dwemer Spectre to Disabled in MCM Settings.'
          - lang: de
            text: 'Wenn DwemerSpectresLegendary.esp genutzt wird, setzen Sie "Creature Toggles Dwemer Spectre" auf Deaktiviert in den MCM Einstellungen.'
        condition: 'active("DwemerSpectresLegendary.esp")'
      - <<: *patch3rdParty_STIP
        condition: 'active("SkyTEST-RealisticAnimals&Predators.esp") and not active("Skytest Immersive Creatures.esp")'
      - <<: *patch3rdParty
        subs:
          - 'Better Spell Learning'
          - '[Better Spell Learning - Patches](https://www.nexusmods.com/skyrimspecialedition/mods/24228/)'
        condition: 'active("Better Spell Learning.esp") and not active("Better Spell Learning - SIC SE Patch.esp")'
      - <<: *patch3rdParty
        subs:
          - 'Improved Closefaced Helmets'
      #changed to the current patch download location
          - '[SIC SE - Add-Ons and Patches](https://www.nexusmods.com/skyrimspecialedition/mods/54930/)'
        condition: 'active("imp_helm_legend.esp") and not active("SIC - ICH Patch.esp")'
      - <<: *patch3rdParty
        subs:
          - 'Wintersun - Faiths of Skyrim'
          - '[Wintersun - More Patches](https://www.nexusmods.com/skyrimspecialedition/mods/24228/)'
        condition: 'active("Wintersun - Faiths of Skyrim.esp") and not active("Wintersun - SIC Patch.esp") and not active("Wintersun_GBRS_SIC_ZIA_Patch.esp")'
      - <<: *patch3rdParty_KPH_CACO
        condition: 'active("Complete Alchemy & Cooking Overhaul.esp") and not active("CACO_SkyrimImmersiveCreaturesSE_Patch.esp")'
      #newly added compatibility patch
      - <<: *patch3rdParty
        subs:
          - 'Complete Crafting Overhaul Remastered'
          - '[SIC SE - Add-Ons and Patches](https://www.nexusmods.com/skyrimspecialedition/mods/54930/)'
        condition: 'active("Complete Crafting Overhaul_Remastered.esp") and not active("SIC CCOR Patch.esp")'
      #newly added compatibility patches
      - <<: *patch3rdParty
        subs:
          - 'Immersive Sounds - Compendium'
          - '[SIC SE - Add-Ons and Patches](https://www.nexusmods.com/skyrimspecialedition/mods/54930/)'
        condition: 'active("Immersive Sounds - Compendium.esp") and not active("SIC - Immersive Sound Integration.esp")'
      - <<: *patch3rdParty
        subs:
          - 'Nix-Hound'
          - '[SIC SE - Add-Ons and Patches](https://www.nexusmods.com/skyrimspecialedition/mods/54930/)'
        condition: 'active("ccbgssse035-petnhound.esl") and not active("SIC CClub Nixhound Patch.esp")'
      - <<: *patch3rdParty
        subs:
          - 'Saints & Seducers'
          - '[SIC SE - Add-Ons and Patches](https://www.nexusmods.com/skyrimspecialedition/mods/54930/)'
        condition: 'active("ccbgssse025-advdsgs.esm") and not active("SIC CClub Saints & Seducer Integration.esp")'
      # this needs to be removed. will break the current mod version -> maybe add a warning?
      - <<: *patchUpdateAvailable
        subs: [ '[Skyrim Immersive Creatures - Official Patch and Patch Central](https://www.nexusmods.com/skyrimspecialedition/mods/18639/)' ]
        condition: 'active("Skyrim Immersive Creatures Special Edition.esp") and checksum("Skyrim Immersive Creatures Special Edition.esp", 7CD2929B)'
    clean:
      #removed the patch esp and added CRC for the current clean "Skyrim Immersive Creatures Special Edition.esp"
      - crc: 0xB39C68DE
        util: 'SSEEdit v4.0.3'

```

---

- [x] Remove message `patchUpdateAvailable`.
- [x] Update tag suggestions.
- [x] Update patch messages.
- [x] Add Obsolete message for older versions.
