### ISSUE TITLE
And a bunch more ITMs... maybe add a bit more later

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/skyrimse#2050]
- [x] [Hearthfire Extended](https://www.nexusmods.com/skyrimspecialedition/mods/8450)
```
  - name: 'hearthfireextended.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA50C3D2B
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x720671F5
        util: 'SSEEdit v4.0.3'
```
Argonian Hearthfire (no link, because was deleted off Nexus)
```
  - name: 'ArgonianHearthfire.esp'
    dirty:
      - <<: *quickClean
        crc: 0x457CB0B3
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0x0F9F99D9
        util: 'SSEEdit v4.0.3'
```
- [x] [Hearthfire Enhanced](https://tes5stuff.blogspot.com/search/label/Recommend%3B) (best guess as to where to get it at all)
```
  - name: 'HearthFiresEnhanced.esp'
    dirty:
      - <<: *quickClean
        crc: 0x10633FF2
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
    clean:
      - crc: 0x120F2679
        util: 'SSEEdit v4.0.3'
```
- [x] [Dovahkiin Vault](https://www.nexusmods.com/skyrimspecialedition/mods/42237)
```
  - name: 'Eli_Dovah Vault.esp'
    dirty:
      - <<: *quickClean
        crc: 0xE9D52EC1
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x0DF6AC5C
        util: 'SSEEdit v4.0.3'
```
- [x] [Yuriana Wench](https://www.nexusmods.com/skyrimspecialedition/mods/598)
```
  - name: 'YurianaWench.esp'
    dirty:
      - <<: *quickClean
        crc: 0xE37FB948
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 20
    clean:
      - crc: 0xF61C3C8C
        util: 'SSEEdit v4.0.3'
```
