### ISSUE TITLE
Dawnguard and Clan Volkihar Epilogues link change and cleaning report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2066]
The author's mods have all been removed from the Nexus and reuploaded to AFK Mods:

> Due to recent decisions made by Nexus Mods, and their handling of those decisions, I will no longer be hosting my mods here, as I have lost all trust in them, and fear that allowing my files to remain would be a violation of the Bethesda Creation Kit End-User License Agreement.

> My mods have been relocated to AFK Mods (https://www.afkmods.com) if you're looking for something that you know I made. *-  [SkyLover264](https://www.nexusmods.com/users/16142639)*

The new location for this mod can be found here: https://www.afkmods.com/index.php?/files/file/2299-dawnguard-and-clan-volkihar-epilogues/

Cleaning report for version 2.2:

```yaml
  - name: 'Dawnguard&VolkiharArtifactsQuests.esp'
    dirty:
      - <<: *quickClean
        crc: 0xA887288B
        util: '[SSEEdit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
    clean:
      - crc: 0xAE46CD2A
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```
