### ISSUE TITLE
The Real Shady

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2096]
Mod name: The Real Shady

Mod version: 1.10

Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/31478

Cleaning report:

```yaml
  - name: 'TheRealShady.esp'
    clean:
      - crc: 0xE5BCC27A
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Suggested bash tags:

```
Actors.ACBS
Actors.AIData
Actors.AIPackages
Actors.Stats
Factions
Invent.Add
Invent.Change
Invent.Remove
NPC.AttackRace
NPC.Class
NPC.DefaultOutfit
ObjectBounds
```
