### ISSUE TITLE
Fulcimentum - More Staves and Wands of Skyrim

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2097]
Mod name: Fulcimentum - More Staves and Wands of Skyrim

Mod version: 3.5

Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/23825

Cleaning report:

```yaml
  - name: 'Fulcimentum - More Staves and Wands of Skyrim.esp'
    dirty:
      - <<: *quickClean
        crc: 0x6B27B98E
        util: '[SSEEdit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x4FE37BE9
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Suggested bash tags:

```
Delev
Invent.Add
Keywords
```
