### ISSUE TITLE
Artifacts of the Court Wizards

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2098]
Mod name: Artifacts of the Court Wizards

Mod version: 1.1.0

Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/51393

Cleaning report:

```yaml
  - name: 'ArtifactsOfTheCourtWizards.esp'
    clean:
      - crc: 0x6D5880CE
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Suggested bash tags:

`Invent.Add`
