### ISSUE TITLE
Get Both Rewards 1.1

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2099]
Mod name: Get Both Rewards 1.1

Mod version: 1.1

Mod link: https://www.afkmods.com/index.php?/files/file/2293-get-both-rewards/

Cleaning report:

```yaml
  - name: 'GetBothRewardsSeries.esp'
    clean:
      - crc: 0xF9821CE2
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Suggested bash tags:

`Invent.Add`
