### ISSUE TITLE
Update SKSE version checks for new 2.0.20 build

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrimse#2107]
https://skse.silverlock.org/

Current masterlist entry:
```yaml
  # SKSE 64
  - <<: *versionOldX
    subs: [ '**Script Extender ([SKSE 64](https://skse.silverlock.org))**' ]
    condition: 'version("../skse64_loader.exe", "0.2.0.19", <) and file("../SkyrimSE.exe") and not file("SkyrimVR.esm") and file("../skse64_loader.exe")'
  - <<: *versionUpToDateX
    subs: [ '**Script Extender ([SKSE 64](https://skse.silverlock.org))**' ]
    condition: 'version("../skse64_loader.exe", "0.2.0.19", >=) and file("../SkyrimSE.exe") and not file("SkyrimVR.esm") and file("../skse64_loader.exe")'
```
Changelog of the new version:
> 2.0.20
> - mark changed flags for SetHarvested
> - process priority loader command line argument now actually works
> - loader change: dll main functions are called outside LoadLibrary
