### ISSUE TITLE
Better Candlelight

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2112]
Mod name: Better Candlelight

Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/4553/

Mod version: 1.0

Cleaning report:

Better Candlelight v1.0
Main
```yaml
  - name: 'Better Candlelight.esp'
    clean:
      - crc: 0xBD16A6B2
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Better Candlelight v1.0
Unlimited
```yaml
  - name: 'Better Candlelight.esp'
    clean:
      - crc: 0xE6CCC39C
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Suggested bash tags for both .esps:

`EffectStats`
