### ISSUE TITLE
Better Hunters

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2113]
Mod name: Better Hunters

Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/3329/

Mod version: 1.0.1

Cleaning report:

Better Hunters v1.0.1
Main
```yaml
  - name: 'Better Hunters.esp'
    dirty:
      - <<: *quickClean
        crc: 0x78B50785
        util: '[SSEEdit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 41
    clean:
      - crc: 0x680D15F3
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Better Hunters v1.0.1
No Hunter Camps
```yaml
  - name: 'Better Hunters.esp'
    clean:
      - crc: 0x6CA160AA
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Better Hunters v1.0.0
Main
```yaml
  - name: 'Better Hunters.esp'
    dirty:
      - <<: *quickClean
        crc: 0x34241866
        util: '[SSEEdit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 41
    clean:
      - crc: 0x6043DA88
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Better Hunters v1.0.0
No Hunter Camps
```yaml
  - name: 'Better Hunters.esp'
    clean:
      - crc: 0x656DA834
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

Suggested bash tags for all .esps:

```
      - Actors.ACBS
      - Actors.Perks.Add
      - Actors.Stats
      - Factions
      - Invent.Add
      - Invent.Remove
      - NPC.Class
      - NPC.DefaultOutfit
```
