### ISSUE TITLE
New ITMs

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/skyrimse#2122]
- [x] [Here There Be Monsters - The Call Of Cthulhu SSE](https://www.nexusmods.com/skyrimspecialedition/mods/35934)
```
  - name: 'Here There Be Monsters - Call of Cthulhu.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xA9CDB25B
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 273
        nav: 73
    dirty:
      - <<: *reqManualFix
        crc: 0xD452BB59
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 73
```

- [x] ['Here There Be Monsters - Curse of Cipactli](https://www.nexusmods.com/skyrimspecialedition/mods/35933)
```
  - name: 'Here There Be Monsters - Curse of Cipactli.esp'
    dirty:
      - <<: *quickClean
        crc: 0x30269D8B
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 22
    clean:
      - crc: 0x3BC946E0
        util: 'SSEEdit v4.0.3'
```

- [x] [SE - Better Cities Patch](https://www.nexusmods.com/skyrimspecialedition/mods/8)
```
  - name: 'SE - Better Cities Patch.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x9F007D48
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 34
        nav: 11
    dirty:
      - <<: *reqManualFix
        crc: 0x86BAE7A6
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 11
```
