### ISSUE TITLE
Serenity - A Silent Moons Camp Overhaul

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#2129]
Mod name: Serenity - A Silent Moons Camp Overhaul

Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/30019

Mod version: 1.2.4

Suggested bash tags for `Serenity.esp`:

```
  - name: 'Serenity.esp'
    tag:
      - C.Location
      - Delev
      - EffectStats
      - Graphics
      - Keywords
      - Names
      - Stats
      - Text
```

Cleaning report:

```yaml
  - name: 'Serenity.esp'
    dirty:
      - <<: *quickClean
        crc: 0x5972B869
        util: '[SSEEdit v4.0.3h (Hotfix 1)](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
    clean:
      - crc: 0x54652F9B
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```
