### ISSUE TITLE
Cleaning data reports

### ISSUE THREAD

**Issue by cecell** [loot/skyrimse#2287]
```yaml
  - name: 'AnotherOakwood.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/61007/' ]
    dirty:
      - <<: *quickClean
        crc: 0xEE69FD67
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 5
    clean:
      - crc: 0xBB723686
        util: 'SSEEdit v4.0.4'
```

```yaml
  - name: 'Syerscote.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/58403/' ]
    dirty:
      - <<: *reqManualFix
        crc: 0x80E9D9C0
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
        udr: 4
        nav: 2
      - <<: *reqManualFix
        crc: 0xFD079DBD
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 2
```

```yaml
  - name: 'Thena.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/36700/' ]
    dirty:
      - <<: *quickClean
        crc: 0x7CA4122E
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x6E76D261
        util: 'SSEEdit v4.0.4'
```

```yaml
  - name: 'TissPumpkinORD.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/30143/' ]
    dirty:
      - <<: *quickClean
        crc: 0x1A383542
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0xA5DC7133
        util: 'SSEEdit v4.0.4'
```

```yaml
  - name: 'UnexpectedComments.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/39935/' ]
    dirty:
      - <<: *quickClean
        crc: 0xDABA090F
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
    clean:
      - crc: 0x6ECA769D
        util: 'SSEEdit v4.0.4'
```
