### ISSUE TITLE
Load `AnotherOakwood.esp` after `ogFalkreathHauntings.esp`

### ISSUE THREAD

**Issue by cecell** [loot/skyrimse#2297]
```yaml
  - name: 'AnotherOakwood.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/61007/' ]
    after: [ 'ogFalkreathHauntings.esp' ]
```

[The Falkreath Hauntings](https://www.nexusmods.com/skyrimspecialedition/mods/20733)
