### ISSUE TITLE
Add cleaning data for BardsRebornStudentofSong.esp

### ISSUE THREAD

**Issue by cecell** [loot/skyrimse#2299]
```
  - name: 'BardsRebornStudentofSong.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/47994/' ]
    dirty:
      - <<: *quickClean
        crc: 0x15455DFE
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
    clean:
      - crc: 0xDC8B5D2F
        util: 'SSEEdit v4.0.4'
```
