### ISSUE TITLE
Misspelling in patch list for 'Lanterns Of Skyrim II.esm'

### ISSUE THREAD

**Issue by Glanzer-modder** [loot/skyrimse#2355]
In the entry for 'Lanterns Of Skyrim II.esm,' the word "Sinkhole" is misspelled as "Skinkhole" in the condition line and it causes a notification to appear telling users they don't have the patch even when they do have the patch:

```yaml
  - name: 'Lanterns Of Skyrim II.esm'
    [...]
      - <<: *patchIncluded
        subs: [ 'Soljund''s Sinkhole' ]
        condition: 'active("Soljund''s Sinkhole.esp") and not active("LoS II - Soljund''s Skinkhole patch.esp")'
```
