### ISSUE TITLE
Change USSEP's LOOT Message to check BSA CRC instead of EXE

### ISSUE THREAD

**Issue by ixanza** [loot/skyrimse#2400]
![image](https://user-images.githubusercontent.com/5535758/167333561-6eb613c5-587a-40e9-ba10-757691a358a2.png)

This isn't an accurate error message due to the existance of the Best of Both Worlds Downgrade Patcher which downgrades the EXE to 1.5.97 while keeping all the ESMs and BSA's updated. The Skyrim Reverse Engineers have pretty much concluded that there is no new functionality in the 1.6 EXEs that prevent anything from the newer esms and bsa's from working fine, hence the check here should just be on the BSAs and ESMs instead of the EXE as the ESMs are the one that contain the changes USSEP needs to function properly and not the EXE. 

The message now is generating unecessary doubt in many people on various skyrim discords wondering if they messed something up when its not the case.

**Comment by pStyl3** [comment]
Let's first have a look at the situation as of right now. This is the current implementation of the above message.

prelude.yaml
```yaml
  - &versionXofYorGreaterRequired
    type: error
    content:
      - lang: en
        text: 'Requires version **%1%** or greater of **%2%**.'
      # Other languages omitted for brevity
```
masterlist.yaml
```yaml
  - name: 'Unofficial Skyrim Special Edition Patch.esp'
    msg:
      - <<: *versionXofYorGreaterRequired
        subs:
          - '1.6.323.0'
          - 'Skyrim Special Edition'
        condition: 'readable("../SkyrimSE.exe") and product_version("../SkyrimSE.exe", "1.6.323.0", <) and version("Unofficial Skyrim Special Edition Patch.esp", "4.2.6a", >=)'
```
The `readable()` check was recently introduced & added here, so that in case the user is modding the Microsoft Store / Game Pass version of the game, the condition is short-circuited and evaluates to false. The reasoning behind that can be found [here](https://github.com/loot/loot/issues/1436).

The part of the condition, that potentially would need to be changed according to this request, is therefore
`'product_version("../SkyrimSE.exe", "1.6.323.0", <)`

If the downgraded `SkyrimSE.exe` is no longer of product version `1.6.323.0` but instead `1.5.97.0`, the error message get's displayed. That is why users of the Downgrade Patcher see this error message.
___
[Unofficial Skyrim Special Edition Downgrade Patcher](https://www.nexusmods.com/skyrimspecialedition/mods/57618)
[Unofficial Skyrim Downloader](https://www.nexusmods.com/skyrimspecialedition/mods/61756)
[Skyrim Downgrade Patcher Usage](https://www.youtube.com/watch?v=dja6naOOpM8)

> The Skyrim Reverse Engineers have pretty much concluded that there is no new functionality in the 1.6 EXEs that prevent anything from the newer esms and bsa's from working fine, hence the check here should just be on the BSAs and ESMs instead of the EXE as the ESMs are the one that contain the changes USSEP needs to function properly and not the EXE.

I'm assuming that by `Skyrim Reverse Engineers` you refer to @halgari and possibly someone else as well? Could you clarify who you mean by that?

In the video I've linked above, halgari says, starting at 5:20:
> But otherwise, you can do here, is select "Best of Both Worlds" and what this will do, is use all the new BSAs and the ESMs with the old executable. Now, I only suggest you use this, if you have a setup that overrides the UI. There are some problems.
> 
> (...)
> 
> Two things, first of all, I was saying here, only use Best of Both Worlds, if you know what you're doing. And the reason is, that there are some parts of the interface, in the new version, of Steam, that are different from the old. So the best option there, is if you gonna use Best of Both Worlds, make sure that you're doing enough UI updates, that it removes those changes. You gonna definitely want SkyUI, and I would also recommend, something like Cleaner Start Menu. It has something to do with the start menu, is a little wonky, when you're mixing the old EXE and the new assets, the new interface assets. So just override that with a different mod and you'll be fine.

Also, to quote the above linked mod pages:
> **Q**: I used the "Best of Both Worlds" Patcher and now I can't move with the keyboard, or in the menus!
**A**: There's a strange conflict with this patcher and lightly modded setups, I recommend some sort of main menu replacer like [Clean Menu](https://www.nexusmods.com/skyrimspecialedition/mods/3223) to override these files and fix the issue.

While I personally cannot comment on the severity of the mentioned "wonkyness" of this issue, I don't think that `there is no new functionality in the 1.6 EXEs that prevent anything from the newer esms and bsa's from working fine` (after downgrading) is describing the situation correctly. The things halgari talks about in the video seem to be reasonable, but there seems to be work needed after downgrading the game to get everything 100% working once again.

Given the above, and also the fact, that the downgrader currently only seems to be supporting the english version of the game, I'm not yet convinced, that switching to CRC checks on the BSAs would be the best way to handle this situation.

One possible way this issue could be addressed is our open issue [Set hide options for single plugin in filter](https://github.com/loot/loot/issues/1083), that way after intentionally downgrading the game could the user hide the error message for USSEP.

Also pinging @Ortham just in case.
