### ISSUE TITLE
OCW Obscure College of Winterhold: False warning

### ISSUE THREAD

**Issue by suamor** [loot/skyrimse#2502]
Installed: [OCW Obscure College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/20514)
Installed: [TGC Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/17127)
Loot complains about missing compatibility patch.
But the patch is installed: OCW_TGCs_FEPatch.esp.
There are two compatibility patches (it is stated in the installer that only one of those patches are to be used. The larger patch that I use contains changes of the smaller one).

**Comment by MacSplody** [comment]
```yaml
      - <<: *patchIncluded
        subs: [ 'The Great Cities - Minor Cities and Towns' ]
        condition: 'active("The Great Cities - Minor Cities and Towns.esp") and not active("OCW_TGCs_FEPatch.esp")'
      - <<: *patchIncluded
        subs: [ 'The Great City of Winterhold' ]
        condition: 'active("The Great City of Winterhold.esp") and not active("OCW_TGCoW_FEPatch.esp")'
```

`OCW_TGCs_FEPatch.esp` is for `The Great Cities - Minor Cities and Towns.esp`.
`OCW_TGCoW_FEPatch.esp` is for `The Great City of Winterhold.esp`.

Don't select both options in the installer, as it will only install the Minor Cities and Towns patch.
