### ISSUE TITLE
Reevaluate unaliased messages

### ISSUE THREAD

**Issue by sibir-ine** [loot/skyrimse#2587]
- [x] Children.esp
- [x] ImCh.esm
- [x] Killable Children.esp
- [x] FacegenForKids.esp
- [x] AsharaSkyrimCharacterPresetsReplacer.esp
- [x] Better_Male_Presets.esp
- [x] Kayla_CharPreset.esp
- [x] Lagertha_CharPreset.esp
- [x] Lydia Face Preset 64bit.esp
- [x] Skyrim Immersive Creatures Special Edition.esp
- [x] SAFO - Valdacil.esp
- [x] Andromeda - Unique Standing Stones of Skyrim.esp
- [x] Convenient Horses.esp
- [x] tcbm.esp
- [x] Growl - Werebeasts of Skyrim.esp
- [x] Immersive Jewelry.esp
- [x] Distinct Interiors.esp
- [x] Distinct Interiors - Player Homes.esp
- [x] EEKs Immersive Whiterun.esp
- [x] `(Solitude Skyway SE Estuary Fortress Extension|Solitude Skyway SE Estuary Fortress Access Extension)\.esp`
- [x] TGCoS + Solitude Skyway SE [PATCH - KvHarborside].esp

**Comment by pStyl3** [comment]
Here are the aforementioned messages (I've condensed the relevant parts from the masterlist a bit):

- [X] **Message 1**
`After Character Creation you should deactivate and/or uninstall this.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'AsharaSkyrimCharacterPresetsReplacer.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/2406/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'After Character Creation you should deactivate and/or uninstall this.'
        condition: 'active("AsharaSkyrimCharacterPresetsReplacer.esp")'

  - name: 'Better_Male_Presets.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/2001/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'After Character Creation you should deactivate and/or uninstall this.'
        condition: 'active("Better_Male_Presets.esp")'

  - name: 'Kayla_CharPreset.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/3851/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'After Character Creation you should deactivate and/or uninstall this.'
        condition: 'active("Kayla_CharPreset.esp")'

  - name: 'Lagertha_CharPreset.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/2629/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'After Character Creation you should deactivate and/or uninstall this.'
        condition: 'active("Lagertha_CharPreset.esp")'

  - name: 'Lydia Face Preset 64bit.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/1080/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'After Character Creation you should deactivate and/or uninstall this.'
        condition: 'active("Lydia Face Preset 64bit.esp")'
```
</details>

___

- [ ] **Message 2**
`An unresolved reference to a package from an older version of USSEP, must be removed from record **X** in **Y**. A guide is available [here](URL)`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'Children.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/2822/' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'An unresolved reference to a package from an older version of USSEP, must be removed from record **00014132** in **Children.esp**. A guide is available [here](https://macsplody.github.io/xGuides/#-children-)'
        condition: '(file("Unofficial Skyrim Special Edition Patch.esp") and version("Unofficial Skyrim Special Edition Patch.esp", "4.1.8", >)) and checksum("Children.esp", EE60F522)'

  - name: 'FacegenForKids.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/22789/' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'An unresolved reference to a package from an older version of USSEP, must be removed from record **00014132** in **FacegenForKids.esp**. A guide is available [here](https://macsplody.github.io/xGuides/#-simple-children-)'
        condition: '(file("Unofficial Skyrim Special Edition Patch.esp") and version("Unofficial Skyrim Special Edition Patch.esp", "4.1.8", >)) and checksum("FacegenForKids.esp", DB8F0931)'
```
</details>

___

- [X] **Message 3**
`Remember to run the included SSEEdit script **MXPF - One ImCh Patcher** every time you have installed or un-installed a mod. Use the recommended patch name **One ImCh Patch** or **One ImCh Patcher** for correct sorting. Instructions for running this patcher can be found on the [Immersive Children](https://www.nexusmods.com/skyrimspecialedition/mods/15001/) description page.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'ImCh.esm'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/15001/'
        name: 'Immersive Children SE - child mortality and burial and animation fixes'
    msg:
      - type: say
        content:
          - lang: en
            text: 'Remember to run the included SSEEdit script **MXPF - One ImCh Patcher** every time you have installed or un-installed a mod. Use the recommended patch name **One ImCh Patch** or **One ImCh Patcher** for correct sorting. Instructions for running this patcher can be found on the [Immersive Children](https://www.nexusmods.com/skyrimspecialedition/mods/15001/) description page.'
```
</details>

___

- [ ] **Message 4**
`This plugins changes to the Default Object Manager record may revert changes in other mods. Remove record **00000031** and install [IDRS - Improved Disabled Race Scaling](https://www.nexusmods.com/skyrimspecialedition/mods/19094/).`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'Killable Children.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/1108/' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugins changes to the Default Object Manager record may revert changes in other mods. Remove record **00000031** and install [IDRS - Improved Disabled Race Scaling](https://www.nexusmods.com/skyrimspecialedition/mods/19094/).'
        condition: 'checksum("Killable Children.esp", 0E290E34) or not file("RaceScalingDisabled.esp")'
```
</details>

___

- [x] **Message 5**
`This plugin seems to be outdated and may not be compatible with the latest version of its master files.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'SAFO.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/12343/'
        name: 'Skyrim Alchemy and Food Overhaul'
  - name: 'SAFO - Valdacil.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: 'This plugin seems to be outdated and may not be compatible with the latest version of its master files.'
        condition: 'checksum("SAFO - Valdacil.esp", DE73CDD3)'
```
</details>

**Comment by pStyl3** [comment]
- [x] **Message 6**
`Make sure the Disparity option "Use Modified Blessings" is disabled.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'Andromeda - Unique Standing Stones of Skyrim.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/14910/' ]
    msg:
      - type: say
        content:
          - lang: en
            text: 'Make sure the Disparity option "Use Modified Blessings" is disabled.'
        condition: 'active("Disparity.esp")'
```
</details>

___

- [X] **Message 7**
`Amazing Follower Tweaks "horse features" and "follower teleport on weapon draw setting" must be disabled for Convenient Horses to function correctly.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'Convenient Horses.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/9519/' ]
    msg:
      - type: say
        condition: 'active("AmazingFollowerTweaks.esp")'
        content:
          - lang: en
            text: 'Amazing Follower Tweaks "horse features" and "follower teleport on weapon draw setting" must be disabled for Convenient Horses to function correctly.'
```
</details>

___

- [X] **Message 8**
`Delete %1% from %2%. %3%''s script must take precedence.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'tcbm.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/9800/'
        name: 'Thieves Guild Alternate Routes: Taking Care of Business Mod'
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/10745/'
        name: 'Thieves Guild For Good Guys: Taking Care of Business Redux'
    msg:
      - type: error
        content:
          - lang: en
            text: 'Delete %1% from %2%. %3%''s script must take precedence.'
        subs:
          - 'QF_MS11_0001F7A3.pex'
          - 'Thieves Guild For Good Guys'
          - 'USSEP'
        condition: 'active("Unofficial Skyrim Special Edition Patch.esp") and file("scripts/QF_MS11_0001F7A3.pex") and checksum("scripts/QF_MS11_0001F7A3.pex", 22A14151)'

  - name: 'Growl - Werebeasts of Skyrim.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/31245/' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'Delete %1% from %2%. %3%''s script must take precedence.'
        subs:
          - 'PlayerWerewolfChangeScript.pex'
          - 'RaceCompatibility'
          - 'Growl - Werebeasts of Skyrim'
        condition: 'file("RaceCompatibility.esm") and file("Scripts/PlayerWerewolfChangeScript.pex")'
```
</details>

___

- [x] **Message 9**
`Version 1.05 of this mod contains corrupt records. Update to version 1.06a.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'Immersive Jewelry.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/5336/' ]
    msg:
      - type: warn
        content:
          - lang: en
            text: 'Version 1.05 of this mod contains corrupt records. Update to version 1.06a.'
        condition: 'version("Immersive Jewelry.esp", "1.05", ==)'
```
</details>

___

- [ ] **Message 10**
`This plugin includes records deleted by its master files. A guide to fixing this can be found [here](https://macsplody.github.io/xGuides/#-distinct-interiors-).`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'Distinct Interiors.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'This plugin includes records deleted by its master files. A guide to fixing this can be found [here](https://macsplody.github.io/xGuides/#-distinct-interiors-).'
        condition: 'checksum("Distinct Interiors.esp", 6977340A)'

  - name: 'Distinct Interiors - Player Homes.esp'
    msg:
      - type: error
        content:
          - lang: en
            text: 'This plugin includes records deleted by its master files. A guide to fixing this can be found [here](https://macsplody.github.io/xGuides/#-distinct-interiors-).'
        condition: 'checksum("Distinct Interiors - Player Homes.esp", 289785CC)'
```
</details>

___

- [ ] **Message 11**
`This plugin references a record **000CB4F3**, which has been deleted by Hearthfires.esm. This must be corrected manually by the mod author.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'EEKs Immersive Whiterun.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/31214/' ]
    msg:
      - type: error
        content:
          - lang: en
            text: 'This plugin references a record **000CB4F3**, which has been deleted by Hearthfires.esm. This must be corrected manually by the mod author.'
        condition: 'checksum("EEKs Immersive Whiterun.esp", 7CAB09F2) or checksum("EEKs Immersive Whiterun.esp", 16BF915D)'
```
</details>

___

- [ ] **Message 12**
`When using DwemerSpectresLegendary.esp, set Creature Toggles Dwemer Spectre to Disabled in MCM Settings.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'Skyrim Immersive Creatures Special Edition.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/12680/'
        name: 'Skyrim Immersive Creatures Special Edition'
    msg:
      - type: say
        content:
          - lang: en
            text: 'When using DwemerSpectresLegendary.esp, set Creature Toggles Dwemer Spectre to Disabled in MCM Settings.'
        condition: 'active("DwemerSpectresLegendary.esp")'
```
</details>

___

- [X] **Message 13**
`Make sure you have completely uninstalled files included with old versions of this mod.`

<details>
  <summary>Masterlist entries</summary>

```yaml
  - name: 'Skyrim Immersive Creatures Special Edition.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/12680/'
        name: 'Skyrim Immersive Creatures Special Edition'
    msg:
      - type: error
        content:
          - lang: en
            text: 'Make sure you have completely uninstalled files included with old versions of this mod.'
        condition: 'file("scripts/scc_spelleater_script.pex") and version("Skyrim Immersive Creatures Special Edition.esp", "7.0.0", >=)'
```
</details>

**Comment by pStyl3** [comment]
@MacSplody
Your input would definitely help, as some messages link to guides written by you.

@sibir-ine
I think the entries for
`(Solitude Skyway SE Estuary Fortress Extension|Solitude Skyway SE Estuary Fortress Access Extension)\.esp`
and
`TGCoS + Solitude Skyway SE [PATCH - KvHarborside].esp`
are already handled by https://github.com/loot/skyrimse/pull/2709 is that correct?

**Comment by sibir-ine** [comment]
Yes, I replaced them.

**Comment by pStyl3** [comment]
I think we can create new message anchors for Messages 1 and 8.

```
Message 1
After Character Creation you should deactivate and/or uninstall this.

Message 8
Delete %1% from %2%. %3%''s script must take precedence.
```

Message 1 could be modified to
```yaml
  - &deactivateAfterCharacterCreation
    type: say
    content:
      - lang: en
        text: 'Deactivate and/or uninstall this mod after character creation.'
```

Message 8 can stay as it is, in my opinion. So:
```yaml
  - &scriptPrecedence
    type: error
    content:
      - lang: en
        text: 'Delete %1% from %2%. %3%''s script must take precedence.'
```

Regarding Message 6 (`Make sure the Disparity option "Use Modified Blessings" is disabled.`), potentially we could create a more generalised message from this as well. That being said, as of now it is only used once in the masterlist & that use case is questionable to begin with. The message comes from this [compatibility list](https://www.nexusmods.com/skyrimspecialedition/articles/365), and it refers to the SLE mod [Disparity -- Player Character Class - Race and Gender Diversity](https://www.nexusmods.com/skyrim/mods/63354/). Apparently there's a SSE port coming (according to the comments on the mod page), but that hasn't been posted until now. Even if, does it make sense to add a message of type `say` to a plugin, if it is only one of multiple compatibility messages that are available on the aforementioned article?

**Comment by sibir-ine** [comment]
> Message 1 could be modified to
> 
> ```yaml
>   - &deactivateAfterCharacterCreation
>     type: say
>     content:
>       - lang: en
>         text: 'Deactivate and/or uninstall this mod after character creation.'
> ```

It's close enough to the original that I don't think we need to throw out it's translations, so I'm fine with the change.

> Message 8 can stay as it is, in my opinion. So:
> 
> ```yaml
>   - &scriptPrecedence
>     type: error
>     content:
>       - lang: en
>         text: 'Delete %1% from %2%. %3%''s script must take precedence.'
> ```

We could generalize this message by changing "script" to something like "version."

> Regarding Message 6 (`Make sure the Disparity option "Use Modified Blessings" is disabled.`), potentially we could create a more generalised message from this as well. That being said, as of now it is only used once in the masterlist & that use case is questionable to begin with. The message comes from this [compatibility list](https://www.nexusmods.com/skyrimspecialedition/articles/365), and it refers to the SLE mod [Disparity -- Player Character Class - Race and Gender Diversity](https://www.nexusmods.com/skyrim/mods/63354/). Apparently there's a SSE port coming (according to the comments on the mod page), but that hasn't been posted until now. Even if, does it make sense to add a message of type `say` to a plugin, if it is only one of multiple compatibility messages that are available on the aforementioned article?

It's one of the few mods in that list with instructions that we can't convey or act on with other metadata, so I think it makes sense to have a specific message for it. However, I would prefer to replace it with `compatIssuesWithX`. We could add more for the other mods with special instructions, specifically Convenient Horses (& remove the load after). Re it not being ported yet, one of the authors who said it would likely be ported soon was active at least within the last few months, so I'd prefer to keep it after replacing it. However, I'd be fine with just adding it back after it's actually ported.

**Comment by pStyl3** [comment]
> It's close enough to the original that I don't think we need to throw out it's translations, so I'm fine with the change.

I think I will purge the old translations anyway (and update the german one), since the adjusted message talks about `this mod` in comparison to `this`.

> We could generalize this message by changing "script" to something like "version."

Good idea.

I will add these new message anchors now.

**Comment by pStyl3** [comment]
Regarding **Message 3**, which is used once for `ImCh.esm` - [Immersive Children SE](https://www.nexusmods.com/skyrimspecialedition/mods/15001/) is no longer supported & the author recommends in his comment section to use either [Slayable Offspring SKSE](https://www.nexusmods.com/skyrimspecialedition/mods/46826/) or [Savage Offspring SKSE](https://www.nexusmods.com/skyrimspecialedition/mods/49377/) instead.

As such, instead of including the detailed patching instructions via a custom message, I would say we just use the following instead:
```yaml
    msg:
      - <<: *compatNotes
        subs: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/15001/' ]
```
