### ISSUE TITLE
Races of Nirn - Kapo'tun

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/skyrimse#2733]
[Races of Nirn - Kapo'tun SE](https://www.nexusmods.com/skyrimspecialedition/mods/40928), port by SirRumple
[Races of Nirn - Kapotun Reborn](https://www.nexusmods.com/skyrimspecialedition/mods/77612), remake by IllusiveMan196

```
  - name: 'DWKaPoTunRace.esp'
    clean:
      # Original
      - crc: 0x672EB2D2
        util: 'SSEEdit v4.0.4'
      # Reborn
      - crc: 0x287A2A43
        util: 'SSEEdit v4.0.4'

  - name: 'SOS - Kapotun Addon.esp'
    clean:
      - crc: 0xFCE78411
        util: 'SSEEdit v4.0.4'
```

Rules for mods:
Incompatible with any Races of Nirn - Kapo'tun SE and Races of Nirn - Kapotun Reborn ≥V2:
Kapotun ARMA Amelia Bandage.esp
Kapotun ARMA Artaeum.esp
Kapotun ARMA BeABard.esp
Kapotun ARMA Campfire.esp
Kapotun ARMA Cloaks.esp
Kapotun ARMA Clockwork.esp
Kapotun ARMA Draugr Upgrades.esp
Kapotun ARMA Ebonscale.esp
Kapotun ARMA Enhanced Solitude.esp
Kapotun ARMA EquippableTomes.esp
Kapotun ARMA ExpandedJewelry.esp
Kapotun ARMA Falskaar.esp
Kapotun ARMA Forgotten City.esp
Kapotun ARMA Glamoril.esp
Kapotun ARMA Gray Fox (mannyGT).esp
Kapotun ARMA ImArmors.esp
Kapotun ARMA LegendsOfAetherium.esp
Kapotun ARMA LunarGuard.esp
Kapotun ARMA Moonpath.esp
Kapotun ARMA NFF.esp
Kapotun ARMA PracticalPirate.esp
Kapotun ARMA TAWOBA.esp
Kapotun ARMA TBD Bikini.esp
Kapotun ARMA TBDUnique Treasures.esp
Kapotun ARMA Unique Uniques.esp
Kapotun ARMA USMP.esp
Kapotun ARMA USSEP.esp
Kapotun ARMA WetAndCold.esp
Kapotun ARMA Winterhold Restored.esp
Kapotun ARMA Wyrmstooth.esp
Kapotun Vanilla Armor Patch.esp
Kapotun SOS.esp

Incompatible with any Races of Nirn - Kapo'tun SE:
SOS - Kapotun Addon.esp

For Races of Nirn - Kapotun Reborn ≥V2 and SOS use included:
SOS - Kapotun Addon.esp

Update Races of Nirn - Kapotun Reborn ≤V2 to newest version.

Patches for body mods:
Races of Nirn - Kapo'tun SE: [CBBE](https://www.nexusmods.com/skyrimspecialedition/mods/40928), [BH(UNP)](https://www.nexusmods.com/skyrimspecialedition/mods/61999), [Improved White Tiger CBBE](https://www.nexusmods.com/skyrimspecialedition/mods/61999), [TBD (TouchedbyDibella.esp](https://www.nexusmods.com/skyrimspecialedition/mods/77612)) named Kapotun TBD Tail.esp
Races of Nirn - Kapotun Reborn has eberything in archive, no need for standalone patches.
