### ISSUE TITLE
Error messages on man_DaedricShrines.esp

### ISSUE THREAD

**Issue by Larhanya** [loot/skyrimse#2853]
Mandragora's All-in-One Daedric Shrines main plugin (man_DaedricShrines.esp) has messages in LOOT that report the presence of all the individual included plugins as errors. For example:

```yaml
      - type: error
        content: '%1% is included with this mod.'
        subs:
          - >-
            [Daedric Shrines -
            Azura](https://www.nexusmods.com/skyrimspecialedition/mods/66776/)
        condition: active("man_azura.esp")
```

I'm not sure what the purpose of the error messages are, since of course it is an AiO installer. (I do not have the standalone mods installed, only the AiO.)

In case it is important, I'm running LOOT version 0.20.0 (build c2c552ad) with MO2 version 2.4.4 (rev 1df1ea5e) for Skyrim SE 1.6.640.
