### ISSUE TITLE
Load Order per xEdit (Masterlist Update???)

### ISSUE THREAD

**Issue by Thor-M465** [loot/skyrimse#3068]
I'm assuming the masterlist needs to be update with the rules below, but I'm not advance enough of a user to say that with any confidence. I'll let y'all be the judge.

I got the following errors from xedit:
<details>
<summary>xEdit Log</summary>

```
[01:28] ModGroup "Seasonal Landscapes - Unfrozen" is invalid:
[01:28]  - Error: "JKs Skyrim.esp" has a lower load order than "Landscape Fixes for Grass Mods.esp"
[01:28]  - Error: "Seasonal Landscapes - Unfrozen.esp" has a lower load order than "fortdawnguardimmersive.esp"
[01:28]  - Error: "Seasons of Bruma Unfrozen.esp" has a lower load order than "Seasonal Landscapes - Unfrozen - LaWF patch.esp"
[01:28]  - Error: "Unique Border Gates - Fixes.esp" has a lower load order than "Seasons of Bruma Unfrozen.esp"
[01:28]  - Error: "Ryn's Standing Stones.esp" has a lower load order than "Seasonal Landscapes - Unfrozen - JKs Syrim Patch.esp"
[01:28]  - Error: "COTN Addon - Anga's Mill.esp" has a lower load order than "Seasonal Landscapes - Unfrozen - JKs Syrim Patch.esp"
[01:28]  - Error: "Seasonal Landscape Unfrozen - JK's High Hrothgar Patch.esp" has a lower load order than "Seasonal Landscapes - Unfrozen - COTN Anga's Mill.esp"
[01:28]  - Error: "Seasonal Landscapes - Unfrozen - Throat of the World Snow Cap.esp" has a lower load order than "Seasonal Landscape Unfrozen - JK's High Hrothgar Patch.esp"
[01:28] ModGroup "Seasonal Landscapes - Unfrozen - Legacy of the Dragonborn" is invalid:
[01:28]  - Error: "Unique Border Gates - Fixes.esp" has a lower load order than "Seasons of Bruma Unfrozen.esp"
[01:28]  - Error: "Seasonal Landscape Unfrozen - LOTD Patch.esp" has a lower load order than "Seasonal Landscapes - Unfrozen - Bruma - complement.esp"
[01:28] ModGroup "Seasonal Landscapes - Unfrozen - No grass under the ice" is invalid:
[01:28]  - Error: "Seasonal Landscapes - Unfrozen.esp" has a lower load order than "fortdawnguardimmersive.esp"
[01:28]  - Error: "Seasonal Landscapes - Unfrozen - No grass under the ice.esp" has a lower load order than "Seasonal Landscapes - Unfrozen - LaWF patch.esp"
[01:28]  - Error: "Seasonal Landscapes - Unfrozen - JKs Syrim Patch.esp" has a lower load order than "Seasonal Landscapes - Unfrozen - LaWF patch.esp"
[01:28]  - Error: "Seasonal Landscapes - Unfrozen - Ryn's Standing Stones patch.esp" has a lower load order than "Seasonal Landscapes - Unfrozen - LaWF patch.esp"
[01:28] ModGroup "Vigilant - Seasons" is invalid:
[01:28]  - Error: "Seasonal Landscapes - Unfrozen.esp" has a lower load order than "Landscape and Water Fixes - Patch - LFfGM.esp"
[01:28]  - Error: "Seasons_Vigilant.esp" has a lower load order than "StendarrReplacer.esp"
```

</details>

I manually created add Load After rules within LOOT, but it seems to be ignoring these rules. I tried creating a userlist.yaml with the syntax below created by GROK, but no joy either.

<details>
<summary>Userlist.yaml</summary>

```yaml
- name: 'JKs Skyrim.esp'
  after:
    - 'Landscape Fixes for Grass Mods.esp'
- name: 'Seasonal Landscapes - Unfrozen.esp'
  after:
    - 'fortdawnguardimmersive.esp'
    - 'Landscape and Water Fixes - Patch - LFfGM.esp'
- name: 'Seasons of Bruma Unfrozen.esp'
  after:
    - 'Unique Border Gates - Fixes.esp'
- name: 'Seasonal Landscapes - Unfrozen - JKs Syrim Patch.esp'
  after:
    - 'Ryn's Standing Stones.esp'
    - 'COTN Addon - Anga's Mill.esp'
    - 'Seasonal Landscapes - Unfrozen - LaWF patch.esp'
- name: 'Seasonal Landscapes - Unfrozen - COTN Anga's Mill.esp'
  after:
    - 'Seasonal Landscape Unfrozen - JK's High Hrothgar Patch.esp'
- name: 'Seasonal Landscapes - Unfrozen - Throat of the World Snow Cap.esp'
  after:
    - 'Seasonal Landscape Unfrozen - JK's High Hrothgar Patch.esp'
- name: 'Seasonal Landscape Unfrozen - LOTD Patch.esp'
  after:
    - 'Seasonal Landscapes - Unfrozen - Bruma - complement.esp'
- name: 'Seasonal Landscapes - Unfrozen - No grass under the ice.esp'
  after:
    - 'Seasonal Landscapes - Unfrozen - LaWF patch.esp'
- name: 'Seasonal Landscapes - Unfrozen - Ryn's Standing Stones patch.esp'
  after:
    - 'Seasonal Landscapes - Unfrozen - LaWF patch.esp'
- name: 'Seasons_Vigilant.esp'
  after:
    - 'StendarrReplacer.esp' 
```

</details>

**Comment by sibir-ine** [comment]
xEdit ModGroups are for resolving conflicts in xEdit. It looks like those are tied to patches, so there's a good chance those conflicts are resolved by those patches & no further load order adjustments are needed. If you can verify that there are conflicts between any of those mods that aren't resolved through patches & require load order adjustments, we can add the appropriate rules, but, as is, those are a lot of plugins to sift through that may not even necessitate rules in the first place. None of us have the time for that unfortunately.

I'll close this for now, but, if you can verify with xEdit that rules are necessary for any of them (& provide links to the relevant plugins), we'll reopen it. Anything else wouldn't be appropriate for the masterlist, those would have to remain in your userlist.

As for your userlist, is that its entire contents? If so, it all needs to be under a `plugins` node as well, like so:

```yaml
- plugins:
  - name: 'JKs Skyrim.esp'
    after:
      - 'Landscape Fixes for Grass Mods.esp'
  etc...
```
