### ISSUE TITLE
Notes - Mod Testing

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#309]
For keeping track of any notes while testing mods.
Cleaning info will be kept on a separate page.

## Template

```
### [mod link](https://www.nexusmods.com/skyrimspecialedition/mods/)
#### Version
n/a
#### Plugins
plugin.esp`
###### Cleaning

#### Sorting
###### After:
- `pluginB.esp`

###### Before
n/a
#### Compatibility
###### Incompatible
n/a
###### Patches
n/a
#### Other Notes
n/a
```

Post Links
- [Stonecrest City Reborn SE](https://github.com/loot/skyrimse/issues/309#issuecomment-439179654)
- [Vivid Weathers Definitive Edition](https://github.com/loot/skyrimse/issues/309#issuecomment-439594288)
- [Falkreath](https://github.com/loot/skyrimse/issues/309#issuecomment-439633694)
- [Clockwork](https://github.com/loot/skyrimse/issues/309#issuecomment-439635462)

**Comment by CptMcSplody** [comment]
- [x] [Skyrim Project Optimization SE](https://www.nexusmods.com/skyrimspecialedition/mods/14084)
```
  - name: 'Skyrim Project Optimization - Full Version.esm'
    clean:
      - crc: 0x45374C76
        util: 'SSEEdit v3.2.44'
```
### Conflicts
- N/A
- Minor conflict with [USSEP](https://www.nexusmods.com/skyrimspecialedition/mods/266) one placed object is moved slightly. Should be fine before or after.
### Requires
- N/A
### Bash Tags
- N/A

**Comment by CptMcSplody** [comment]
LSFX-SSE-Audiosettings.esp

**Comment by CptMcSplody** [comment]
- [ ] [Improved Hearthfire Lighting SE](https://www.nexusmods.com/skyrimspecialedition/mods/721)

### Conflicts
Load before 

- Lighting mods
- EmbersHD.esp
- EnhancedLightsandFX.esp
- ELFX - Exteriors.esp
- ELFXEnhancer.esp

### Requires
- N/A
### Bash Tags
- N/A

**Comment by CptMcSplody** [comment]
Quick Auto Clean 
```

 - name: 'Update.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xE95F6A98
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        itm: 256
        udr: 91
        nav: 2
    dirty:
      - <<: *dirtyPlugin
        crc: 0xA208CF56
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        nav: 2

  - name: 'Dawnguard.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xCFBEE94B
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        itm: 724
        udr: 82
        nav: 57
    dirty:
      - <<: *dirtyPlugin
        crc: 0xC1E55A15
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        itm: 3
        nav: 57
    dirty:
      - <<: *dirtyPlugin
        crc: 0xE81631D4
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        nav: 57

Manual clean
CELL 00016BCF: Remove XEZN subrecord referring to RiftenRatwayZone [ECZN:0009FBB9]
CELL 0001FA4C: Wild edit. Remove this record. It's a testing cell.
CELL 0006C3B6: Wild edit. Remove this record. It's a testing cell.

  - name: 'Dawnguard.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xF71A6B33
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        itm: 4
        nav: 57
    dirty:
      - <<: *dirtyPlugin
        crc: 0x8DB8C71E
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        nav: 57
[00:00] Quick Clean mode finished.
[00:45] Background Loader: finished

  - name: 'HearthFires.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0x20B605D1
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        itm: 211
        udr: 11
        nav: 5
    dirty:
      - <<: *dirtyPlugin
        crc: 0xD5A0679C
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        nav: 5

  - name: 'Dragonborn.esm'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xA1BF01BD
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        itm: 81
        udr: 8
        nav: 1
    dirty:
      - <<: *dirtyPlugin
        crc: 0x9E981BAE
        util: 'SSEEdit v3.2.67 EXPERIMENTAL'
        nav: 1
```

**Comment by CptMcSplody** [comment]
### Archived 
Checked if added to Master list. Strikeout if addition is not required.
~- [ ] [ApachiiSkyHair SSE](https://www.nexusmods.com/skyrimspecialedition/mods/2014)~
```
  - name: 'ApachiiHair.esm'
    clean:
      - crc: 0x2949DB49 # v1.6
        util: 'SSEEdit v3.2.44'

  - name: 'ApachiiHairFemales.esm'
    clean:
      - crc: 0xE7A2F17C # version v1.5
        util: 'SSEEdit v3.2.44'
  - name: 'ApachiiHairMales.esm'
    clean:
      - crc: 0x3781AD61 # v1.2
        util: 'SSEEdit v3.2.44'
```
### Conflicts
- N/A
- All three `.esm' can be loaded before or after [USSEP](https://www.nexusmods.com/skyrimspecialedition/mods/266).
---
- [x] [Skyrim Project Optimization SE](https://www.nexusmods.com/skyrimspecialedition/mods/14084)
```
  - name: 'Skyrim Project Optimization - Full Version.esm'
    clean:
      - crc: 0x45374C76 # v1.3
        util: 'SSEEdit v3.2.44'
  - name: 'Skyrim Project Optimization - Full Version.esp'
    clean:
      - crc: 0x137A03B3 # v1.3
        util: 'SSEEdit v3.2.44 EXTRA EXPERIMENTAL'
```
### Conflicts
- Only use one at a time.
- Minor conflict with [USSEP](https://www.nexusmods.com/skyrimspecialedition/mods/266) one placed object is moved slightly. Should be fine before or after.
---
- [x] [Lucidity Sound FX SSE](https://www.nexusmods.com/skyrimspecialedition/mods/1841)
```
  - name: 'LSFX-SSE-Audiosettings.esp'
    clean:
      - crc: 0x8018F548
        util: 'SSEEdit v3.2.44 EXTRA EXPERIMENTAL'
```
### Conflicts
Load before 
  - SSE High Quality Music.esp
  - illy's HQ Fire Audio.esp
  - Audio Overhaul Skyrim.esp
  - Immersive Sounds - Compendium.esp
  - Audio Overhaul Skyrim - Immersive Sounds Patch.esp
---
- [x] [Improved Hearthfire Lighting SE](https://www.nexusmods.com/skyrimspecialedition/mods/721)

### Conflicts
Load before 

- Lighting mods
- EmbersHD.esp
- EnhancedLightsandFX.esp
- ELFX - Exteriors.esp
- ELFXEnhancer.esp
---
- [x] [The Notice Board - Better Solstheim Quests](https://www.nexusmods.com/skyrimspecialedition/mods/15829)

### Conflicts
Load after

- Alternate Start - Live Another Life.esp
- Immersive Wenches.esp
---
- [x] [Enlightened College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/8710)

### Conflicts
Load before
- CollegeOfWinterholdImmersive.esp

**Comment by MacSplody** [comment]
## [Stonecrest City Reborn SE](https://www.nexusmods.com/skyrimspecialedition/mods/9303)
### Plugins
`Stonecrest.esp`
###### Cleaning info
https://github.com/loot/skyrimse/issues/467#issuecomment-439169422
### Sorting
###### After:
- `Stonecrest - Verdant, Patch.esp`
- `Verdant - A Skyrim Grass Plugin SSE Version.esp`
###### Before:
n/a
### Compatibility
###### Incompatible
n/a
###### Patches
`Stonecrest - Verdant, Patch.esp`
### Other notes
n/a

**Comment by MacSplody** [comment]
## [Vivid Weathers Definitive Edition](https://www.nexusmods.com/skyrimspecialedition/mods/2187/)
### Plugins
`Vivid WeathersSE.esp`
### Cleaning info
n/a
### Sorting
###### After:
n/a
###### Before:
 [A Quality World Map](https://www.nexusmods.com/skyrimspecialedition/mods/5804)
`IcePenguinWorldMap.esp`
### Compatibility
###### Incompatible
- Patch required [Wet & Cold](https://www.nexusmods.com/skyrimspecialedition/mods/644) `WetandCold.esp`

###### Patches
n/a
### Other notes
n/a

**Comment by MacSplody** [comment]
## [Falkreath](https://www.nexusmods.com/skyrimspecialedition/mods/21266)
### Plugin
`Falkreath.esp`
###### Cleaning info
https://github.com/loot/skyrimse/issues/467#issuecomment-439631051
### Sorting
###### After
[Immersive Citizens - AI Overhaul SE](https://www.nexusmods.com/skyrimspecialedition/mods/173) `Immersive Citizens - AI Overhaul.esp` 
- ICAIO Alters AI Packages used by NPCs with a Quest via Alias referencing.
![image](https://user-images.githubusercontent.com/1944639/48663628-c79ad680-ea8a-11e8-9f26-11194ae7026a.png)
- Note that `062117E1` `AI for Falkreath citizens` references the NPC `Kust`.
![image](https://user-images.githubusercontent.com/1944639/48663885-77257800-ea8e-11e8-9c4d-e1ac71db87c8.png)
- This sleep package places `Kust's` bed in the falkreath hall of the dead.
![image](https://user-images.githubusercontent.com/1944639/48663944-50b40c80-ea8f-11e8-86c3-4a6531e80df1.png)
- Falkreath adds a new Home for the NPC `Kust`.
![image](https://user-images.githubusercontent.com/1944639/48663725-4a706100-ea8c-11e8-86fc-2c44bb9c5171.png)
- It uses an AI package to make sure the NPC `Kust` uses this new house.
![image](https://user-images.githubusercontent.com/1944639/48663668-53acfe00-ea8b-11e8-8c49-be7ea3829269.png)
###### After
[Clockwork (SSE)](https://www.nexusmods.com/skyrimspecialedition/mods/4155) `Clockwork.esp` 
- Nav mesh conflict in `FalkreathExterior01`.
![image](https://user-images.githubusercontent.com/1944639/48663188-4d675380-ea84-11e8-978a-f0ba1da8345d.png)
###### Before
n\a
### Compatibility
###### Incompatible
n\a
###### Patches
n\a
### Other Notes
n\a

**Comment by MacSplody** [comment]
## [Clockwork (SSE)](https://www.nexusmods.com/skyrimspecialedition/mods/4155)
### Plugin(s)
`Clockwork.esp`
###### Cleaning info
https://github.com/loot/skyrimse/issues/467#issuecomment-439630745
### Sorting
###### after:
[Simple Raven Rock Expansion](https://www.nexusmods.com/skyrimspecialedition/mods/640) `Raven Rock.esp`

###### Before
n/a
### Compatibility
[Immersive Citizens - AI Overhaul SE](https://www.nexusmods.com/skyrimspecialedition/mods/173) `Immersive Citizens - AI Overhaul.esp`
**Requires Patch**
- Nav mesh conflict in `WindhelmExterior02 NAVM 000798D8`.![image](https://user-images.githubusercontent.com/1944639/48664039-ac32ca00-ea90-11e8-926a-da45602dabdd.png)

###### Patches
[Simple Raven Rock Expansion](https://www.nexusmods.com/skyrimspecialedition/mods/640)
`Raven Rock - Clockwork Patch.esp`

### Other Notes
n/a

**Comment by CptMcSplody** [comment]
[WARZONES - Civil Unrest for SSE](https://www.nexusmods.com/skyrimspecialedition/mods/2360)

```yaml
  - name: 'WARZONES - SSE - Civil Unrest.esp'
    clean:
      - crc: 0xD755C4B7
        util: '[SSEEdit v3.3.4 BETA](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
```

**Comment by MacSplody** [comment]
## [WARZONES - Civil Unrest for SSE](https://www.nexusmods.com/skyrimspecialedition/mods/2360)
### Plugins
`WARZONES - SSE - Civil Unrest.esp`
###### Cleaning info
https://github.com/loot/skyrimse/issues/467#issuecomment-439770960
### Sorting
###### After:
n/a
###### Before
[`Cutting Room Floor.esp`](https://www.nexusmods.com/skyrimspecialedition/mods/276)
Reverts Changes to:
Location
`00018C8C`
Persistent DLC Regions
`00000D74`
`XCWT - Water`
`00009147`
`XLCN - Location` for:
`00009367`, `00009387`, `00009388`, `00009389`, `00009617`

![image](https://user-images.githubusercontent.com/1944639/48686941-c5ce3180-ebb6-11e8-869b-fab267974c90.png)

### Compatibility
###### Incompatible
n/a
###### Patches
n/a
### Other Notes
n/a

**Comment by MacSplody** [comment]
[No Snow Under The Roof](https://www.nexusmods.com/skyrimspecialedition/mods/518)

Taken from #531 by @Infernio 
Wild Edits
> 1. Load only `Prometheus_No_snow_Under_the_roof.esp`
> 2. Open record `00104217`
> 3. Note the `Object Bounds/NAM0` and `Object Bounds/NAM9` changes
> 
> I don't see how these could be intentional.
> 
> Some info on object bound edits can be found [here](https://forum.step-project.com/topic/11024-worldspace-edits-nam9-and-nam0-object-bounds/), but the TL;DR on them is that they can't be corrected by patching and have to be manually cleaned. The fix is to simply drag and drop the values from `Skyrim.esm`.

**Comment by MacSplody** [comment]
## [Unlimited Bookshelves](https://www.nexusmods.com/skyrimspecialedition/mods/2885)
### Plugins
`UnlimitedBookshelves.esp`
###### Cleaning info
n/a
### Sorting
###### After:
- `Unofficial Skyrim Special Edition Patch.esp`
###### Before
n/a
### Compatibility
Taken from Unlimited Bookshelves description page.
> This mod will be compatible with any mod that doesn't change the bookshelf container script. Any bookshelves placed by mods should work automatically as long as they are set up the same as in vanilla.
If you have mod added items that are stacking up and not displaying properly, please politely request to the author of that mod that they include correct object bounds for their new items, books, weapons and armors. This also helps them interact properly with items when drop into the world so it is not just a function purely for this mod.
Do not use this mod along side any other that edits the primary bookshelf activators or script in a different manner. 
###### Incompatible
n/a
###### Patches

Patching Notes
`Update.esm` 
- 42 armor records, Survival keywords.

`Cutting Room Floor.esp`
- 1 armor record, 2 Scroll records.

### Other Notes
An xEdit patcher script is available. [Unlimited Bookshelves patch generator](https://www.nexusmods.com/skyrimspecialedition/mods/19160)

**Comment by MacSplody** [comment]
### [Tel Nalta SE - Telvanni Home](https://www.nexusmods.com/skyrimspecialedition/mods/18680)
#### Version
1.00
#### Plugins
`Tel_Nalta.esp`
###### Cleaning
```yaml
  - name: 'Tel_Nalta.esp'
    dirty:
      # version: 1.00
      - <<: *quickClean
        crc: 0xDB9E70DA
        util: '[SSEEdit v4.0.1](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 6
    clean:
      # version: 1.00
      - crc: 0x67A6845B
        util: 'SSEEdit v4.0.1'
```
#### Sorting
###### After:
n/a
###### Before
n/a
#### Compatibility
n/a
##### Patches
n/a
###### Requires Patch - none available
- `Cutting Room Floor.esp`
#### Other Notes
- `Cutting Room Floor.esp`

![image](https://user-images.githubusercontent.com/1944639/51201393-d91a2680-18f3-11e9-8b0d-cfac0c261a69.png)


<details>
  <summary>Click to view picture</summary>
  ---

![image](https://user-images.githubusercontent.com/1944639/51201493-20081c00-18f4-11e9-8fcb-e0407c0359fa.png)

  ---
</details>
`040274A5` DLC2ExpSpiderPackmuleScroll


<details>
  <summary>Click to view picture</summary>
  ---

![image](https://user-images.githubusercontent.com/1944639/51201552-462dbc00-18f4-11e9-93b4-aa00070f678c.png)

  ---
</details>
`040274A0` DLC2ExpSpiderPackmuleFriendCUT


<details>
  <summary>Click to view picture</summary>
  ---

![image](https://user-images.githubusercontent.com/1944639/51201705-aa508000-18f4-11e9-879d-6b3967712e24.png)

  ---
</details>
`04027495` DLC2ExpSpiderGlowingFriend


<details>
  <summary>Click to view picture</summary>
  ---

![image](https://user-images.githubusercontent.com/1944639/51201767-d79d2e00-18f4-11e9-875e-8a732855feaa.png)

  ---
</details>
`0401DA1B` DLC2ExpSpiderCraftingBooksListSTATIC


<details>
  <summary>Click to view picture</summary>
  ---

![image](https://user-images.githubusercontent.com/1944639/51201845-0f0bda80-18f5-11e9-92e5-d0de4afaabc4.png)

  ---
</details>
`04017061` DLC2ExpSpiderCraftingResultsList


<details>
  <summary>Click to view picture</summary>
  ---

![image](https://user-images.githubusercontent.com/1944639/51201888-32368a00-18f5-11e9-978d-07fc1d82917e.png)

  ---
</details>
`04017060` DLC2ExpSpiderCraftingRecipesList
