### ISSUE TITLE
Refactor - Messages

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#460]
##### `common` Patch Messages
  - [x] **hasPluginPatch**
```yaml
  - &hasPluginPatch
    type: warn
    content:
      - lang: en
        text: "You seem to be using %1%, but you haven't enabled the patch for this plugin: %2%"
```
```yaml
    msg:
      - <<: *hasPluginPatch
        subs:
          - '[True Storms SE](https://www.nexusmods.com/skyrimspecialedition/mods/2472/)'
          - '[NAT - TrueStorms Merged Compatibility SSE](https://www.nexusmods.com/skyrimspecialedition/mods/15025/)'
        condition: 'active("TrueStormsSE.esp") and not active("NAT_TS_Patch_.*\.esp")'
```
Count: 86

  - [x] **hasPatchIncluded**
```yaml
  - &hasPatchIncluded
    type: warn
    content:
      - lang: en
        text: "A patch is included with the %2% installer, please make sure you have installed the %1% patch and have it activated."
```
```yaml
    msg:
      - <<: *hasPatchIncluded
        subs:
          - '[Climates Of Tamriel Special Edition](https://www.nexusmods.com/skyrimspecialedition/mods/2237/)'
          - '[Sounds of Skyrim Complete SE](https://www.nexusmods.com/skyrimspecialedition/mods/8286/)'
        condition: 'active("ClimatesOfTamriel.esm") and not active("SoS_CoT_Patch.esp")'
```
Count: 141

##### Other Patch Messages
  - [x] **Third party patch**
```yaml
    msg:
      - type: warn
        content: 'Third party patch available for %1% here: %2%'
        subs:
          - 'Beyond Skyrim: Bruma'
          - '[ Joy of Perspective Compatibility Patches ](https://www.nexusmods.com/skyrimspecialedition/mods/20009)'
        condition: 'active("BSHeartland.esm") and not active("Jop - BrumaPatch.esp")'
```
Count: 20

```yaml
      - type: warn
        content: 'Third party patch available for both %1% and %2% here: %3%'
        subs:
          - ' `Zim''s Immersive Artifacts` '
          - ' `MorrowLoot Ultimate` '
          - '[ Scoped Bows Compatibility Kit - SBCK ](https://www.nexusmods.com/skyrimspecialedition/mods/19495)'
        condition: 'active("ZIA_Complete Pack_V4.esp") and active("MLU.esp") and not file("ScopedBows_MLU_ZIA Patch.esp")'
```
Count: 1

> both %1% and %2% here: %3%'

can be replaced with:

>for %1% here: %2%'

both `x` and `y` can be passed in the sub.

 - [x] **recommendX**
```yaml
    msg:
      - type: warn
        content: 'Update Patch available: %1%'
        subs: [ '[Unofficial Moonpath to Elsweyr Patch](https://www.nexusmods.com/skyrimspecialedition/mods/15882/)' ]
        condition: 'active("moonpath.esp") and checksum("moonpath.esp", 18577F3E) and not active("JRMoonpathtoElsweyrPatch.esp")'

    msg:
      - type: warn
        content: 'Update Patch available: %1%'
        subs: [ '[No Snow Under the roof - Bug fixes](https://www.nexusmods.com/skyrimspecialedition/mods/15064/)' ]
        condition: 'active("Prometheus_No_snow_Under_the_roof.esp") and not active("NSUTR_bugfixes.esp")'
```

- [x] **Patcher Available**
```yaml
    msg:
      - type: say
        content: '%1% patcher script available here: %2%'
        subs:
          - '[xEdit](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
          - '[ Auto Patching - VIS - JOP ](https://www.nexusmods.com/skyrimspecialedition/mods/10959)'
        condition: 'active("Joy of Perspective.esp")'
```

- [x] **useXinstead**
```yaml
    msg:
      - type: warn
        content: 'Use the Winterhold Restored version of Jobasha''s Books SE instead: %1%'
        subs:
          - '[Jobasha''s Books and WinterHold Restored Patch] (https://www.nexusmods.com/skyrimspecialedition/mods/13285/)'
        condition: 'active("sm_jobasha_bookshop.esp")'
```
```yaml
    msg:
      - type: info
        content: 'Shezrie''s Old Hroldan Town is only compatible with Distinct Interiors - Modular version without Inns.'
        condition: 'active("Distinct Interiors.esp")'
```
count: 3

  - [x] **Compatibility Notes**
```yaml
    msg:
      - type: say
        content:
          - lang: en
            text: '[Sacrosanct Compatibility Notes](https://www.nexusmods.com/skyrimspecialedition/articles/54/?)'
          - lang: de
            text: '[Sacrosanct-Kompatibilitätsnotizen](https://www.nexusmods.com/skyrimspecialedition/articles/54/?)'

    msg:
      - type: say
        content:
          - lang: en
            text: '[WACCF Compatibility Notes & Patches](https://forums.nexusmods.com/index.php?/topic/6871717-waccf-compatibility/?p=62448162)'
          - lang: de
            text: '[WACCF-Kompatibilitätsnotizen & Patches](https://forums.nexusmods.com/index.php?/topic/6871717-waccf-compatibility/?p=62448162)'
```
count: 12

  - [x] **Recommend Deactivate**
```yaml
    msg:
      - type: warn
        content: 'Bijin AIO SSE recommends that you deactivate this ESP.'
        condition: 'active("Bijin Wives.esp") and active("BijinAIO_SSE-3.1.1-SV.esp")'
```
Count: 8

  - [ ] **deactivate and/or uninstall**
```yaml
    msg:
      - type: say
        content: 'After Character Creation you should deactivate and/or uninstall.'
        condition: 'active("AsharaSkyrimCharacterPresetsReplacer.esp")'
```
Count: 6

- [x] **Replace with dedicated meta data**
```yaml
    msg:
      - type: warn
        content: 'ELFX - NoPlayerHomes module required.'
        condition: 'active("EnhancedLightsandFX.esp") and not active("ELFX - NoPlayerHomes.esp")'
```
```yaml
    msg:
      - type: error
        content: 'Lock Overhaul - Ordinator Version is required.'
        condition: 'active("Ordinator - Perks of Skyrim.esp") and not checksum("Lock_Overhaul.esp", CD2D19F5)'
```
- [x] **Includes X**
```
    msg:
      - type: say
        content: 'Run For Your Lives SE now includes the old mod When Vampires Attack. You can uninstall When Vampires Attack.'
        condition: 'active("When Vampires Attack.esp")'
```
```yaml
    msg:
      - type: warn
        content: '%1% is already included in this mod.'
        subs:
          - '`Realistic High Altitude Treeline`'
        condition: 'active("Realistic Treeline.esp")'
```
