### ISSUE TITLE
Sort UHDAP before USSEP

### ISSUE THREAD

**Issue by Infernio** [loot/skyrimse#470]
[Unofficial High Definition Audio Project (UHDAP)](https://www.nexusmods.com/skyrimspecialedition/mods/18115) must be loaded before USSEP, so that USSEP's voice line fixes can take precedence. It looks like this was broken in d68c0fdbbce4a232961077cb59e04079b533fbb9, when USSEP and UHDAP both got the Fixes & Resources group assigned.

From the mod author's page:
```
The load order of the .esp files MUST be as follows in order to avoid conflicts with other mods:

Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
UHDAP - MusicHQ.esp OR UHDAP - MusicUHQ.esp
UHDAP - en0.esp // replace en0 as necessary with respective language
UHDAP - enX.esp // replace X with the rest of the language .esp
... // Any other mods that the authors state should be above USSEP
Unofficial Skyrim Special Edition Patch.esp
... // Rest of your load order
```

**Comment by MacSplody** [comment]
```yaml
  - name: 'Unofficial Skyrim Special Edition Patch.esp'
    group: *fixesGroup
    after:
      - 'Lanterns Of Skyrim - All In One - Main.esm'
      - 'RSkyrimChildren.esm'
      - 'UHDAP - de0.esp'
      - 'UHDAP - de1.esp'
      - 'UHDAP - de2.esp'
      - 'UHDAP - de3.esp'
      - 'UHDAP - de4.esp'
      - 'UHDAP - en0.esp'
      - 'UHDAP - en1.esp'
      - 'UHDAP - es0.esp'
      - 'UHDAP - es1.esp'
      - 'UHDAP - es2.esp'
      - 'UHDAP - es3.esp'
      - 'UHDAP - es4.esp'
      - 'UHDAP - fr0.esp'
      - 'UHDAP - fr1.esp'
      - 'UHDAP - fr2.esp'
      - 'UHDAP - fr3.esp'
      - 'UHDAP - fr4.esp'
      - 'UHDAP - it0.esp'
      - 'UHDAP - it1.esp'
      - 'UHDAP - it2.esp'
      - 'UHDAP - it3.esp'
      - 'UHDAP - it4.esp'
      - 'UHDAP - pl0.esp'
      - 'UHDAP - pl1.esp'
      - 'UHDAP - pl2.esp'
      - 'UHDAP - pl3.esp'
      - 'UHDAP - pl4.esp'
      - 'UHDAP - ru0.esp'
      - 'UHDAP - ru1.esp'
      - 'UHDAP - ru2.esp'
      - 'UHDAP - ru3.esp'
      - 'UHDAP - ru4.esp'
      - 'UHDAP - MusicHQ.esp'
      - 'UHDAP - MusicUHQ1.esp'
      - 'UHDAP - MusicUHQ2.esp'
```
verses changing `UHDAP` group from `fixesgroup` to `ccgroup`
```yaml
  - name: 'UHDAP -.*\.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/18115/'
        name: 'Unofficial High Definition Audio Project on Nexus Mods'
    group: *ccGroup
  - name: 'UHDAP - MusicHQ.esp'
    inc:
      - 'UHDAP - MusicUHQ1.esp'
      - 'UHDAP - MusicUHQ2.esp'
```
