### ISSUE TITLE
Add/Update Winterhold Mods

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#517]
- [x] [Finding Velehk Sain](https://www.nexusmods.com/skyrimspecialedition/mods/19815)
- [x] [Obscure's College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/20514)
- [x] [Winterhold Restored](https://www.nexusmods.com/skyrimspecialedition/mods/12811)
- [x] [Improved College Entry](https://www.nexusmods.com/skyrimspecialedition/mods/22184)
- [x] [Misc. College of Winterhold Tweaks](https://www.nexusmods.com/skyrimspecialedition/mods/22653)

**Comment by MacSplody** [comment]
## [Finding Velehk Sain](https://www.nexusmods.com/skyrimspecialedition/mods/19815)

### Plugins
`Finding_VelehkSain` Standalone
`Finding_VelehkSain_MAQF` Complete
#### Cleaning info
https://github.com/loot/skyrimse/issues/467#issuecomment-446517777
### Compatibility
#### Sorting
###### After:
[Apepi's Better College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/4221)
[Immersive College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/17004)
[Immersive Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/16788)
[Magical College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/1539)
[Obscure's College of Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/20514)
[Weapons Armor Clothing and Clutter Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/18994)

###### Before
Load this mod before any mod that does global changes such as lighting, sound, music, or water.

#### Incompatible
n\a
#### Patches
n\a
### Sources/Other Notes
Mod description page Compatibility and Conflicts section.

**Comment by SomethingObscure** [comment]
This is an example of a "get all of the shouts early" mod which will cause problems with OCW:  https://www.nexusmods.com/skyrim/mods/64774.  I am not aware of any others, but I suspect they may be using names I just haven't thought of to search for.

**Comment by SomethingObscure** [comment]
I've determined that OCW should be loaded after Enlightened College of Winterhold﻿, due to it missing some USSEP fixes.

**Comment by MacSplody** [comment]
@SomethingObscure Updated in #523

**Comment by SomethingObscure** [comment]
It may go without saying, but the _SoS_ELFX+Hardcore_Patch.esp_ should be loaded before any of my ELFX or SoS patches.

**Comment by MacSplody** [comment]
I'll have to test them to see how default sorting is placing them, will add rules if needed.

**Comment by SomethingObscure** [comment]
Hello Captain McSplody!  Would you please add rules for the following mods?  OCW should be loaded after them.

Relighting Skyrim: https://www.nexusmods.com/skyrimspecialedition/mods/8586

Thank you!  I am working on patches for these, but even with those patches the same rule will still apply.

Edit: I had listed Luminosity and Enhanced Lighting for ENB, but I see that they're "Late Loaders", so I'll just have to make sure that the patch includes everything needed to make sure the two mods play nicely together and not rely on OCW loading later than them.

**Comment by MacSplody** [comment]
@SomethingObscure Okay Relighting one is done, what about [Realistic Lighting Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/844)?

From what I can see in xEdit, it looks fine if RLO is after OCW.

**Comment by SomethingObscure** [comment]
RLO and OCW surprisingly don't seem to have any conflicts!

**Comment by MacSplody** [comment]
Yeah, either way looks fine, doesn't need rules I guess.

**Comment by SomethingObscure** [comment]
I found another one.  Mage College Dorm Doors is not compatible.  OCW already includes doors and chair ownership.
https://www.nexusmods.com/skyrimspecialedition/mods/16082

Edit:  Also incompatible with College Grounds: https://www.nexusmods.com/skyrimspecialedition/mods/2294
OCW Should be loaded after The Midden - Expanded Lite (conflicts a bit, can be fixed): https://www.nexusmods.com/skyrimspecialedition/mods/2219

Edit 2:  Also incompatible with College Guards: https://www.nexusmods.com/skyrimspecialedition/mods/11538

**Comment by MacSplody** [comment]
@SomethingObscure Okay added those 4 rules

**Comment by SomethingObscure** [comment]
Thanks, Captain!  As per a player's inquiry, Konahriks Accoutrements has no conflicts, but should be loaded before OCW.  https://www.nexusmods.com/skyrimspecialedition/mods/22206

**Comment by MacSplody** [comment]
Okay I'll leave this for future reference on that rule.

![image](https://user-images.githubusercontent.com/1944639/50552706-fcf13180-0c90-11e9-8470-56041984f4a5.png)

**Comment by SomethingObscure** [comment]
I've noticed that an ITM record in Immersive Music.esp can cause glitches with OCW.  LOOT already recommends cleaning it, but setting OCW to load after it would help people out.  Thanks, Cpt.

**Comment by MacSplody** [comment]
@SomethingObscure I've set it to always load after for now, as there are other conflicts.
Could you have a look at compatibility with [THE PEOPLE OF SKYRIM 2](https://www.nexusmods.com/skyrimspecialedition/mods/22392) and your mods?

**Comment by SomethingObscure** [comment]
I am seeing a lot of edits to the Winterhold exterior cell and surroundings, but I do not understand the author's intention behind them.  (And their QA says they do not edit Winterhold.)  I think I need to contact the author about this to see if they either want to clean it up or if I should make a patch.  Thanks for bringing it to my attention!

**Comment by SomethingObscure** [comment]
I just spoke with Nesbit.  TPoS2 will soon be updated to remove the Winterhold edits, but to be safe we agreed that OCW should be sorted after it.  There's no conflict with any of my other mods.

**Comment by MacSplody** [comment]
@SomethingObscure Okay, thanks.

**Comment by SomethingObscure** [comment]
@CptMcSplody 
Nesbit contacted me again concerning COW and TPoS2.  He says that he's having trouble with LOOT with the sorting rules as they are.  This is the text of his message:  https://pastebin.com/d0accrTb

I haven't gotten a chance to look at the patch he made yet, but I wanted to keep you up to date.

**Comment by MacSplody** [comment]
@SomethingObscure It seems fine in the latest version of the Full version plus the patch.

![image](https://user-images.githubusercontent.com/1944639/56865651-5c094d80-69c8-11e9-8b5c-eb7de6466fb8.png)

Load Order:
`OCW_Obscure's_CollegeofWinterhold.esp`
`tpos_complete02_RTCWG.esp`
`tpos_Obscures_CollegeofWinterholdPatch_Full.esp`

`OCW_Obscure's_CollegeofWinterhold.esp` already sorts after the partial version `thepeopleofskyrim.esp` in case you're wondering.

**Comment by SomethingObscure** [comment]
Hi Cpt.  I've updated Finding Velehk Sain to better manage its conflicts with OCW.  It should now be loaded first, with OCW after it.

**Comment by MacSplody** [comment]
@SomethingObscure Yeah I can change that, it's not without issues though.
I'll have to keep the sorting for the old versions, just in case it affects anyones setup.
I can use checksums like below to check versions, but those aren't future proof.

```yaml
  - name: 'Finding_VelehkSain.esp'
    after:
      - name: 'OCW_Obscure''s_CollegeofWinterhold.esp'
        condition: 'not checksum("Finding_VelehkSain.esp", 63CC1662) and not checksum("Finding_VelehkSain.esp", 596355B3)'
  - name: 'Finding_VelehkSain_MAQF.esp'
    after:
      - name: 'OCW_Obscure''s_CollegeofWinterhold.esp'
        condition: 'not checksum("Finding_VelehkSain_MAQF.esp", 622EFFB6) and not checksum("Finding_VelehkSain_MAQF.esp", 4714F2F9)'
```
```yaml
  - name: 'OCW_Obscure''s_CollegeofWinterhold.esp'
    after:
      - name: 'Finding_VelehkSain.esp'
        condition: 'checksum("Finding_VelehkSain.esp", 63CC1662) or checksum("Finding_VelehkSain.esp", 596355B3)'
      - name: 'Finding_VelehkSain_MAQF.esp'
        condition: 'checksum("Finding_VelehkSain_MAQF.esp", 622EFFB6) or checksum("Finding_VelehkSain_MAQF.esp", 4714F2F9)'
```
So the easier solution is to add a version to the plugins SNAM - Description. 
LOOT can check for version info listed in a plugins description.

![image](https://user-images.githubusercontent.com/1944639/59147148-e5606680-89ef-11e9-810a-0c9381c9eb8e.png)

![image](https://user-images.githubusercontent.com/1944639/59146931-61f14600-89ec-11e9-8d5e-2c594fa20640.png)

```yaml
  - name: 'OCW_Obscure''s_CollegeofWinterhold.esp'
    after:
      - name: 'Finding_VelehkSain.esp'
        condition: 'version("Finding_VelehkSain.esp", "1.0.7", >=)'
      - name: 'Finding_VelehkSain_MAQF.esp'
        condition: 'version("Finding_VelehkSain_MAQF.esp", "1.0.7", >=)'
```
```yaml
  - name: 'Finding_VelehkSain.esp'
    after:
      - name: 'OCW_Obscure''s_CollegeofWinterhold.esp'
        condition: 'version("Finding_VelehkSain.esp", "1.0.7", <)'
  - name: 'Finding_VelehkSain_MAQF.esp'
    after:
      - name: 'OCW_Obscure''s_CollegeofWinterhold.esp'
        condition: 'version("Finding_VelehkSain_MAQF.esp", "1.0.7", <)'
```
