### ISSUE TITLE
Translations for messages

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#646]
If the language you want to translate for isn't listed, see [this article](https://github.com/loot/loot/blob/master/CONTRIBUTING.md#translating-loot) to add support for your language to LOOT.
If it is, feel free to check if the localization for your language is up-to-date anyway.

While pull requests are appreciated, you can simply leave a comment with your translations.
Any contribution is always appreciated.

**NOTE**
_Actual translations only, don't just use google translate._

---

**Overall progress**
  - [x] Bulgarian (bg) 🏆
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de) 🏆
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja) 🏆
  - [ ] Korean (ko)
  - [ ] Polish (pl)
  - [ ] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR) 🏆
  - [ ] Russian (ru)
  - [ ] Swedish (sv)
  - [ ] Simplified Chinese (zh_CN)

---

### _common_

**&alreadyInX**

`'Delete. Already included in %1%.'`

**&alreadyInOrFixedByX**

`'Delete. Already included or otherwise fixed in %1%.'`

**&alsoUseX**

`'It''s highly recommended that you also use %1%.'`

**&compatIssuesWithX**

`This plugin has compatibility issues with %1%. For more information, read this mods compatibility notes.`

**&compatNotes**

`'It is recommended that you read this mod''s [Compatibility Notes](%1%).'`

**&corrupt**

`'This file is corrupt and should not be used.'`

**&deletePlugin**

`'When using **%1%**, it''s recommended that you deactivate or delete this ESP file but keep the resources (e.g. meshes, textures) installed with this mod.'`

**&includesX**

`'%1% is included with this mod.'`

**&missingRequirementXforY**

`'It appears you have installed **%2%**, but some of its requirements seem to be missing. Please ensure you have correctly installed **%1%**.'`

**&missingRequirementXforPlugin**

`'Some of this plugins requirements seem to be missing. Please ensure you have correctly installed **%1%**.'`

**&obsolete**

`'Obsolete. Update to the latest version. %1%'`

**&optional**

`'This plugin is optional.'`

**&patch3rdParty**

`'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A third party patch is available here: %2%'`

**&patchIncluded**

`'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is included with this plugin''s installer.'`

**&patchProvided**

`'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin''s mod page.'`

**&patchUnavailable**

`'A patch is required to make this mod fully compatible with %1%. None is currently available for download.'`

**&patchUpdateAvailable**

`'Update Patch available: %1%'`

**&renameXtoY**

`'You need to rename %1% to %2% or this mod won''t work.'`

**&requiresMCM_X**

`'A **Mod Configuration Menu** is required for this mod to be fully functional. An **MCM** can be added by installing %1%.'`

**&requiresX**

`'Requires: %1%'`

**&runAnimFramework**

`'It appears you have **%1%** installed. Remember to run **%2%** every time you have installed or uninstalled %3%, or a %3%-based mod.'`

**&semiCompatible**

`'%1% is not fully compatible with this mod. %2%'`

**&sortMasters**

`'Plugin''s Masters require sorting.'`

**&useBashTweakInstead**

`'A Bashed Patch tweak can be used instead of this plugin. %1%'`

**&useInstead**

`'Use %1% instead.'`

**&useOnlyOneX**

`'Use only one %1%.'`

**&useVersion**

`'Use %1% version.'`

**&versionOldX**

`'It appears you do not have the latest version of %1%. Some mods may require functionality added in the latest version of %1% to work.'`

**&versionUpToDateX**

`'Your %1% is up-to-date.'`

**&versionXIncY**

`'Your installed version of %1% is not compatible with your version of %2%.'`

**&wildEdits**

`'This plugin contains wild edits beyond ITM and UDR records and deleted navmeshes and may require additional manual cleaning to not interfere with other mods. %1%'`

**&quickClean**

`'A guide to cleaning plugins using xEdit can be found [here](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#ThreeEasyStepstocleanMods).'`

**&reqManualFix**

`'It is strongly recommended not to use mods that contain **Deleted navmeshes** as they''re known to cause crashes. **Deleted navmeshes** must be corrected manually(A complex process that should be done by the mod author). More information on **Deleted navmeshes** is provided [here](https://www.creationkit.com/index.php?title=Fixing_Navmesh_Deletion_Tutorial).'`

---

### _globals_

**Creation Club plugins**

`'This version of LOOT has inferior handling of Creation Club plugins. Support for these are therefore limited in versions prior to LOOT 0.13.1. It is recommended to update as soon as possible.'`

**Latest LOOT thread**

`'[Latest LOOT thread](%1%).'`

**SKSE - Required Scripts**

`'It appears you have installed **%1%**, but its required scripts seem to be missing. Please ensure you have correctly installed the scripts bundled with the **%2%** installation archive.'`

**SKSE Plugins - Requirements**

`'You have installed an %1% Plugin but %1% was not found! See %1% download page: %2%.'`

**Comment by CptMcSplody** [comment]
###### Semi Compatible
```yaml
  - &semiCompatible
    type: say
    content:
      - lang: en
        text: '%1% is not fully compatible with this mod. %2%'
      - lang: de
        text: '%1% ist nicht komplett kompatibel mit diesem Mod. %2%'
```
###### Requires MCM
```yaml
  - &requiresMCM
    type: warn
    content:
      - lang: en
        text: 'A **Mod Configuration Menu** is required for this mod to be fully functional. An **MCM** can be added by installing [SkyUI SE](https://www.nexusmods.com/skyrimspecialedition/mods/12604).'
```
###### Patch Messages

> 'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin''s mod page.'

> 'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is included with this plugin''s installer.'

> 'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A third party patch is available here: %2%'

```yaml
  - &patchProvided
    type: say
    content:
      - lang: en
        text: 'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin''s mod page.'
      - lang: de
        text: 'Sie scheinen **%1%** zu nutzen, aber sie haben keinen Kompatibilitätspatch für diesen Mod aktiviert. Ein Kompatibilitätspatch wird auf dieser Plugins Mod-Seite zur Verfügung gestellt.'
  - &patchIncluded
    type: say
    content:
      - lang: en
        text: 'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A compatibility patch is included with this plugin''s installer.'
      - lang: de
        text: 'Sie scheinen **%1%** zu nutzen, aber sie haben keinen Kompatibilitätspatch für diesen Mod aktiviert. Ein Kompatibilitätspatch ist enthalten mit diesen Plugins Installer.'
  - &patch3rdParty
    type: say
    content:
      - lang: en
        text: 'You seem to be using **%1%**, but you have not enabled a compatibility patch for this mod. A third party patch is available here: %2%'
      - lang: de
        text: 'Sie scheinen **%1%** zu nutzen, aber sie haben keinen Kompatibilitätspatch für diesen Mod aktiviert. Ein Patch von Dritten ist hier verfügbar: %2%'
```

**Comment by ironmagician** [comment]
Hey. I can do the **'pt'** ones, since I'm a native portuguese.
Already got the masterlist file and I'm working on it.
Would you prefer that I use Git or that I simply send you the altered file?

(p.s.: Also adding translations to the 'cleaning data' messages, since I'm on it)

**Comment by pStyl3** [comment]
Pull Requests are preferred I would assume, but in case someone doesn't know how to use Git, posting here would also do the job.

Also: @loot/translators Anyone wants to help out?

**Comment by MacSplody** [comment]
> Pull Requests are preferred I would assume, but in case someone doesn't know how to use Git, posting here would also do the job.

Exactly, either is perfectly fine.

**Comment by ironmagician** [comment]
Done with the **pt** translation.  Also translated pretty much everything that was ready to be translated into portuguese (followed the string"lang: en")

**Comment by MacSplody** [comment]
@ironmagician Thanks, I left a review on that pull request. Two minor issues that need to be corrected.
I'll review when it's updated.

**Comment by pStyl3** [comment]
@tktk11
Could you take a look at the above messages that still need to be translated to japanese? Any help with this would be much appreciated.

**Comment by tktk11** [comment]
I just translate it and send pull request, so please check it.

**Comment by TokcDK** [comment]
Added pull request with russian localization of messages on top of the masterlist.

**Comment by pStyl3** [comment]
@Freso Could you translate the rest for the danish translation?

**Comment by Yoosk** [comment]
I will take care of polish translation, pull request will come soon.

**Comment by MacSplody** [comment]
@Yoosk Thanks.

**Comment by pStyl3** [comment]
@simoneddeland Would you be interested in translating the two remaining messages mentioned in this issue into Swedish as well? (`Fnis reminder` and `Script Extender - Required Scripts`) Maybe even translate some for the masterlist for Skyrim Legendary Edition?

@ThePotatoChronicler You did some Czech translations for LOOT in the past. Would you be willing to translate the messages mentioned here?

**Comment by DaCoolX** [comment]
German so far is done and I am often ontop other more rare/minor messages to be translated but am open to receive pings or notifications should a message have been added or changed and thus be needed to be translated.

**Comment by MacSplody** [comment]
Backup of total progress; I'm trimming checkboxes from main post.

### _common_

- [ ] `&alreadyInX`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] `&alreadyInOrFixedByX`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [ ] Japanese (ja)
  - [ ] Korean (ko)
  - [x] Polish (pl)
  - [ ] Portuguese (pt)
  - [ ] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&compatNotes`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&corrupt`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&deletePlugin`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&doNotClean`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] `&includesX`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&missingRequirementXforY`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [ ] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&missingRequirementXforPlugin`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [ ] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&obsolete`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [ ] Portuguese (pt)
  - [ ] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] `&patch3rdParty`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&patchIncluded`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&patchProvided`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&patchUpdateAvailable`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&requiresMCM`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&requiresSKSE`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] `&requiresX`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [ ] Portuguese (pt)
  - [ ] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&semiCompatible`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&sortMasters`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&useBashTweakInstead`
  - [ ] Bulgarian (bg)
  - [ ] (da) Danish
  - [x] (de) German
  - [ ] (es) Spanish
  - [ ] (fi) Finnish
  - [ ] (fr) French
  - [ ] (ja) Japanese
  - [ ] (ko) Korean
  - [ ] (pl) Polish
  - [ ] (pt) Portuguese
  - [ ] (pt_BR) Portuguese Brazilian
  - [ ] (ru) Russian
  - [ ] (sv) Swedish
  - [ ] (zh_CN) Chinese

- [ ] `&useOnlyOneX`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] `&versionOldX`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] `&versionUpToDateX`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] `&versionXIncY`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&wildEdits`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [x] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [ ] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] `&reqManualFix`
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [ ] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [x] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

---

### _Globals_

- [ ] **LOOT CC Handling**
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [ ] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [ ] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [ ] Chinese (zh_CN)

- [ ] **LOOT Forum thread**
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [x] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [ ] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [x] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] **Fnis reminder**
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [x] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [x] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [ ] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [ ] Swedish (sv)
  - [x] Chinese (zh_CN)

- [ ] **Script Extender - Required Scripts**
  - [ ] Bulgarian (bg)
  - [ ] Czech (cs)
  - [ ] Danish (da)
  - [x] German (de)
  - [ ] Spanish (es)
  - [ ] Finnish (fi)
  - [ ] French (fr)
  - [x] Japanese (ja)
  - [ ] Korean (ko)
  - [x] Polish (pl)
  - [x] Portuguese (pt)
  - [ ] Portuguese Brazilian (pt_BR)
  - [x] Russian (ru)
  - [ ] Swedish (sv)
  - [ ] Chinese (zh_CN)

---

```yaml
    msg:
      - type: warn
        condition: 'active("Ordinator - Perks of Skyrim.esp") and not active("unofficial skyrim survival patch.esp") and not active("unofficial skyrim survival patch.esl") and not active("Unofficial Skyrim Creation Club Content Patch.esl")'
        content:
          - lang: en
            text: '[%1%] has a [Known bug](%2%) which is incompatible with [%3%]. Consider using the %4% to fix this bug.'
          - lang: de
            text: '[%1%] hat einen [bekannten Fehler](%2%), welcher es inkompatibel mit [%3%] macht. Der %4% behebt diesen Fehler.'
          - lang: ja
            text: '[%1%]は既知のバグ( (%2%)として[%3%]と互換性がありません。このバグを修正するには、%4%の使用を検討してください。'
          - lang: pt
            text: '[%1%] contém um [erro identificado](%2%) em que é incompatível com [%3%]. Considere utilizar o %4% para reparar este erro.'
        subs:
          - 'ccqdrsse001-survivalmode.esl'
          - 'https://www.nexusmods.com/skyrimspecialedition/articles/22/'
          - 'Ordinator - Perks of Skyrim.esp'
          - '[Unofficial Skyrim Survival Patch](https://www.nexusmods.com/skyrimspecialedition/mods/12655/)'
```
