### ISSUE TITLE
Distinct Interiors - 13 UDR and 1 NAV

### ISSUE THREAD

**Issue by Teabag86** [loot/skyrimse#657]
https://www.nexusmods.com/skyrimspecialedition/mods/6130

![Capture](https://user-images.githubusercontent.com/43588812/56456456-1c32dc80-63b0-11e9-88b0-acc0fcfb062f.PNG)

**Comment by Teabag86** [comment]
Nav is probably a false positive. The Nav record is deleted by Hearthfire yet for some reason the deleted record has been included in Distinct Interiors which is flagging a nav deletion from Skyrim.esm.
![Capture](https://user-images.githubusercontent.com/43588812/56456592-bfd0bc80-63b1-11e9-9706-c8f445f72392.PNG)

**Comment by MacSplody** [comment]
@Teabag86 Which version is that?
I've only checked All in one 1.82 and Modular Core 1.81 before.

**Comment by MacSplody** [comment]
I could link to an updated version. Comes up clean with QAC.
[Distinct Interiors - Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/23831)

**Comment by Teabag86** [comment]
That's odd. I am using 1.82 All in One. Not sure why my QAC picked up the UDR's then. I did see the Deleted references in the file whilst completing The Method and thought best to clean the mod. Sorry for the false alarm.

I looked at the Fixes and it removes a lot of content in Whiterun. I did grab their "Fixed greynoise.dds that caused CTDs" file though.

**Comment by MacSplody** [comment]
> That's odd. I am using 1.82 All in One.

Below is what I get, 🤷‍♂️ .

```yaml
  - name: 'Distinct Interiors.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x6977340A
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 1
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0xC6A69F3C
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'Distinct Interiors.esp'
    clean:
      - crc: 0xB337055B
        util: 'SSEEdit v4.0.2'
```

> Sorry for the false alarm.

No worries.

> I looked at the Fixes and it removes a lot of content in Whiterun.

Ah, not really a fix so, just an alternative for compatibility.
Thanks for the info.
