### ISSUE TITLE
Give Better Vampire Lord Transformation a Corruption Message

### ISSUE THREAD

**Issue by Xahtax** [loot/skyrimse#723]
[Better Vampire Lord Transformation](https://www.nexusmods.com/skyrimspecialedition/mods/2659)

This mod is a direct port of a mod that was flagges as corrupted on Skyrim LE. I've heard that  it was made with TESVSnip. 
xEdits QAC gives me this messages:
`[00:09] Error: record RACE contains unexpected (or out of order) subrecord MPAV 5641504D [00:09] Errors were found in: DLC1VampireBeastRace "Vampire Lord" [RACE:0200283A] [00:09] Contained subrecords: EDID FULL DESC SPCT SPLO SPLO SPLO SPLO WNAM BODT KSIZ KWDA DATA MNAM ANAM MODT FNAM ANAM MODT MTNM MTNM MTNM MTNM MTNM VTCK TINL PNAM UNAM ATKD ATKE ATKD ATKE ATKD ATKE ATKD ATKE ATKD ATKE NAM1 MNAM INDX MODL MODT FNAM INDX MODL MODT GNAM NAM3 MNAM MODL MODT FNAM MODL MODT NAM4 NAM5 ONAM LNAM NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME NAME VNAM QNAM QNAM QNAM QNAM UNES PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT PHWT NAM0 FNAM INDX HEAD INDX HEAD INDX HEAD INDX HEAD INDX HEAD MPAI MPAV MPAI MPAV MPAI MPAV MPAI MPAV FTSF DFTF TINI TINT TINP TINI TINT TINP TINI TINT TINP Error: Container.ElementCount {68} > aChildCount {56} for RACE in DLC1VampireBeastRace "Vampire Lord" [RACE:0200283A]`
Note: the mod author has said, that those warnings/the corruption message Loot gives you can be ignored, which is not true afaik.

**Comment by MacSplody** [comment]
Not sure why it has an empty head marker or removes WRLD Map Data.

![image](https://user-images.githubusercontent.com/1944639/60136632-9dd22c80-979c-11e9-999d-de39f78922ed.png)
![image](https://user-images.githubusercontent.com/1944639/60136664-b3dfed00-979c-11e9-8069-6bcf868a676a.png)

![image](https://user-images.githubusercontent.com/1944639/60136747-ef7ab700-979c-11e9-82eb-80792989f599.png)

**Comment by MacSplody** [comment]
Form Version 40, next object ID updated by CK save.
![image](https://user-images.githubusercontent.com/1944639/60136955-821b5600-979d-11e9-810d-3001e73da3a8.png)

**Comment by MacSplody** [comment]
@Xahtax The metadata for these plugins can be copied from the Skyrim Masterlist.

_common_ entry.
```yaml
  - &corrupt
    type: warn
    content:
      - lang: en
        text: 'This file is corrupt and should not be used.'
      - lang: ru
        text: 'Файл испорчен и не должен использоваться.'
      - lang: es
        text: 'Este archivo puede corromper tu juego y no debería ser utilizado.'
      - lang: ja
        text: 'このファイルは壊れています。使用しないでください。'
```
_plugins_ entry.
```yaml
  - name: 'BVLT - (Argonian|Ashen|Dark Elf|High Elf|Human|Khajiit|Wood Elf)?\.esp'
    msg: [ *corrupt ]
```
