### ISSUE TITLE
Enhanced Vanilla Trees plugin name has changed

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#734]
[Enhanced Vanilla Trees SE](https://www.nexusmods.com/skyrimspecialedition/mods/11008)

Old plugin name `SRG Enhanced Trees Activator.esp`
New plugin name `Enhanced Vanilla Trees SSE.esp`

Current meta data for `SRG Enhanced Trees Activator.esp`

```yaml
  - name: 'SRG Enhanced Trees Activator.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/11008'
        name: 'Enhanced Vanilla Trees'
    group: *floraGroup
    inc:
      - 'SimplyBiggerTreesSE.esp'
      - 'Skyrim Flora Overhaul.esp'

  - name: 'S3DTrees NextGenerationForests.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/12371/' ]
    inc:
      - 'SRG Enhanced Trees Activator.esp'

  - name: 'SkyrimIsWindy - EVT patch.esp'
    group: *floraGroup
    req:
      - 'SkyrimIsWindy.esp'
      - 'SRG Enhanced Trees Activator.esp'
```
