### ISSUE TITLE
JK's skyrim + Great Cities overhaul is probably now doable with the help of this patch

### ISSUE THREAD

**Issue by parsafaramarzi** [loot/skyrimse#741]
https://www.nexusmods.com/skyrimspecialedition/mods/25282

**Comment by MacSplody** [comment]
@parsafaramarzi Looks like it has some major issues going by the comments.
But it's one to keep track of for sure, hopefully they can resolve any issues.

**Comment by parsafaramarzi** [comment]
should i keep putting these sort of posts here or should i move them out of issues section

**Comment by MacSplody** [comment]
In issues is fine for any discussions on changes.

**Comment by MacSplody** [comment]
@parsafaramarzi Closing as I wouldn't recommend using that patch currently.

```yaml
  - name: 'XenonCitiesPatch.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/25282/'
        name: 'JK''s and The Great Cities compatibility refit'
    dirty:
      # version: 1.3
      - <<: *reqManualFix
        crc: 0xF3117ADB
        util: '[SSEEdit v4.0.2f](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 256
        udr: 677
        nav: 32
      # version: 1.3, after QAC
      - <<: *reqManualFix
        crc: 0x96972D29
        util: '[SSEEdit v4.0.2f](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 32
```

**Comment by MacSplody** [comment]
[Xenons City patch (The Great Cities of Skyrim and JKs skyrim compatibility patch)](https://www.nexusmods.com/skyrimspecialedition/mods/25282)

version 3.0 is clean.

```yaml
  - name: 'The Great JK''s Cities.esp'
    clean:
      - crc: 0xE0CA35BC
        util: 'SSEEdit v4.0.3'
```

- [x] Update cleaning info.
- [x] Update The Great Cities of Skyrim and JKs skyrim compatibility.
- [x] Add patch message.
