### ISSUE TITLE
Aurlyn Dawnstone - Cleaning Info

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#800]
[Aurlyn Dawnstone - The Reclusive Philosopher](https://www.nexusmods.com/skyrimspecialedition/mods/9536)

version: 7.22

```yaml
  - name: 'Aurlyn.esp'
    dirty:
      - <<: *quickClean
        crc: 0x8A9891D9
        util: '[SSEEdit v4.0.2f](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 31
```
