### ISSUE TITLE
Civil War Aftermath - 28 ITM

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#839]
Mod page: https://www.nexusmods.com/skyrimspecialedition/mods/3484

Auto Clean results:

```yaml
 - name: 'Civil War Aftermath.esp'
    dirty:
      - <<: *quickClean
        crc: 0x7F868FE8
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 28
    clean:
      - crc: 0xB99E96A8
        util: 'SSEEdit v4.0.2'
```
