### ISSUE TITLE
Artifacts of Skyrim - 1 ITM

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#840]
Mod page: https://www.nexusmods.com/skyrimspecialedition/mods/2431

Auto Clean results:

```yaml
 - name: 'Artifacts.esp'
    dirty:
      - <<: *quickClean
        crc: 0x23847A1C
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1
    clean:
      - crc: 0x65FE1C0B
        util: 'SSEEdit v4.0.2'
```
