### ISSUE TITLE
The Staff Of Sheogorath - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#848]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/14468

Version: 1.0

QAC Report:

```yaml
 - name: 'StaffOfSheogorath.esp'
    dirty:
      - <<: *quickClean
        crc: 0x9B0E1A85
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 18
    clean:
      - crc: 0xF473FDCA
        util: 'SSEEdit v4.0.2'
```
