### ISSUE TITLE
Ruin's Edge - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#849]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/12792

Version: 1.2

QAC Report:

```yaml
 - name: 'RuinsEdge.esp'
    dirty:
      - <<: *quickClean
        crc: 0xE3C3CF54
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 5
    clean:
      - crc: 0xBBD8F4A4
        util: 'SSEEdit v4.0.2'
```
