### ISSUE TITLE
Adept - Magic of Ash - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#850]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/2350

Mod version: SE1.0

QAC Report:

```yaml
  - name: 'DustAdept.esp'
    dirty:
      - <<: *quickClean
        crc: 0x4E210611
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 4
    clean:
      - crc: 0xE28AA3D1
        util: 'SSEEdit v4.0.2'
```
