### ISSUE TITLE
Chrysamere - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#851]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/12829

Mod version: 1.0

QAC Report:

```yaml
 - name: 'Chrysamere.esp'
    dirty:
      - <<: *quickClean
        crc: 0xD4C67D7F
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
        udr: 1
    clean:
      - crc: 0x16E0F43E
        util: 'SSEEdit v4.0.2'
```
