### ISSUE TITLE
Daedric Realms - Volume I The Hunting Grounds - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#852]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/3140

Mod version: 1.0

QAC Report:

```yaml
 - name: 'StagPrinceBow.esp'
    dirty:
      - <<: *quickClean
        crc: 0x6B66BD44
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 5
    clean:
      - crc: 0x00EB3F5F
        util: 'SSEEdit v4.0.2'
```
