### ISSUE TITLE
Nightwielder Spire - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#853]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/2351

Mod version: SE1.1

QAC Report:

```yaml
  - name: 'ShadowMagic.esp'
    dirty:
      - <<: *quickClean
        crc: 0x32C92E63
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 39
    clean:
      - crc: 0x4F5A73E9
        util: 'SSEEdit v4.0.2'
```
