### ISSUE TITLE
Stendarr's Hammer - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#854]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/12945

Mod version: 1.1

QAC Report:

```yaml
  - name: 'StendarrsHammer.esp'
    dirty:
      - <<: *quickClean
        crc: 0x683930EE
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 18
        udr: 1
    clean:
      - crc: 0x4BFA89B0
        util: 'SSEEdit v4.0.2'
```
