### ISSUE TITLE
Reach Magic - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#855]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/5209

Mod version: 1.0

QAC Report:

```yaml
  - name: 'ReachMage.esp'
    dirty:
      - <<: *quickClean
        crc: 0x674BDEC6
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
        udr: 10
    clean:
      - crc: 0xED719340
        util: 'SSEEdit v4.0.2'
```

**Part two:  Reach Magic - Unique Uniques Compatability (ReachMagicIS.esp)**

QAC Report:

```yaml
  - name: 'ReachMageIS.esp'
    dirty:
      - <<: *quickClean
        crc: 0xCC209536
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
        udr: 10
    clean:
      - crc: 0xB04D3647
        util: 'SSEEdit v4.0.2'
```
