### ISSUE TITLE
Aetherium Armor and Weapons Compilation by lautasantenni - QAC Report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#856]
Mod link: https://www.nexusmods.com/skyrimspecialedition/mods/2687

Version: 1.0

QAC Report:

```yaml
  - name: 'AetheriumSwordsnArmor.esp'
    dirty:
      - <<: *quickClean
        crc: 0xC2285F24
        util: '[SSEEdit v4.0.2h](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 7
    clean:
      - crc: 0xFA7F23A7
        util: 'SSEEdit v4.0.2h'
```
