### ISSUE TITLE
Conflicting messages about ITM records on MLU - Immersive Armors.esp

### ISSUE THREAD

**Issue by ubeogesh** [loot/skyrimse#861]
I've noticed that there are conflicting messages on the "MLU - Immersive Armors.esp".

It says "do not clean", but at the same time it recommends cleaning ITM records. Should one of these should be removed? I tried doing the QuickAutoClean on this plugin, and it didn't break the game or anything like that; however I'm not sure exactly what changes I am supposed to be looking at to see if it makes a difference.

```  
- name: 'MLU - Immersive Armors.esp'
    msg: [ *doNotClean ]
    tag:
      - Delev
      - Invent
      - Names
      - Relev
      - Stats
    dirty:
      # version: 1.1a.1
      - <<: *quickClean
        crc: 0xCDB3B128
        util: '[SSEEdit v4.0.2f](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 16
```
