### ISSUE TITLE
Player Homes - Cleaning Info

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#876]
- [x] [Alchemist's Retreat](https://www.nexusmods.com/skyrimspecialedition/mods/29358)
- [x] [Ash's Rest - Solstheim Dunmer Player Home](https://www.nexusmods.com/skyrimspecialedition/mods/28526)
- [x] [Bjartholm - An Apocrypha Home](https://www.nexusmods.com/skyrimspecialedition/mods/29585)
- [x] [Breezehome Extra (Less) Breezy With General Stores](https://www.nexusmods.com/skyrimspecialedition/mods/24824)
- [x] [Breezehome TNF Expanded for SSE](https://www.nexusmods.com/skyrimspecialedition/mods/25078)
- [x] [Build Your Own Breezehome SSE](https://www.nexusmods.com/skyrimspecialedition/mods/28380)
- [x] [Deithwen - Witcher Inspired Home](https://www.nexusmods.com/skyrimspecialedition/mods/29935)

- [x] [Falkreath Cave House SSE](https://www.nexusmods.com/skyrimspecialedition/mods/28337)
- [x] [Indaren Estate - Redoran themed home in Raven Rock](https://www.nexusmods.com/skyrimspecialedition/mods/26211)
- [x] [Lakeside Hideaway](https://www.nexusmods.com/skyrimspecialedition/mods/27342)
- [x] [Lakeview Manor Runestones](https://www.nexusmods.com/skyrimspecialedition/mods/29405)
- [x] [Methmod4 (Player Home)](https://www.nexusmods.com/skyrimspecialedition/mods/27712)
- [x] [Mighty Nine's Photo Studio](https://www.nexusmods.com/skyrimspecialedition/mods/10034)
- [x] [Miserith Hall](https://www.nexusmods.com/skyrimspecialedition/mods/25693)
- [x] [Morwen's Couple House](https://www.nexusmods.com/skyrimspecialedition/mods/26870)
- [x] [Muzuleft Special Edition](https://www.nexusmods.com/skyrimspecialedition/mods/29810)
- [x] [Mysterious Greenhouse](https://www.nexusmods.com/skyrimspecialedition/mods/25026)
- [x] [Mysterious Workshop](https://www.nexusmods.com/skyrimspecialedition/mods/25027)
- [x] [Nutcase Compound](https://www.nexusmods.com/skyrimspecialedition/mods/29737)
- [x] [Rose's Cottage](https://www.nexusmods.com/skyrimspecialedition/mods/18580)
- [x] [Sea Dragon - A player Home Ship](https://www.nexusmods.com/skyrimspecialedition/mods/27119)
- [x] [Shalidor's Fortress of Ice](https://www.nexusmods.com/skyrimspecialedition/mods/26095)
- [x] [SPH1's Rorikstead Farmhouse](https://www.nexusmods.com/skyrimspecialedition/mods/20737)
- [x] [Stoop Over Markarth -- Vlindrel Hall Elevated Patio](https://www.nexusmods.com/skyrimspecialedition/mods/25090)
- [x] [Udaur Ranger Camp](https://www.nexusmods.com/skyrimspecialedition/mods/7908)
- [x] [Vandfald Cottage - A Player Home](https://www.nexusmods.com/skyrimspecialedition/mods/28071)
- [x] [Whiterun Mansion](https://www.nexusmods.com/skyrimspecialedition/mods/29196)
- [x] [Winterhold Beacon](https://www.nexusmods.com/skyrimspecialedition/mods/27657)
- [x] [WolfSkull Manor - A Riften Thief Player Home](https://www.nexusmods.com/skyrimspecialedition/mods/27565)

**Comment by CptMcSplody** [comment]
```yaml
  - name: 'jdcHome.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xA4F3FC7D
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 12
        nav: 1
      - <<: *reqManualFix
        crc: 0x83626886
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'Methmannor4.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xB228484B
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 106
        nav: 56
      - <<: *reqManualFix
        crc: 0xCB6B5B59
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 56

  - name: 'MorwenCoupleHouse.esp'
    dirty:
      - <<: *quickClean
        crc: 0xEA79AD86
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
        udr: 34

  - name: 'Dragon Home.esp'
    dirty:
      - <<: *quickClean
        crc: 0xCB96D39C
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 6

  - name: 'ThievesDen.esp'
    dirty:
      - <<: *quickClean
        crc: 0xDA57185B
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 7

  - name: 'Lakehold_house.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xA11E1065
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 58
        udr: 6
        nav: 1
      - <<: *reqManualFix
        crc: 0x961D546A
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1
  - name: 'Lakehold_nohouse.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x60F24B2B
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 58
        udr: 6
        nav: 1
      - <<: *reqManualFix
        crc: 0x39BE89C8
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'RDSSE_The_Cave.esp'
    dirty:
      - <<: *quickClean
        crc: 0x63CF31C0
        util: '[SSEEdit v4.0.2j](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 9
```
