### ISSUE TITLE
Destructible Skyrim - Cleaning info & Conflicts

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#890]
#### [Destructible Skyrim - Breakable Objects SE (Beta)](https://www.nexusmods.com/skyrimspecialedition/mods/28291)

```yaml
  - name: 'Destructible Skyrim.esp'
    dirty:
      - <<: *quickClean
        crc: 0xAF111F67
        util: '[SSEEdit v4.0.2k](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 584
```

Conflicts with:

`Blowing in the Wind SSE.esp`

![image](https://user-images.githubusercontent.com/1944639/68165861-82500d00-ff58-11e9-9dd4-70c6bf8f7732.png)

Reverts changes made by `SMIM-SE-Merged-All.esp`.
No conflicts if `SMIM-SE-Merged-All.esp` is after `Destructible Skyrim.esp`
![image](https://user-images.githubusercontent.com/1944639/68166033-fbe7fb00-ff58-11e9-8274-5405143ab281.png)

`Cutting Room Floor.esp`

![image](https://user-images.githubusercontent.com/1944639/68166570-a4e32580-ff5a-11e9-9519-64878f580b8a.png)

---

- [x] Add Cleaning Info.
- [x] Sort before conflicting mods.
