### ISSUE TITLE
Legacy of the Dragonborn V5 Updates

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#922]
### [Legacy of the Dragonborn SSE](https://www.nexusmods.com/skyrimspecialedition/mods/11802)

All patches have been moved to a new page [Legacy of the Dragonborn Patches (Official)](https://www.nexusmods.com/skyrimspecialedition/mods/30980).

- [x] Remove patch provided messages from LotD plugin.
- [x] Add 3rd party patch messages to patched mods.
- [ ] Add already included in X messages to included mods.
- [x] Update cleaning info.
- [x] Update compatibility info.

**Comment by Xahtax** [comment]
Legacy was cleaned with the v5.0.23 update.
```
 - name: 'LegacyoftheDragonborn.esm'
    clean:
      - crc: 0xDC39CE6D
        util: 'SSEEdit v4.0.3'
```

I looked at the masterlist and I have to admit that I don't think that I will be able to make the edits myself, but I can ask the legacy devs about any required changes.

**Comment by Xahtax** [comment]
https://www.nexusmods.com/skyrimspecialedition/articles/1494
Some incompatible mods.

**Comment by MacSplody** [comment]
Patch provided messages removed.

```yaml
  - name: 'LegacyoftheDragonborn.esm'
    msg:
      - <<: *patchProvided
        subs: [ 'Advanced Adversary Encounters' ]
        condition: 'active("AAE Ultimate Edition.esp") and not active("DBM_AAE_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Amulets of Skyrim' ]
        condition: 'active("SL01AmuletsSkyrim.esp") and not active("DBM_AmuletsOfSkyrim_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Apophysis Dragon Priest Masks' ]
        condition: 'active("Apophysis_DPM_SE.esp") and not active("DBM_Apophysis_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Artifacts - The Ice Blade of the Monarch' ]
        condition: 'active("IceBladeOfTheMonarch.esp") and not active("DBM_IceBladeMonarch_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Artifacts - The Tournament of the Ten Bloods' ]
        condition: 'active("ArtifactsOfBoethiah.esp") and not active("DBM_ArtifactsOfBoethiah_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Artificer - Artifacts of Skyrim' ]
        condition: 'active("Artificer - Artifacts of Skyrim.esp") and not active("DBM_Artificer_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Audio Overhaul Skyrim' ]
        condition: 'active("Audio Overhaul Skyrim.esp") and not active("DBM_AOS_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Better Skill and Quest Books Names' ]
        condition: 'active("Better Skill and Quest Books Names SE.esp") and not active("BCS_BSQBN _Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Beyond Reach' ]
        condition: 'active("arnima.esm") and not active("DBM_BeyondReach_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Beyond Skyrim - Bruma' ]
        condition: 'active("BSHeartland.esm") and not active("DBM_Bruma_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Barely Used Vanilla Actors Recycle Project' ]
        condition: 'active("BUVARP.esp") and not active("DBM_BUVARP_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Cloaks of Skyrim' ]
        condition: 'active("Cloaks.esp") and not active("DBM_Cloaks_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Cutting Room Floor' ]
        condition: 'active("Cutting Room Floor.esp") and not active("DBM_CRF_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Daedric Cloaks' ]
        condition: 'active("DaedricCloaks.esp") and not active("DBM_DaedricCloaks_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Daedric Realms' ]
        condition: 'active("StagPrinceBow.esp") and not active("DBM_StagPrinceBow_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Dark Brotherhood for Good Guys' ]
        condition: 'active("goodbrother.esp") and not active("DBM_GoodBrother_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Dawnguard and Clan Volkihar Epilogues' ]
        condition: 'active("Dawnguard&VolkiharArtifactsQuests.esp") and not active("Legendary Skyrim Crossbows.esp") and not active("DBM_DGE_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Dawnguard and Clan Volkihar Epilogues & Legendary Skyrim Crossbows' ]
        condition: 'active("Dawnguard&VolkiharArtifactsQuests.esp") and active("Legendary Skyrim Crossbows.esp") and not active("DBM_DGE_Crossbow_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Dynamic Dungeon Loot' ]
        condition: 'active("DynamicDungeonLoot.esp") and not active("DBM_DDL_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Elemental Dragons' ]
        condition: 'active("Elemental_Dragons.esp") and not active("DBM_ElementalDragons_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Even Better Quest Objectives' ]
        condition: 'active("BetterQuestObjectives.esp") and not active("BetterQuestObjectives - BCS Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Heavy Armory - New Weapons' ]
        condition: 'active("Prvtl_HeavyArmory.esp") and not active("DBM_HA_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Helgen Reborn' ]
        condition: 'active("Helgen Reborn.esp") and not active("DBM_HelgenReborn_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Holds the City Overhaul' ]
        condition: 'active("Holds.esp") and not active("DBM_Holds_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Immersive Armors' ]
        condition: 'active("Hothtrooper44_ArmorCompilation.esp") and not active("DBM_IA_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Immersive Jewelry' ]
        condition: 'active("Immersive Jewelry.esp") and not active("DBM_ImmersiveJewelry_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Immersive Sounds Compendium' ]
        condition: 'active("Immersive Sounds - Compendium.esp") and not active("DBM_ISC_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Immersive Weapons' ]
        condition: 'active("Immersive Weapons.esp") and not active("DBM_IW_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'iNeed' ]
        condition: 'active("iNeed - Extended.esp") and not active("DBM_iNeed_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Legendary Skyrim Crossbows' ]
        condition: 'active("Legendary Skyrim Crossbows.esp") and not active("Dawnguard&VolkiharArtifactsQuests.esp") and not active("DBM_KelCrossbowPatch.esp")'
      - <<: *patchProvided
        subs: [ 'Moon and Star' ]
        condition: 'active("MoonAndStar_MAS.esp") and not active("DBM_MAS_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'MorrowLoot Ultimate' ]
        condition: 'active("MLU.esp") and not active("DBM_MLU_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Mystic Condenser' ]
        condition: 'active("Mystic Condenser.esp") and not active("DBM_MysticCondenser_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Namira for Good Guys' ]
        condition: 'active("AK- Namira for Good Guys.esp") and not active("DBM_Namira_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Not So Fast - Main Quest' ]
        condition: 'active("NotSoFast-MainQuest.esp") and not active("BCS_NotSoFast_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Oblivion Artifact Pack' ]
        condition: 'active("WZOblivionArtifacts.esp") and not active("DBM_OblivionArtifacts_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Open Cities' ]
        condition: 'active("Open Cities Skyrim.esp") and not active("DBM_OpenCities_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Opulent Outfits AIO' ]
        condition: 'active("OpulentOutfits_2017-SSE AIO.esp") and not active("DBM_OpulentAIO_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Opulent Outfits Replacer' ]
        condition: 'active("OpulentOutfits_2017-SSE Replacer.esp") and not active("DBM_OpulentREP_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Path of the Revenant' ]
        condition: 'active("bloodworm.esp") and not active("DBM_Bloodworm_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Palaces and Castles Enhanced' ]
        condition: 'active("Palaces Castles Enhanced.esp") and not active("PCE - Legacy of the Dragonborn Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Project AHO' ]
        condition: 'active("Dwarfsphere.esp") and not active("DBM_AHO_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Reach Magic' ]
        condition: 'active("ReachMage.esp") and not active("DBM_ReachMage_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Realistic Needs and Diseases' ]
        condition: 'active("RealisticNeedsandDiseases.esp") and not active("DBM_RND_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Relics of Hyrule' ]
        condition: 'active("RelicsofHyruleDragonborn.esp") and not active("DBM_RelicsofHyrule_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Royal Armory - New Artifacts' ]
        condition: 'active("PrvtlRoyalArmory.esp") and not active("DBM_RoyalArmory_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'RS Children Overhaul' ]
        condition: 'active("RSChildren.esp") and not active("DBM_RSChildren.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Ruin''s Edge' ]
        condition: 'active("RuinsEdge.esp") and not active("DBM_RuinsEdge_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Skyrim Alchemy and Food Overhaul' ]
        condition: 'active("SAFO.esp") and not active("DBM_SAFO_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Skyrim Immersive Creatures' ]
        condition: 'active("Skyrim Immersive Creatures Special Edition.esp") and not active("DBM_ImmersiveCreatures_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Skyrim Revamped - Loot and Encounter Zones' ]
        condition: 'active("Skyrim Revamped.esp") and not active("DBM_SRLEZ_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Skyrim Revamped - Complete Enemy Overhaul' ]
        condition: 'active("Skyrim Revamped - Complete Enemy Overhaul.esp") and not active("DBM_SRCEO_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Skyrim Underground' ]
        condition: 'active("AKSkyrimUnderground.esp") and not active("DBM_SkyrimUnderground_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'SkyTEST - Harder Creatures' ]
        condition: 'active("SkyTEST-HarderCreatures.esp") and not active("DBM_STHC_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Snazzy Furniture and Clutter Overhaul' ]
        condition: 'active("Snazzy Furniture and Clutter Overhaul.esp") and not active("SFCO - LotD Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Solitude Skyway' ]
        condition: 'active("Solitude Skyway SE.esp") and not active("DBM_Skyway_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Tamrielic Culture' ]
        condition: 'active("WZTamrielic Culture.esp") and not active("DBM_TamrielicCulture_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'The Choice is Yours' ]
        condition: 'active("TheChoiceIsYours.esp") and not active("BCS_TCIY_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'The Men of Winter' ]
        condition: 'active("Men of Winter.esp") and not active("DBM_MenofWinter_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'The Staff of Sheogorath' ]
        condition: 'active("StaffOfSheogorath.esp") and not active("DBM_StaffofSheogorath_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'True Artifacts' ]
        condition: 'active("TrueArtifactsofSkyrim.esp") and not active("DBM_TAS_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Ultimate Deadly Encounters' ]
        condition: 'active("SOTFull.esp") and not active("DBM_SoT_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Undeath Remastered' ]
        condition: 'active("Undeath.esp") and not active("DBM_Undeath_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Unique Loot' ]
        condition: 'active("mrbs-uniqueloot-se.esp") and not active("DBM_UniqueLoot_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Vigilant' ]
        condition: 'active("Vigilant.esp") and not active("DBM_Vigilant_Patch.esp") and not active("LOTD Patches Merged.esp")'
      - <<: *patchProvided
        subs: [ 'Wild World' ]
        condition: 'active("Wild World.esp") and not active("DBM_WildWorld_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Yet Another Skyrim Hardcore Mod' ]
        condition: 'active("YASH2.esp") and not active("DBM_YASH_Patch.esp")'
      - <<: *patchProvided
        subs: [ 'Zim''s Immersive Artifacts' ]
        condition: 'active("ZIA_Complete Pack_V4.esp") and not active("DBM_ZimsImmersiveArtifacts_Patch.esp")'
```

Old patch metadata

```yaml
  - name: 'DBM_AOS_Patch.esp'
    group: *underridesGroup
    tag:
      - Graphics
      - Sound
  - name: 'DBM_CRF_Patch.esp'
    group: *underridesGroup
    tag:
      - Graphics
      - Names
      - Stats
  - name: 'DBM_HelgenReborn_Patch.esp'
    tag: [ C.Location ]
  - name: 'DBM_ISC_Patch.esp'
    group: *underridesGroup
    tag: [ Sound ]
  - name: 'DBM_MAS_Patch.esp'
    after:
      - 'MoonAndStar_ImmersionPatch.esp'
  - name: 'DBM_OpenCities_Patch.esp'
    tag: [ C.Location ]
  - name: 'DBM_SkyrimUnderground_Patch.esp'
    tag: [ Invent ]
  - name: 'DBM_WACCF_Patch.esp'
    group: *underridesGroup
    after:
      - 'DBM_CRF_Patch.esp'
      - 'DBM_ISC_Patch.esp'
      - 'Qw_WACCF_CRF Patch.esp'
```
