### ISSUE TITLE
Treasure Hunter for SSE - Cleaning report

### ISSUE THREAD

**Issue by Sabre142** [loot/skyrimse#941]
Mod name: Treasure Hunter for SSE

Version: 1.1

Link: https://www.nexusmods.com/skyrimspecialedition/mods/5789/

QAC report:

```yaml
  - name: 'TreasureHunter.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x615E9874
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 9
        nav: 5
    dirty:
      - <<: *reqManualFix
        crc: 0xC63DD30E
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 5
```
