### ISSUE TITLE
Cleaning info for Solemn Keep Chronicles

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#976]
[Solemn Keep Chronicles - Shimmerfall Springs](https://www.nexusmods.com/skyrimspecialedition/mods/11037)

```yaml
  - name: 'SolemnKeep.esp'
    dirty:
      - <<: *quickClean
        crc: 0x883638C7
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 14
    clean:
      - crc: 0x0F77C8CE
        util: 'SSEEdit v4.0.3'
```
Version 1.1.0
