### ISSUE TITLE
Cleaning info for Friendlier Taverns

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#979]
### [Friendlier Taverns](https://www.nexusmods.com/skyrimspecialedition/mods/2506)
version 1.8.1

```yaml
  - name: 'Friendlier Taverns.esp'
    dirty:
      - <<: *quickClean
        crc: 0x6B2AFBBC
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 5
        udr: 17
    clean:
      - crc: 0xC733E9CA
        util: 'SSEEdit v4.0.3'
```

---

### [Friendlier Taverns with Baths](https://www.nexusmods.com/skyrimspecialedition/mods/1399)

version 2.7 Baths and Barns

```yaml
  - name: 'Friendlier Taverns.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x0C38A36A
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 198
        udr: 28
        nav: 2
      - <<: *reqManualFix
        crc: 0xB66104FF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 2
```

version 2.8.3 Baths and Bathers (and Barns)

```yaml
  - name: 'Friendlier Taverns.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x4773C8FF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 2
```

version 2.7.4 No Barns

```yaml
  - name: 'Friendlier Taverns.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x4F6EC655
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 199
        udr: 30
        nav: 2
      - <<: *reqManualFix
        crc: 0xC42B5E1E
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 2
```
