### ISSUE TITLE
Cleaning info for Depths of Skyrim

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#980]
### [Depths of Skyrim - An Underwater Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/26913)

version 1.0.7

```yaml
  - name: 'DepthsOfSkyrim.esp'
    clean:
      - crc: 0xB380C597
        util: 'SSEEdit v4.0.3'
```
