### ISSUE TITLE
Cleaning info for Mammoth Manor

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#982]
[Mammoth Manor](https://www.nexusmods.com/skyrimspecialedition/mods/9710)

version 1.0.2

```yaml
  - name: 'MammothManor.esp'
    dirty:
      - <<: *quickClean
        crc: 0x51C76901
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 18
    clean:
      - crc: 0xC2AEE421
        util: 'SSEEdit v4.0.3'
```
