### ISSUE TITLE
Cleaning info for Ravengrave

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#983]
### [Ravengrave](https://www.nexusmods.com/skyrimspecialedition/mods/6570)
version 3.0

```yaml
  - name: 'Ravengrave.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x14B4ADCF
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 159
        udr: 209
        nav: 1
      - <<: *reqManualFix
        crc: 0x15078B91
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1
```
