### ISSUE TITLE
Cleaning info for Beyond Skyrim - Wares of Tamriel

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#987]
[Beyond Skyrim - Wares of Tamriel SE](https://www.nexusmods.com/skyrimspecialedition/mods/31519)
version 1.1
```yaml
  - name: 'BeyondSkyrimMerchant.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xE3B8C9F8
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1
```
