### ISSUE TITLE
Cleaning info for Realistic Winterhold

### ISSUE THREAD

**Issue by MacSplody** [loot/skyrimse#996]
### [Realistic Winterhold](https://www.nexusmods.com/skyrimspecialedition/mods/14384)

Version 1.0.1
```yaml
  - name: 'RealisticWinterhold.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x6C1AA296
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 77
        udr: 36
        nav: 1
      - <<: *reqManualFix
        crc: 0xF9F9AF0E
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1
```
